
# since this plugin contains mulitple object files - define the extra ones
# here. The standard ones are added by 'makeplug'

CSRC =					\
	$(CURDIR)/babinwor.c			\
	$(CURDIR)/baclump.c			\
	$(CURDIR)/bageomet.c			\
	$(CURDIR)/balight.c			\
	$(CURDIR)/bamateri.c			\
	$(CURDIR)/bamatlst.c			\
	$(CURDIR)/bamesh.c			\
	$(CURDIR)/bameshop.c			\
	$(CURDIR)/basector.c			\
	$(CURDIR)/baworld.c			\
	$(CURDIR)/baworobj.c

PLUGIN = rpworld

ifndef BASEDIR
BASEDIR = $(CURDIR)/..
endif
include $(BASEDIR)/makeincl/makewrld

