/*
 * This is a required file for each plugin. It should be generated by the 
 * plugin vendor. The information contained in this file should be unique
 * derived from the vendor id / name to prevent conflict with other plugins
 */

/* rwPLUGIN_ID must be defined in order to use the RenderWare debug/error
 * mechanism
 */

#define rwPLUGIN_ID      0x02
#define rwPLUGIN_ERRFUNC _rwdb_CriterionWorld
#define rwPLUGIN_ERRENUM e_rwdb_CriterionWorld
#define rwPLUGIN_ERRENUMLAST e_rwdb_CriterionWorldLAST
