#pragma once

enum eSUPERIOR_TYPE
{
  eSUPERIOR_STR = 0,
  eSUPERIOR_CON,
  eSUPERIOR_FOC,
  eSUPERIOR_DEX,
  eSUPERIOR_SOL,
  eSUPERIOR_ENG,

  eSUPERIOR_COUNT = 0x6,

  eSUPERIOR_RANDOM = 0x64,

  eSUPERIOR_FIRST = eSUPERIOR_STR,
  eSUPERIOR_LAST = eSUPERIOR_ENG,
  eSUPERIOR_INVALID = 0xFF,
};

enum eCHANNEL_ADVANTAGE_TYPE
{
  CHANNEL_ADVANTAGE_STATUS = 0,
  CHANNEL_ADVANTAGE_MOVE_SPEED,
  CHANNEL_ADVANTAGE_VEHICLE_SPEED,

  CHANNEL_ADVANTAGE_COUNT,
  CHANNEL_ADVANTAGE_INVALID = 0xFF,

  CHANNEL_ADVANTAGE_FIRST = CHANNEL_ADVANTAGE_STATUS,
  CHANNEL_ADVANTAGE_LAST = CHANNEL_ADVANTAGE_VEHICLE_SPEED,
};

enum eDBO_TEMP_BI_TYPE
{
  DBO_TEMP_BI_TYPE_SERVER = 0,
  DBO_TEMP_BI_TYPE_SEND,
  DBO_TEMP_BI_TYPE_COUNT,
  DBO_TEMP_BI_TYPE__INVALID = 0xFF,

  DBO_TEMP_BI_TYPE_FIRST = DBO_TEMP_BI_TYPE_SERVER,
  DBO_TEMP_BI_TYPE_LAST = DBO_TEMP_BI_TYPE_COUNT - 1,
};

enum eDBO_REVIVAL_AFTEREFFECT_PENALTY
{
	DBO_REVIVAL_AFTEREFFECT_PENALTY_OFFENCE = 0x0,
	DBO_REVIVAL_AFTEREFFECT_PENALTY_DEFENCE,
	DBO_REVIVAL_AFTEREFFECT_PENALTY_LP_EP,
	DBO_REVIVAL_AFTEREFFECT_PENALTY_RUN_SPEED,

	DBO_REVIVAL_AFTEREFFECT_PENALTY_COUNT,

	DBO_REVIVAL_AFTEREFFECT_PENALTY_FIRST = 0,
	DBO_REVIVAL_AFTEREFFECT_PENALTY_LAST = DBO_REVIVAL_AFTEREFFECT_PENALTY_COUNT - 1,
};

enum eCONTENTS_CONDITION_EVENT
{
	CONT_COND_EVENT_TREE_HEADER = 0x0,
	CONT_COND_EVENT_KILL_MOB_GRADE = 0x1,
	CONT_COND_EVENT_KILL_MOB_GROUP = 0x2,
	CONT_COND_EVENT_KILL_PC_CONTENTS = 0x3,
	CONT_COND_EVENT_KILL_PC_DOJO_SCRAMBLE_CLASS = 0x4,
	CONT_COND_EVENT_KILL_PC_DB_SCRAMBLE_CLASS = 0x5,
	CONT_COND_EVENT_CLEAR_TMQ_SCENARIO = 0x6,
	CONT_COND_EVENT_CLEAR_TMQ_SCENARIO_DIFFICULTY = 0x7,
	CONT_COND_EVENT_CLEAR_QUEST_INDEX = 0x8,
	CONT_COND_EVENT_VICTORY_CONTENTS = 0x9,
	CONT_COND_EVENT_VICTORY_RANKBATTLE_CLASS = 0xA,
	CONT_COND_EVENT_VICTORY_FREEBATTLE_CLASS = 0xB,
	CONT_COND_EVENT_CLASS_CHANGE = 0xC,
	CONT_COND_EVENT_SUMMON_DB = 0xD,
	CONT_COND_EVENT_VICTORY_TENKAICHBUDOKAI_MODE = 0xE,
	CONT_COND_EVENT_CAPTURE_DOJO_SEAL = 0xF,
	CONT_COND_EVENT_CAPTURE_DOJO_SEAL_DOJO = 0x10,
	CONT_COND_EVENT_CLEAR_QUEST = 0x11,
	CONT_COND_EVENT_CLEAR_QUEST_TYPE = 0x12,
	CONT_COND_EVENT_CLEAR_QUEST_AREA = 0x13,
	CONT_COND_EVENT_LEVELUP_HOIPOI_MIX_SKILL_TYPE = 0x14,
	CONT_COND_EVENT_LEARN_MIX_RECIPE = 0x15,
	CONT_COND_EVENT_CREATE_MIX_ITEM_RESULT = 0x16,
	CONT_COND_EVENT_CREATE_MIX_ITEM_RANK = 0x17,
	CONT_COND_EVENT_CREATE_MIX_ITEM_LEVEL = 0x18,
	CONT_COND_EVENT_UPGRADE_ITEM = 0x19,
	CONT_COND_EVENT_UPGRADE_ITEM_TYPE = 0x1A,
	CONT_COND_EVENT_UPGRADE_ITEM_VALUE = 0x1B,
	CONT_COND_EVENT_EQUIP_ITEM_RANK = 0x1C,
	CONT_COND_EVENT_EQUIP_ITEM_BATTLE_ATTRIBUTE = 0x1D,
	CONT_COND_EVENT_LEARN_CLASS_SKILL = 0x1E,
	CONT_COND_EVENT_LEARN_FINALITY_CLASS_SKILL = 0x1F,
	CONT_COND_EVENT_REGIST_DOJO = 0x20,
	CONT_COND_EVENT_REGIST_MASCOT = 0x21,
	CONT_COND_EVENT_REGIST_ZENY = 0x22,
	CONT_COND_EVENT_MILEAGE_POINT = 0x23,
	CONT_COND_EVENT_MILEAGE_POINT_CONTENTS = 0x24,
	CONT_COND_EVENT_TRADE_PC = 0x25,
	CONT_COND_EVENT_SELL_TMP = 0x26,
	CONT_COND_EVENT_BUY_TMP = 0x27,
	CONT_COND_EVENT_REPAIR_ITEM_COUNT = 0x28,
	CONT_COND_EVENT_REPAIR_ITEM_ZENY = 0x29,
	CONT_COND_EVENT_BUY_MILEAGE_SHOP_COUNT = 0x2A,
	CONT_COND_EVENT_BUY_MILEAGE_SHOP_POINT_TOTAL = 0x2B,
	CONT_COND_EVENT_REGIST_RYUHA_POINT = 0x2C,
	CONT_COND_EVENT_NAMEKANSIGN = 0x2D,
	CONT_COND_EVENT_NAMEKANSIGN_AREA = 0x2E,
	CONT_COND_EVENT_REGIST_POTAL = 0x2F,
	CONT_COND_EVENT_REGIST_POTAL_AREA = 0x30,
	CONT_COND_EVENT_LANDMARK = 0x31,
	CONT_COND_EVENT_LANDMARK_AREA = 0x32,
	CONT_COND_EVENT_POPOSTONE = 0x33,
	CONT_COND_EVENT_POPOSTONE_AREA = 0x34,
	CONT_COND_EVENT_GAMBLE_SLOTMACHINE_COUNT = 0x35,
	CONT_COND_EVENT_GAMBLE_SLOTMACHINE_POINT_TOTAL = 0x36,
	CONT_COND_EVENT_IDENTIFY_ITEM = 0x37,
	CONT_COND_EVENT_RECEIVE_MAIL = 0x38,
	CONT_COND_EVENT_SEND_MAIL = 0x39,
	CONT_COND_EVENT_DWC_CLEAR = 0x3A,
	CONT_COND_EVENT_REGIST_DWC_CARD = 0x3B,
	CONT_COND_EVENT_REGIST_DWC_CARD_RANK = 0x3C,
	CONT_COND_EVENT_REGIST_TITLE = 0x3D,
	CONT_COND_EVENT_KILL_MOB_INDEX = 0x3E,
	CONT_COND_EVENT_REGIST_MODE_TENKAICHIBUDOKAI = 0x3F,
	CONT_COND_EVENT_VICTORY_JUNIOR_TEAM_TENKAICHIBUDOKAI = 0x40,
	CONT_COND_EVENT_VICTORY_ADULT_TEAM_TENKAICHIBUDOKAI = 0x41,
	CONT_COND_EVENT_REGIST_FLOOR_CCBD = 0x42,
	CONT_COND_EVENT_KILL_MOB_CONTENTS = 0x43,
	CONT_COND_EVENT_KILL_PC = 0x44,
	CONT_COND_EVENT_KILL_PC_CLASS = 0x45,
	CONT_COND_EVENT_DWC_CLEAR_IDX = 0x46,
	CONT_COND_EVENT_SUMMON_DB_TYPE = 0x47,
};


const int NTL_SCS_IMAGE_PACKET_PER_LENGTH = 3380;
const int NTL_SCS_IMAGE_REPLY_LENGTH = 5;
const BYTE NTL_SCS_IMAGE_COUNT = 15;
const WORD NTL_SCS_IMAGE_PACKET_TOTAL_LENGTH = 16595; //not sure
const int NTL_SCS_IMAGE_PACKET_COUNT = 16;
//const DWORD DBO_SCS_ICON_CHECK_TIME_IN_MILLISECS = 
//const DWORD DBO_SCS_CHECK_TIME_IN_MILLISECS = 
const DWORD DBO_SCS_CHECK_FAIL_TIME_IN_MILLISECS = 20000;
const int DBO_SCS_CHECK_MIN_COUNT = 10;
const DWORD DBO_SCS_CHECK_MAX_COUNT = 1000;


