#pragma once


enum eHLS_MERCHANT_DATA_TYPE
{
  HLS_MERCHANT_DATA_TYPE_HLS_ITEM_DATA = 0,
  HLS_MERCHANT_DATA_TYPE_HLS_WAGUWAGU_MACHINE_DATA,
  HLS_MERCHANT_DATA_TYPE_HLS_EVENT_MACHINE_DATA,

  HLS_MERCHANT_DATA_TYPE_COUNT,
  HLS_MERCHANT_DATA_TYPE_FIRST = HLS_MERCHANT_DATA_TYPE_HLS_ITEM_DATA,
  HLS_MERCHANT_DATA_TYPE_LAST = HLS_MERCHANT_DATA_TYPE_COUNT - 1,
};


