#include "StdAfx.h"
#include "NtlPacketMC.h"

const char * s_packetName_MC[] =
{
	DECLARE_PACKET_NAME( MC_HEARTBEAT ),
	DECLARE_PACKET_NAME( MC_AUTH_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MC_CHARACTER_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MC_GAME_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MC_GAME_SERVER_CHANNEL_INFO ),
	DECLARE_PACKET_NAME( MC_SERVERS_INFO ),
	DECLARE_PACKET_NAME( MC_SERVICE_INFO ),
	DECLARE_PACKET_NAME( MC_SERVERS_INFO_END ),
	DECLARE_PACKET_NAME( MC_NOTIFY_ILLEGAL_SERVER ),

	DECLARE_PACKET_NAME( MC_SERVER_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MC_AUTH_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MC_CHARACTER_SERVER_FARM_INFO_CHANGED_NFY ),

	DECLARE_PACKET_NAME( MC_GAME_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MC_GAME_SERVER_CHANNEL_INFO_CHANGED_NFY ),

	DECLARE_PACKET_NAME( MC_SERVER_USER_ALL_KICK_REQ ),
	DECLARE_PACKET_NAME( MC_SERVER_VERSION_CHANGED_NFY ), // by sooshia 07/23/2008
	DECLARE_PACKET_NAME( MC_SERVER_TURNOFF_FOR_DEVEL_NFY ),
	DECLARE_PACKET_NAME( MC_LOGIN_RES ),
	DECLARE_PACKET_NAME( MC_MOVE_RES ),
	DECLARE_PACKET_NAME( MC_CHARACTER_EXIT_RES ),
	DECLARE_PACKET_NAME( MC_KICKOUT_REQ ),

	DECLARE_PACKET_NAME( MC_PING_RES ),
	DECLARE_PACKET_NAME(MC_SERVERS_INFO_ADD),

};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_MC(WORD wOpCode)
{
	if( wOpCode < MC_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > MC_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - MC_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_MC) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_MC[ nIndex ];
}