//***********************************************************************************
//
//	File		:	NtlPacketNG.cpp
//
//	Begin		:	2006-05-12
//
//	Copyright	:	¨Ï NTL-Inc Co., Ltd
//
//	Author		:	Hyun Woo, Koo   ( zeroera@ntl-inc.com )
//
//	Desc		:	
//
//***********************************************************************************


#include "StdAfx.h"
#include "NtlPacketNG.h"


const char * s_packetName_NG[] =
{
	DECLARE_PACKET_NAME( NG_HEARTBEAT ),

	DECLARE_PACKET_NAME( NG_GAME_DATA_REQ ),
	DECLARE_PACKET_NAME( NG_ENTER_GAME_REQ ),
	DECLARE_PACKET_NAME( NG_LEAVE_GAME_REQ ),
	DECLARE_PACKET_NAME( NG_ENTER_WORLD_REQ ),
	DECLARE_PACKET_NAME( NG_LEAVE_WORLD_REQ ),
	DECLARE_PACKET_NAME( NG_SPS_SERVER_EVENT ),

	//DECLARE_PACKET_NAME( NG_CHAR_SPAWN_RES ),
	DECLARE_PACKET_NAME( NG_CHAR_READY ),
	DECLARE_PACKET_NAME( NG_CHAR_MOVE ),
	DECLARE_PACKET_NAME( NG_CHAR_DESTMOVE ),
	DECLARE_PACKET_NAME( NG_CHAR_FOLLOWMOVE ),
	DECLARE_PACKET_NAME( NG_CHAR_CHANGE_HEADING ),

	DECLARE_PACKET_NAME( NG_CHAR_TARGET_SELECT ),
	DECLARE_PACKET_NAME( NG_CHAR_TOGG_FIGHT ),
	DECLARE_PACKET_NAME( NG_CHAR_TOGG_RUN ),
	DECLARE_PACKET_NAME( NG_CHAR_TOGG_ATTACK ),
	DECLARE_PACKET_NAME( NG_CHAR_TOGG_SITDOWN ),

	DECLARE_PACKET_NAME( NG_CHAR_DIALOG ),
	DECLARE_PACKET_NAME( NG_CHAR_DIRECT_PLAY ),
	DECLARE_PACKET_NAME( NG_CHAR_DIRECT_TURNING ),
	DECLARE_PACKET_NAME( NG_CHAR_SET_CONDITION ),
	DECLARE_PACKET_NAME( NG_CHAR_BATTLE_MODE_NFY ),

	DECLARE_PACKET_NAME( NG_CHAR_START_ESCORT_RES),	
	DECLARE_PACKET_NAME( NG_CHAR_INITIALIZE ),// [12/13/2007 SGpro]
	DECLARE_PACKET_NAME( NG_CHAR_SETSPEEDPERCENT ),// [12/13/2007 SGpro]
	
	DECLARE_PACKET_NAME( NG_BOT_SKILL_REQ ),// [2/11/2008 SGpro]
	DECLARE_PACKET_NAME( NG_SKILL_TARGET_LIST ),
	DECLARE_PACKET_NAME( NG_BOT_BOTCAUTION_NFY ),//  [2/20/2008 SGpro]
	DECLARE_PACKET_NAME( NG_BOT_BOTCAUTION_HELPME_NFY ),// [5/27/2008 SGpro]

	DECLARE_PACKET_NAME( NG_CHAR_DESPAWN ),// [7/28/2008 SGpro]
	DECLARE_PACKET_NAME( NG_CHAR_TELEPORT_REQ ),// [7/28/2008 SGpro]
	DECLARE_PACKET_NAME( NG_CHAR_READY_TO_SPAWN ),// [8/4/2008 SGpro]
	
	DECLARE_PACKET_NAME( NG_CHAR_CHANGE_NICKNAME ),// [8/4/2008 SGpro]

	DECLARE_PACKET_NAME( NG_CHAR_MOB_ROLE_CHANGED_NFY ),// [11/10/2008 SGpro]

	DECLARE_PACKET_NAME( NG_CHAR_NONBATTLEACTIONPATTERNSET_UNITIDX_NFY ),

	DECLARE_PACKET_NAME( NG_SEND_SPS_EVENT ),
	DECLARE_PACKET_NAME( NG_SEND_AIS_EVENT ),

	DECLARE_PACKET_NAME( NG_CHANGE_SPS_SCENE_RES ),

	DECLARE_PACKET_NAME( NG_CHAR_LOC_AFTER_KNOCKDOWN_NFY ),
	DECLARE_PACKET_NAME( NG_CHAR_LOC_AFTER_SLIDING_NFY ),
	DECLARE_PACKET_NAME( NG_CHAR_LOC_AFTER_PUSH_NFY ),
};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_NG(WORD wOpCode)
{
	if( wOpCode < NG_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > NG_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - NG_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_NG) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_NG[ nIndex ];
}

