#include "StdAfx.h"
#include "NtlPacketGT.h"


const char * s_packetName_GT[] =
{
	DECLARE_PACKET_NAME( GT_GAME_INFO ),
	DECLARE_PACKET_NAME( GT_WORLD_CREATED_NFY ),
	DECLARE_PACKET_NAME( GT_WORLD_DESTROYED_NFY ),
	DECLARE_PACKET_NAME( GT_USER_ENTER_GAME ),
	DECLARE_PACKET_NAME( GT_USER_LEAVE_GAME ),
	DECLARE_PACKET_NAME( GT_USER_AUTH_KEY_CREATED_NFY ),

	DECLARE_PACKET_NAME( GT_UPDATE_PLAYER_POSITION ),
	DECLARE_PACKET_NAME( GT_UPDATE_PLAYER_CLASS ),
	DECLARE_PACKET_NAME( GT_UPDATE_PLAYER_LEVEL ),
	DECLARE_PACKET_NAME( GT_UPDATE_PLAYER_REPUTATION ),
	DECLARE_PACKET_NAME( GT_UPDATE_PUNISH ),

	DECLARE_PACKET_NAME( GT_PARTY_CREATED ),
	DECLARE_PACKET_NAME( GT_PARTY_DISBANDED ),
	DECLARE_PACKET_NAME( GT_PARTY_MEMBER_JOINED ),
	DECLARE_PACKET_NAME( GT_PARTY_MEMBER_LEFT ),
	DECLARE_PACKET_NAME( GT_PARTY_LEADER_CHANGED ),

	DECLARE_PACKET_NAME( GT_GUILD_CREATE ),
	DECLARE_PACKET_NAME( GT_GUILD_INVITE_REQ ),

	DECLARE_PACKET_NAME( GT_SYSTEM_DISPLAY_TEXT ),

	DECLARE_PACKET_NAME( GT_GUILD_FUNCTION_ADD_REQ ),
	DECLARE_PACKET_NAME( GT_GUILD_GIVE_ZENNY_REQ ),
	DECLARE_PACKET_NAME( GT_GUILD_BANK_START_REQ ),
	DECLARE_PACKET_NAME( GT_GUILD_BANK_END_NFY ),
	DECLARE_PACKET_NAME( GT_GUILD_CREATE_MARK_REQ ),							// GuildMark Create
	DECLARE_PACKET_NAME( GT_GUILD_CHANGE_MARK_REQ ),							// GuildMark Change
	DECLARE_PACKET_NAME( GT_GUILD_CHANGE_NAME_REQ ),

	DECLARE_PACKET_NAME( GT_BUDOKAI_NOTICE_NFY ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_CHANNEL_STATE_INFO_NFY ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_CHANNEL_UPDATE_STATE ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_CHANNEL_UPDATE_MATCH_STATE ),

	DECLARE_PACKET_NAME( GT_BUDOKAI_TOURNAMENT_INDIVIDUAL_LIST_RES ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_TOURNAMENT_INDIVIDUAL_INFO_RES ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_TOURNAMENT_TEAM_LIST_RES ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_TOURNAMENT_TEAM_INFO_RES ),

	DECLARE_PACKET_NAME( GT_BUDOKAI_MINOR_MATCH_INDIVIDUAL_LIST_NFY ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_MINOR_MATCH_TEAM_LIST_NFY ),

	DECLARE_PACKET_NAME( GT_BUDOKAI_MINOR_MATCH_TELEPORT_INFO_REQ ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_MINOR_MATCH_TELEPORT_INFO_RES ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_PROGRESS_MESSAGE_NFY ),

	DECLARE_PACKET_NAME( GT_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_REQ ),
	DECLARE_PACKET_NAME( GT_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_RES ),

	DECLARE_PACKET_NAME( GT_CHAR_MARKING_UPDATE ),

	DECLARE_PACKET_NAME( GT_CHAR_SERVER_TELEPORT),

	DECLARE_PACKET_NAME( GT_DOJO_CREATE_REQ),
	DECLARE_PACKET_NAME( GT_DOJO_DELETE_REQ),	
	DECLARE_PACKET_NAME( GT_DOJO_FUNCTION_ADD_REQ ),
	DECLARE_PACKET_NAME( GT_DOGI_CREATE_REQ ),
	DECLARE_PACKET_NAME( GT_DOGI_CHANGE_REQ ),

	DECLARE_PACKET_NAME( GT_CONNECT_VALID_CHECK_REQ ),

	DECLARE_PACKET_NAME( GT_DOJO_SCRAMBLE_REQ ),
	DECLARE_PACKET_NAME( GT_DOJO_SCRAMBLE_RESPONSE ),
	DECLARE_PACKET_NAME( GT_DOJO_SCRAMBLE_STATE_CHANGE ),
	DECLARE_PACKET_NAME( GT_DOJO_UPDATE_REQ ),

	DECLARE_PACKET_NAME( GT_CONNECT_CHANNEL_CHANGE_REQ ),
	DECLARE_PACKET_NAME( GT_DOJO_SCRAMBLE_RESET ),

	DECLARE_PACKET_NAME( GT_DOJO_SCRAMBLE_POINT_NFY ),
	DECLARE_PACKET_NAME( GT_DOJO_SCRAMBLE_SHIEFT_SEAL_STATE_NFY ),

	DECLARE_PACKET_NAME( GT_SEND_SERVER_RELAY_DATA ),

	DECLARE_PACKET_NAME( GT_DOJO_SCRAMBLE_REWARD_REQ ),
	DECLARE_PACKET_NAME( GT_DOJO_NPC_INFO_REQ ),
	DECLARE_PACKET_NAME( GT_DOJO_SEND_TELEPORT_PROPOSAL ),
	DECLARE_PACKET_NAME( GT_DOJO_COMMAND ),

	DECLARE_PACKET_NAME( GT_CHAR_READY_FOR_COMMUNITY_SERVER_NFY ),

	DECLARE_PACKET_NAME( GT_DOJO_USERCOUNT_CHANGE ),
	
};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_GT(WORD wOpCode)
{
	if( wOpCode < GT_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > GT_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - GT_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_GT) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_GT[ nIndex ];
}