#include "StdAfx.h"
#include "NtlPacketMA.h"

const char * s_packetName_MA[] =
{
	DECLARE_PACKET_NAME( MA_HEARTBEAT ),
	DECLARE_PACKET_NAME( MA_AUTH_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MA_CHARACTER_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MA_SERVERS_INFO ),
	DECLARE_PACKET_NAME( MA_SERVER_RELEASE_INFO ),
	DECLARE_PACKET_NAME( MA_SERVERS_INFO_END ),
	DECLARE_PACKET_NAME( MA_NOTIFY_ILLEGAL_SERVER ),

	DECLARE_PACKET_NAME( MA_SERVER_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MA_AUTH_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MA_CHARACTER_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MA_SERVER_VERSION_CHANGED_NFY ), // by sooshia 07/22/2008
	DECLARE_PACKET_NAME( MA_SERVER_TURNOFF_FOR_DEVEL_NFY ),
	DECLARE_PACKET_NAME( MA_LOGIN_RES ),
	DECLARE_PACKET_NAME( MA_MOVE_RES ),
	DECLARE_PACKET_NAME( MA_KICKOUT_REQ ),

	DECLARE_PACKET_NAME( MA_PING_RES ),
	
	DECLARE_PACKET_NAME( MA_ON_PLAYER_CHECK_RES ),
	DECLARE_PACKET_NAME(MA_SERVERS_INFO_ADD),
};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_MA(WORD wOpCode)
{
	if( wOpCode < MA_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > MA_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - MA_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_MA ) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_MA[ nIndex ];
}