#include "StdAfx.h"
#include "NtlPacketMG.h"


const char * s_packetName_MG[] =
{
	DECLARE_PACKET_NAME( MG_HEARTBEAT ),
	DECLARE_PACKET_NAME( MG_AUTH_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MG_CHARACTER_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MG_GAME_SERVER_FARM_INFO ),
	DECLARE_PACKET_NAME( MG_GAME_SERVER_CHANNEL_INFO ),
	DECLARE_PACKET_NAME( MG_SERVERS_INFO ),
	DECLARE_PACKET_NAME( MG_SERVICE_INFO ),
	DECLARE_PACKET_NAME( MG_WORLD_ASSIGNMENT_INFO_BEGIN ),
	DECLARE_PACKET_NAME( MG_WORLD_ASSIGNMENT_INFO ),
	DECLARE_PACKET_NAME( MG_WORLD_ASSIGNMENT_INFO_END ),
	DECLARE_PACKET_NAME( MG_SERVERS_INFO_END ),
	DECLARE_PACKET_NAME( MG_NOTIFY_ILLEGAL_SERVER ),

	DECLARE_PACKET_NAME( MG_SERVER_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MG_AUTH_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MG_CHARACTER_SERVER_FARM_INFO_CHANGED_NFY ),

	DECLARE_PACKET_NAME( MG_GAME_SERVER_FARM_INFO_CHANGED_NFY ),
	DECLARE_PACKET_NAME( MG_GAME_SERVER_CHANNEL_INFO_CHANGED_NFY ),

	DECLARE_PACKET_NAME( MG_SERVER_USER_ALL_KICK_REQ ),
	DECLARE_PACKET_NAME( MG_SERVER_VERSION_CHANGED_NFY ), // by sooshia 07/23/2008
	DECLARE_PACKET_NAME( MG_SERVER_TURNOFF_FOR_DEVEL_NFY ),
	DECLARE_PACKET_NAME( MG_SERVER_MAX_USER_NFY ),
	DECLARE_PACKET_NAME( MG_LOGIN_RES ),
	DECLARE_PACKET_NAME( MG_MOVE_RES ),
	DECLARE_PACKET_NAME( MG_KICKOUT_REQ ),

	DECLARE_PACKET_NAME( MG_PING_RES ),

	DECLARE_PACKET_NAME( MG_REPORT_MONSTER_STATISTICS_CONTINUE_REQ ),
	DECLARE_PACKET_NAME( MG_PLAYER_SWITCH_CHANNEL_RES ),
	DECLARE_PACKET_NAME( MG_PLAYER_EXIT_TO_CHAR_RES ),

	DECLARE_PACKET_NAME(MG_SERVERS_INFO_ADD),
};


//------------------------------------------------------------------
//
//------------------------------------------------------------------
const char * NtlGetPacketName_MG(WORD wOpCode)
{
	if( wOpCode < MG_OPCODE_BEGIN )
	{
		return "NOT DEFINED PACKET NAME : OPCODE LOW";
	}

	if( wOpCode > MG_OPCODE_END )
	{
		return "NOT DEFINED PACKET NAME : OPCODE HIGH";
	}

	int nIndex = wOpCode - MG_OPCODE_BEGIN;
	if( nIndex >= _countof( s_packetName_MG) )
	{
		return "OPCODE BUFFER OVERFLOW";
	}

	return s_packetName_MG[ nIndex ];
}