#include "StdAfx.h"
#include "NTLReport.h"


const sGM_REPORT_CONTENT g_aGM_REPORT_TYPE[GM_REPORT_TYPE_COUNT] = 
{
	{ GM_REPORT_CATEGORY_USERSEARCH,	GM_REPORT_TYPE_DELETE_CHARACTER },
	
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_CHARACTER_NAME,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_CHARACTER_LEVEL,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_CHARACTER_EXP,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_RANK_POINT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_MODOSA_POINT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_HONOR,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_REVIVAL_SPOT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_CHANGE_PRESENT_SPOT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_ADD_SKILL,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_ADD_HTB_SKILL,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_DELETE_SKILL,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_DELETE_SKILL_HTB,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_CHARACTERINFO,	GM_REPORT_TYPE_DELETE_BUF,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_MAIL,			GM_REPORT_TYPE_DELETE_MAIL,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_MAIL,			GM_REPORT_TYPE_DELETE_MAIL_ITEM,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_MAIL,			GM_REPORT_TYPE_DELETE_MAIL_JENNY,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_ITEM,			GM_REPORT_TYPE_CHANGE_JENNY,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_ITEM,			GM_REPORT_TYPE_CREATE_ITEM,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_ITEM,			GM_REPORT_TYPE_DELETE_ITEM,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_ITEM,			GM_REPORT_TYPE_DELETE_WAREHOUSE,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_QUEST,			GM_REPORT_TYPE_DELETE_QUEST,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_QUEST,			GM_REPORT_TYPE_CREATE_QUEST_ITEM,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_QUEST,			GM_REPORT_TYPE_DELETE_QUEST_ITEM,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_QUEST,			GM_REPORT_TYPE_CHANGE_QUEST_ITEM_COUNT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_PUNISHMENT,	GM_REPORT_TYPE_COUNT_PUNISHMENT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_PUNISHMENT,	GM_REPORT_TYPE_CANCEL_PUNISHMENT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_CHANGE_GUILD_NAME,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_CHANGE_GUILD_POINT,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_CANCEL_GUILD_DELIVERY,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_INITIALIZE_GUILD_NOTIFY,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_INITIALIZE_GUILD_EMBLEM,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_CHANGE_GUILD_ABILITY,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_DELETE_GUILD_WAREHOUSE_ITEM,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_GUILD,			GM_REPORT_TYPE_CHANGE_GUILD_WAREHOUSE_JENNY,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_PETITION,		GM_REPORT_TYPE_COUNT_PETTION_PROCESS,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_PETITION,		GM_REPORT_TYPE_COUNT_PETTION_PROCESS_STILL,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_SERVERSTAUTS,	GM_REPORT_TYPE_SERVERSTATUS,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_MULTIMAIL,		GM_REPORT_TYPE_CREATE_MULTIMAIL_ITEM_INDIVIDUAL,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_MULTIMAIL,		GM_REPORT_TYPE_CREATE_MULTIMAIL_ITEM_MULTI,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },

	{ GM_REPORT_CATEGORY_DATASETTING,	GM_REPORT_TYPE_CHANGE_GAME_EXP,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 },
	{ GM_REPORT_CATEGORY_DATASETTING,	GM_REPORT_TYPE_CHANGE_GAME_DROP,INVALID_SERVERFARMID, "", "", "", "", "", "", 0, 0, 0 }
};

BYTE GetCategory(eGM_REPORT_TYPE eGMReportType)
{
	return (BYTE)g_aGM_REPORT_TYPE[eGMReportType].category;
}