//***********************************************************************************
//
//	File		:	NtlService.h
//
//	Begin		:	2008-05-18
//
//	Copyright	:	¨Ï NTL-Inc Co., Ltd
//
//	Author		:	
//
//	Desc		:	
//
//***********************************************************************************

#pragma once

#include "NtlSharedDef.h"

#define SERVER_SETTING_FILE "serverOption"

enum eDBO_ALLOWED_FUNC_FOR_DEV
{
	DBO_ALLOWED_FUNC_FOR_DEV_HUMAN =0,
	DBO_ALLOWED_FUNC_FOR_DEV_NAMEK,
	DBO_ALLOWED_FUNC_FOR_DEV_MAJIN,

	DBO_ALLOWED_FUNC_FOR_DEV_COUNT,

	DBO_ALLOWED_FUNC_FOR_DEV_FIRST = DBO_ALLOWED_FUNC_FOR_DEV_MAJIN,
	DBO_ALLOWED_FUNC_FOR_DEV_LAST = DBO_ALLOWED_FUNC_FOR_DEV_COUNT - 1
};

enum eDBO_ALLOWED_FUNC_FOR_DEV_FLAG
{
	DBO_ALLOWED_FUNC_FOR_DEV_FLAG_HUMAN = 1 << DBO_ALLOWED_FUNC_FOR_DEV_HUMAN,
	DBO_ALLOWED_FUNC_FOR_DEV_FLAG_NAMEK = 1 << DBO_ALLOWED_FUNC_FOR_DEV_NAMEK,
	DBO_ALLOWED_FUNC_FOR_DEV_FLAG_MAJIN = 1 << DBO_ALLOWED_FUNC_FOR_DEV_MAJIN,
};


enum eDBO_ALLOWED_SERVICE_SERVICE_FUNC
{
	DBO_ALLOWED_SERVICE_FUNC_GMT = 0x0,
	DBO_ALLOWED_SERVICE_FUNC_HLS_ICON = 0x1,
	DBO_ALLOWED_SERVICE_FUNC_HLS_SHOP = 0x2,
	DBO_ALLOWED_SERVICE_FUNC_YARDRAT_STORE = 0x3,
	DBO_ALLOWED_SERVICE_FUNC_BENEFIT_ICON = 0x4,
	DBO_ALLOWED_SERVICE_FUNC_NETMARBLE_MEMBERSHIP_LOGO = 0x5,
	DBO_ALLOWED_SERVICE_FUNC_HOIPOI_CORE_SLOT = 0x6,
	DBO_ALLOWED_SERVICE_FUNC_YARDRAT_KEY = 0x7,
	DBO_ALLOWED_SERVICE_FUNC_CRESCENT_POPO = 0x8,
	DBO_ALLOWED_SERVICE_FUNC_SKILL_POINT_RESET = 0x9,
	DBO_ALLOWED_SERVICE_FUNC_PARTY_POPO = 0xA,
	DBO_ALLOWED_SERVICE_FUNC_QUICK_TELEPORT = 0xB,
	DBO_ALLOWED_SERVICE_FUNC_SUPERRIOR_WARRIOR = 0xC,
	DBO_ALLOWED_SERVICE_FUNC_NET_STORE = 0xD,
	DBO_ALLOWED_SERVICE_FUNC_GUILD_NAME_CHANGE = 0xE,
	DBO_ALLOWED_SERVICE_FUNC_CHARACTER_NAME_CHANGE = 0xF,
	DBO_ALLOWED_SERVICE_FUNC_NETPYSHOP = 0x10,
	DBO_ALLOWED_SERVICE_FUNC_SCSCHECK = 0x11,
	DBO_ALLOWED_SERVICE_FUNC_COUNT = 0x12,
};

struct sDBO_SERVER_SETTING
{
	bool bAllowHuman;
	bool bAllowNamek;
	bool bAllowMajin;
	int nMaxLevel;
	int nMaxLoadSlot;
	int nBasicSlot;
	int nPremiumSlot;
	bool bCommercialSetting[18];
	unsigned int dwDelDurMin;
};

bool ReadServerSetting( sDBO_SERVER_SETTING &sInfo );

bool Dbo_IsValidText(WCHAR* pwszText);

bool Dbo_IsNameTooShort(WCHAR* pwszName);

bool Dbo_IsNameTooLong(WCHAR* pwszName);


DBOTIME	DBO_TIMEToDBOTIME(sDBO_TIME& time);
void	DBOTIMEToDBO_TIME(sDBO_TIME* result, const DBOTIME time);
