// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "togglebutton2.h"

/////////////////////////////////////////////////////////////////////////////
// CTogglebutton2

IMPLEMENT_DYNCREATE(CTogglebutton2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTogglebutton2 properties

/////////////////////////////////////////////////////////////////////////////
// CTogglebutton2 operations
