//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Venus.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDW_PROP_BAR                    103
#define IDD_ROLLUPPAGEID                105
#define IDC_TREELISTEDITCONTROL         107
#define IDI_TABCTRLBAR                  109
#define IDR_MAINFRAME                   128
#define IDI_MAINFRAME                   129
#define IDS_TRUE                        129
#define IDB_BITMAP1                     130
#define IDB_TABIMAGE                    130
#define IDS_FALSE                       130
#define IDD_EFFECT_LIST                 131
#define IDS_NOITEMSEL                   131
#define IDD_EFFECT_PROPERTY_VIEW        132
#define IDD_EFFECT_PROPERTY             132
#define IDS_SELFORINFO                  132
#define IDC_SPLITER                     133
#define IDC_FPOINT                      134
#define IDB_EXPANDDOWN_BITMAP           135
#define IDB_EXPANDDOWN_BLUE_BITMAP      136
#define IDB_EXPANDLEFT_BITMAP           137
#define IDB_EXPANDLEFT_BLUE_BITMAP      138
#define IDD_TEXTURE_LIST                139
#define IDD_TEXTURE_INFO                140
#define IDR_POPUP                       141
#define IDD_STRING                      142
#define IDD_STATUSBAR                   143
#define IDD_INSTANCE_EFFECT             144
#define IDI_CIRCLE_EMITTER              145
#define IDI_POINT_EMITTER               146
#define IDI_SPHERE_EMITTER              149
#define IDI_RESOURCE_EFFECT             150
#define IDI_RESOURCE_PARTICLE           151
#define IDI_EMITTER_SIZE                152
#define IDI_EMITTER_COLOR               153
#define IDB_EFFECT_LIST_IMAGE           155
#define IDD_OPTION                      156
#define IDD_MESH_LIST                   157
#define IDD_ANIMATION_LIST              158
#define IDD_UVANI_LIST                  159
#define IDD_ACTION_LIST                 160
#define IDD_EDIT                        161
#define IDI_CATEGORY                    162
#define IDI_ANIMATION                   163
#define IDD_SPLINE_PATH_LIST            164
#define IDD_CREATE_SPLINE_PATH          165
#define IDR_VenusTYPE                   167
#define IDD_UPDATE_NEWS                 168
#define IDD_LIGHT                       169
#define IDB_TOOLBAR_DRAW                170
#define IDB_TOOLBAR_DRAW_HOT            171
#define IDR_TOOLBAR_DRAW                172
#define IDD_DIALOG1                     174
#define IDD_POST_EFFFECT                174
#define IDD_EVENT_LIST                  175
#define IDD_AVATAR_PROPERTY             176
#define IDD_SPLINE_PATH_PROPERTY        177
#define IDD_ENEMY_PROPERTY              178
#define IDD_PROGRESS                    179
#define IDI_ICON2                       182
#define IDC_PROPERTY_STATIC             1000
#define IDC_EFFECT_LIST                 1001
#define IDC_TEXTURE_LIST                1002
#define IDC_TEXTURE_WIDTH               1004
#define IDC_TEXTURE_HEIGHT              1005
#define IDC_TEXTURE                     1006
#define IDC_BALL_LIFETIME               1006
#define IDC_STRING                      1008
#define IDC_TRACE_LIST                  1009
#define IDC_RESOURCE_EFFECT_LIST        1011
#define IDC_FPS                         1012
#define IDC_GRID_WIDTH                  1013
#define IDC_GRID_COUNT                  1014
#define IDC_EDIT_GRID_WIDTH             1015
#define IDC_EDIT_GRID_COUNT             1016
#define IDC_MESH_LIST                   1017
#define IDC_OBJECT_MOVE_SPEED           1017
#define IDC_ANIMATION_LIST              1018
#define IDC_OBJECT_ROTATE_SPEED         1018
#define IDC_EDIT_OBJECT_MOVE_SPEED      1019
#define IDC_ACTION_LIST                 1020
#define IDC_EDIT_OBJECT_ROTATE_SPEED    1020
#define IDC_EDIT1                       1021
#define IDC_OBJECT_SCALE_SPEED          1021
#define IDC_ABSOLUTE_X                  1021
#define IDC_UPDATE_NEW                  1021
#define IDC_EDIT2                       1022
#define IDC_EDIT_OBJECT_SCALE_SPEED     1022
#define IDC_ABSOLUTE_Y                  1022
#define IDC_EDIT3                       1023
#define IDC_CAMERA_MOVE_SPEED           1023
#define IDC_ABSOLUTE_Z                  1023
#define IDC_LIGHT_COLOR_R               1023
#define IDC_CAMERA_ROTATE_SPEED         1024
#define IDC_LIGHT_COLOR_G               1024
#define IDC_EDIT7                       1024
#define IDC_EDIT_CAMERA_MOVE_SPEED      1025
#define IDC_LIGHT_EDIT_COLOR_R          1025
#define IDC_UVANIMATION_LIST            1026
#define IDC_EDIT_CAMERA_ROTATE_SPEED    1026
#define IDC_LIGHT_EDIT_COLOR_G          1026
#define IDC_EDIT4                       1027
#define IDC_SPLINE_PATH_LIST            1027
#define IDC_CAMERA_WHEEL_SPEED          1027
#define IDC_OFFSET_X                    1027
#define IDC_LIGHT_COLOR_B               1027
#define IDC_EDIT5                       1028
#define IDC_BACKGROUND                  1028
#define IDC_OFFSET_Y                    1028
#define IDC_EDIT6                       1029
#define IDC_EDIT_CAMERA_WHEEL_SPEED     1029
#define IDC_OFFSET_Z                    1029
#define IDC_LIGHT_EDIT_COLOR_B          1029
#define IDC_LIGHT_COLOR                 1030
#define IDC_LIGHT_RADIUS                1031
#define IDC_LIGHT_EDIT_RADIUS           1032
#define IDC_LIGHT_ANGLE                 1033
#define IDC_LIGHT_EDIT_ANGLE            1034
#define IDC_FORWARD_y                   1040
#define IDC_TIME_SPEED                  1046
#define IDC_LIGHT_COLOR_ALL             1046
#define IDC_EDIT_TIME_SPEED             1047
#define IDC_LIGHT_EDIT_COLOR_ALL        1047
#define IDC_TIME_PAUSE                  1049
#define IDC_POLYGON_COUNT               1050
#define IDC_EFFECT_COUNT                1051
#define IDC_SHOW_GRID                   1052
#define IDC_SHOW_TERRAIN                1053
#define IDC_SHOW_SKY                    1054
#define IDC_SHOW_OBJECT                 1054
#define IDC_TIME_REPEAT                 1055
#define IDC_LIGHT_TYPE                  1056
#define IDC_ABMIENT_COLOR               1057
#define IDC_ABMIENT_COLOR_R             1058
#define IDC_ABMIENT_COLOR_G             1059
#define IDC_ABMIENT_COLOR_B             1060
#define IDC_ABMIENT_EDIT_COLOR_R        1061
#define IDC_ABMIENT_EDIT_COLOR_G        1062
#define IDC_ABMIENT_EDIT_COLOR_B        1063
#define IDC_ABMIENT_COLOR_ALL           1064
#define IDC_LIST1                       1064
#define IDC_ABMIENT_EDIT_COLOR_ALL      1065
#define IDC_COMBO1                      1065
#define IDC_COMBO5                      1066
#define IDC_COMBO2                      1067
#define IDC_EVENT_LIST                  1067
#define IDC_COMBO3                      1068
#define IDC_COMBO4                      1069
#define IDC_COMBO6                      1070
#define IDC_ANIMATION_TIME              1070
#define IDC_COMBO7                      1071
#define IDC_CURRENT_TIME                1071
#define IDC_COMBO8                      1072
#define IDC_LAST_TIME                   1072
#define IDC_BALL_SPEED                  1076
#define IDC_PROGRESS                    1077
#define IDC_PERSENT                     1078
#define IDC_PERCENT                     1078
#define IDC_FILTER_ENABLE               1080
#define IDC_FILTER_SLIDER_POWER_HEIGHT  1081
#define IDC_FILTER_EDIT_SPACE_HEIGHT    1082
#define IDC_FILTER_SLIDER_SPACE_HEIGHT  1083
#define IDC_FILTER_EDIT_POWER_HEIGHT    1084
#define POPUP_CREATE_EFFECT             32774
#define POPUP_DELETE_EFFECT             32776
#define POPUP_DELETE_SYSTEM             32780
#define POPUP_TEST_EFFECT               32782
#define ID_VIEW_EFFECT_LIST             32784
#define POPUP_INSERT_POINT_EMITTER      32791
#define POPUP_INSERT_CIRCLE_EMITTER     32792
#define POPUP_INSERT_SPHERE_EMITTER     32793
#define POPUP_INSERT_EMITTER_COLOR      32795
#define POPUP_INSERT_EMITTER_SIZE       32796
#define POPUP_DELETE_ACTION             32798
#define POPUP_INSERT_EMITTER_MULTI_COLOR 32801
#define POPUP_INSERT_EMITTER_MULTI_SIZE 32802
#define POPUP_CREATE_RESOURCE_SYSTEM    32804
#define POPUP_CREATE_ATTACH_SYSTEM      32805
#define POPUP_INSERT_ATTACH_SYSTEM      32807
#define POPUP_INSERT_TEXTURE            32809
#define POPUP_DELETE_TEXTURE            32811
#define POPUP_INSERT_EMITTER_MULTI_TEXCOORDS 32813
#define POPUP_INSERT_EMITTER_TEXCOORDS  32817
#define POPUP_INSERT_EMITTER_2DROTATE   32818
#define POPUP_INSERT_EMITTER_MATRIX     32819
#define ID_VIEW_OPTION                  32820
#define ID_EFFECT_CRREATERESOURCESYSTEM 32821
#define POPUP_CREATE_PARTICLE_SYSTEM    32823
#define POPUP_CREATE_MESH_SYSTEM        32825
#define POPUP_INSERT_MESH               32827
#define POPUP_DELETE_MESH               32829
#define ID_EDIT_EDITMODE                32830
#define ID_EDIT_MODE_MOVE               32832
#define ID_EDIT_MODE_ROTATE             32835
#define ID_EDIT_MODE_SCALE              32836
#define ID_VIEW_EDIT_DIALOG             32838
#define POPUP_CREATE_PATH               32840
#define POPUP_DELETE_PATH               32842
#define POPUP_INSERT_EMITTER_SPLINE_PATH 32844
#define ID_FILE_EFFECT_NEW              32845
#define ID_FILE_EFFECT_OPEN             32846
#define ID_FILE_EFFECT_SAVE             32847
#define ID_FILE_EFFECT_SAVE_AS          32848
#define POPUP_CREATE_BEAM_SYSTEM        32849
#define POPUP_INSERT_EMITTER_MULTI_TEXTURES 32850
#define POPUP_CREATE_HURRICANE_SYSTEM   32852
#define POPUP_INIT_CAMERA               32853
#define ID_VIEW_UPDATE_NEWS             32855
#define POPUP_CREATE_LIGHTNING_SYSTEM   32857
#define ID_VIEW_LIGHT                   32859
#define POPUP_INSERT_EMITTER_HURRICANE  32861
#define POPUP_EFFECT_SORT               32863
#define POPUP_INSERT_EMITTER_FADE_OUT   32865
#define ID_RENDER_FILLMODE              32866
#define POPUP_FILLMODE_POINT            32870
#define POPUP_FILLMODE_WIREFRAME        32871
#define POPUP_FILLMODE_SOLID            32872
#define POPUP_CREATE_EVENT              32874
#define POPUP_DELETE_EVENT              32876
#define POPUP_SAVE_EVENT                32879
#define POPUP_LOAD_EVENT                32880
#define POPUP_CLEAR_EVENT               32882
#define ID_EFFECT_INSERTEMITTERMULTIROTATE 32883
#define POPUP_INSERT_EMITTER_MULTI_ROTATE 32884
#define ID_FILE_MERGE                   32885
#define ID_FILE_EFFECT_MERGE            32886
#define ID_CREATERESOURCESYSTEM_DECAL   32887
#define POPUP_CREATE_DECAL_SYSTEM       32888
#define ID_EFFECT_INSERTEMITTERORBITPOINT 32889
#define POPUP_INSERT_EMITTER_ORBIT_POINT 32890
#define POPUP_INSERT_EMITTER_ORBITPOINT 32891
#define ID_VIEW_POSTEFFECTDIALOG        32892
#define ID_VIEW_POST_EFFECT             32893
#define ID_CREATERESOURCESYSTEM_POSTEFFECT 32894
#define POPUP_CREATE_POST_EFFECT_SYSTEM 32895
#define ID_VIEW_BLURFILTER              32897
#define ID_CREATERESOURCESYSTEM_TRACEEFFECT 32898
#define POPUP_CREATE_TRACE_EFFECT_SYSTEM 32899
#define ID_CREATERESOURCESYSTEM_LINESYSTEM 32900
#define POPUP_                          32901
#define POPUP_CREATE_LINE_SYSTEM        32902
#define ID_VIEW_FRAMEFIX                32903
#define ID_EFFECT_INSERTEMITTERFINISH   32904
#define POPUP_INSERT_EMITTER_FINISH     32905
#define ID_EFFECT_INSERTEMITTERTRACE    32906
#define POPUP_INSERT_EMITTER_TRAIL      32907
#define ID_EFFECT_INSERTEMITTERUVANIMATION 32908
#define POPUP_EFFECT_INSERTEMITTERUVANIMATION 32909
#define POPUP_EFFECT_INSERT_UVANIM      32910
#define POPUP_INSERT_EMITTER_UVANIM     32911
#define ID_VIEW_CAMERA                  32912
#define ID_CAMERA_FRONTCAMERA           32913
#define ID_CAMERA_LEFTCAMERA            32914
#define ID_CAMERA_RIGHTCAMERA           32915
#define ID_CAMERAVIEWPOSITION_BACKCAMERA 32916
#define ID_CAMERAVIEWPOSITION_UPCAMERA  32917
#define ID_CAMERAVIEWPOSITION_DOWNDCAMERA 32918
#define ID_CAMERAVIEWPOSITION_DOWNCAMERA 32919
#define ID_EFFECT_CREATEFOLDER          32920
#define ID_EFFECT_DELETEFOLDER          32921
#define POPUP_CREATE_FOLDER             32922
#define POPUP_DELETE_FOLDER             32923
#define ID_EFFECT_RENAMEFOLDER          32924
#define POPUP_RENAME_FOLDER             32925
#define ID_VIEW_VIEWBOUNDINGSPHERE      32926
#define ID_TOOL_GENARATEBOUNDINGSPHEREALL 32927
#define ID_VIEW_LOWSPECEFFECT           32928

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32929
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
