//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MrPoPo.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_PANE_LOGVIEW                101
#define IDR_PANE_SETITEM                102
#define IDD_MPPCONFIGSETTING            103
#define IDR_PANE_TEST                   103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_MPPSETITEMPANE              105
#define IDR_PANE_CHEAT                  105
#define IDD_MPPTESTPANE                 106
#define IDR_PANE_GRAPHIC                106
#define IDD_MPPCLIENTCHEAT              107
#define IDD_MPPGRAPHICPANE              108
#define IDR_MAINFRAME                   128
#define IDR_MrPoPoTYPE                  129
#define IDB_BITMAP_ICONS                130
#define IDD_DIALOG1                     130
#define IDC_BTN_SAVEXML                 1000
#define IDC_BTN_SAVEENC                 1001
#define IDC_EDIT_CREATEITEM             1003
#define IDC_BTN_CREATEITEM              1004
#define IDC_BTN_UPGRADEITEM             1005
#define IDC_ED_LUA                      1005
#define IDC_EDIT_SETZENNY               1006
#define IDC_ED_OUT                      1006
#define IDC_BTN_SETZENNY                1007
#define IDC_BTN_LUA_COMPILE             1007
#define IDC_ST_LUA                      1008
#define IDC_ST_LUA_DIR                  1009
#define IDC_ST_OUT_DIR                  1010
#define IDC_EDIT_ADDEXP                 1011
#define IDC_EDIT_SETLEVEL               1012
#define IDC_BTN_ADDEXP                  1013
#define IDC_BTN_COLLECTDRAGONBALL       1014
#define IDC_BTN_SETLEVEL                1015
#define IDC_CB_CROWD                    1015
#define IDC_BTN_SETSPEED                1016
#define IDC_BTN_CROWD_CHANGE            1016
#define IDC_BTN_OFFENCE                 1017
#define IDC_BTN_DEFENCE                 1018
#define IDC_EDIT_SETSPEED               1019
#define IDC_EDIT_OFFENCE                1020
#define IDC_EDIT_DEFENCE                1021
#define IDC_BUTTON1                     1022
#define IDC_ED_TELE_X                   1023
#define IDC_ED_TELE_Z                   1024
#define IDC_CB_TELE_SELECT              1025
#define IDC_ED_TELE_VISIT               1026
#define IDC_RD_SELECT                   1027
#define IDC_RD_DIRECT                   1028
#define IDC_ED_OBSERVER_INDEX           1028
#define IDC_RD_VISIT                    1029
#define IDC_BT_OBSERVER_INDEX           1029
#define IDC_BT_TEST1                    1030
#define IDC_ED_ELAPSED                  1030
#define IDC_BTN_LEARN_ALL_SKILL         1030
#define IDC_ED_TEST1                    1031
#define IDC_BT_DUMP_CONSOLE             1031
#define IDC_BTN_UPGRADE_ALL_SKILL       1031
#define IDC_BT_TEST2                    1032
#define IDC_BT_DUMP_FILE                1032
#define IDC_BTN_CREATE_LEVEL_ITEMS      1032
#define IDC_ED_TEST2                    1033
#define IDC_BT_DUMP_GUI                 1033
#define IDC_BTN_SUPER_MODE              1033
#define IDC_BT_TEST3                    1034
#define IDC_DUMP_TARGET                 1034
#define IDC_ED_TEST3                    1035
#define IDC_CB_DUMP                     1035
#define IDC_BT_ELAPSED                  1036
#define IDC_BT_OBSERVER_LUA             1036
#define IDC_DUMP_REG                    1037
#define IDC_BT_FREECAMERA               1037
#define IDC_DUMP_UNREG                  1038
#define IDC_ED_OBSERVER_LUA             1038
#define IDC_BT_LOWSPEC_CHAR             1039
#define IDC_BT_RENDER_SCOUTER           1039
#define IDC_BT_LOWSPEC_EFFECT           1040
#define IDC_TENKAICHI                   1040
#define IDC_BT_LOWSPEC_MESH             1041
#define IDC_COLORCHANGE                 1041
#define IDC_TERRAIN_DIST                1041
#define IDC_BT_LOWSPEC_DECAL            1042
#define IDC_STATECHANGE                 1042
#define IDC_TERRAIN_SHADOW              1042
#define IDC_TRANSFORM                   1043
#define IDC_WATER_SPECULAR              1043
#define IDC_STUNTYPE                    1044
#define IDC_EFFECT                      1044
#define IDC_EFFECT_PARTICLE_RATIO       1044
#define IDC_BT_TARGET_MARKING           1045
#define IDC_CHAR_EDGE                   1045
#define IDC_BT_RENDER_SCOUTER2          1046
#define IDC_BT_PUSHING                  1046
#define IDC_CHAR_GRAY_COLOR             1046
#define IDC_EFFECT_LOWSPEC              1047
#define IDC_EFFECT_MESH                 1048
#define IDC_EFFECT_DECAL                1049
#define IDC_EDIT_TERRAIN_DIST           1050
#define IDC_EDIT_PARTICLE_RATIO         1051
#define IDC_OBJECT_DIST                 1052
#define IDC_GRASS_DIST                  1053
#define IDC_CHAR_DIST                   1054
#define IDC_CHAR_SHADOW                 1055
#define IDC_CHAR_FOOT                   1056
#define IDC_CHAR_UPGRADE_EFFECT         1057
#define IDC_EFFECT_WEATHER              1058
#define IDC_EFFECT_BLOOM                1059
#define IDC_SLIDER1                     1059
#define IDC_SLIDER2                     1060
#define IDC_SLIDER3                     1061
#define IDC_SLIDER4                     1062
#define IDC_SLIDER5                     1063
#define IDC_SLIDER8                     1066
#define IDC_SLIDER9                     1067
#define IDC_COMBO1                      1068
#define IDC_COMBO2                      1069
#define IDC_SLIDER10                    1070
#define IDC_CHECK1                      1071
#define IDC_CHECK2                      1072
#define IDC_SLIDER11                    1073
#define IDC_SLIDER12                    1075
#define IDC_SLIDER13                    1076
#define IDC_CHECK3                      1079
#define IDC_CHECK4                      1080
#define IDR_PANE_OPTIONS                4000
#define IDR_PANE_PROPERTIES             4001
#define IDR_PANE_CONFIG                 4002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
