//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DTEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STRING_EFFECT               101
#define IDS_STRING_SOUND                102
#define IDD_CONTROL_POINT               103
#define IDS_STRING_REFREE               104
#define IDD_CONTROLPANE                 105
#define IDD_POINTSHAPE                  106
#define IDR_MAINFRAME                   128
#define IDR_DTEditorTYPE                129
#define IDB_BITMAP_ICONS                130
#define IDD_DIALOG1                     130
#define IDD_CONTROL_PANE                131
#define IDB_TOOLBAR_ALPHA               134
#define IDB_BITMAP2                     135
#define IDB_TABITEM                     135
#define IDR_TOOLBAR1                    136
#define IDB_BITMAP1                     137
#define IDB_OBJECTPANE_TOOLBARS_ICONS   138
#define IDR_TOOLBAR2                    146
#define IDR_TOOLBAR3                    152
#define IDR_OBJ_PANE_TOOLBAR            152
#define IDR_TOOLBAR4                    156
#define IDD_ADD_PROP                    162
#define IDR_SCRIPT_PANE_TOOLBAR         163
#define IDR_CONTROL_PANE_TOOLBAR        166
#define IDB_RULER_DO                    168
#define IDB_RULER_DOM                   169
#define IDD_SEQUENCE_GRAPH              170
#define IDR_PROPERTY_TRANS_TOOLBAR      171
#define IDB_PROPERTY_TRANS_IMAGE        173
#define IDR_POPUP                       174
#define IDD_RENAME_PROP                 175
#define IDR_EDIT_MODE_TOOLBAR           177
#define IDD_VIEWER_CONTROL              179
#define IDR_SKILL_PANE_TOOLBAR          180
#define ID_BOT_PANE_CREATE              182
#define IDR_BOT_PANE_CREATE             182
#define IDR_BOT_PANE_TOOLBAR            182
#define IDD_POINTEDIT                   184
#define IDR_POINTEDIT_TOOLBAR           185
#define IDD_POINTROTATEEDIT             187
#define IDD_POINTATTRIBUTE              188
#define IDD_POINTCUSTOMEDIT             189
#define IDR_DIRECTIONBAR                190
#define IDD_DIRECTION_ADD_NODE_DIALOG   192
#define IDD_DIRECTION_PROP_REFREE       193
#define IDD_DIALOG2                     194
#define IDD_SOUND_OPTION                195
#define IDC_LIST1                       1000
#define IDC_ADD_PROP_LIST               1000
#define IDC_BUTTON1                     1001
#define IDC_POINTEDIT_CENTER_MOVE       1001
#define IDC_SEQUENCE_GRAPH_CENTER       1001
#define IDC_POINTROTATEEDIT_RESET_CAMERA 1001
#define IDC_POINTATTR_RESET_AVATAR_DIR  1001
#define IDC_BORDER_TAB                  1002
#define IDC_SEQUENCE_GRAPH_LAYOUT       1006
#define IDC_CONTROL_POINT_TIME_INFO     1007
#define IDC_COMBO1                      1008
#define IDC_COMBO_WORLD_NAME            1008
#define IIDC_POINTATTR_COMBO_TYPE       1008
#define IDC_SEQUENCE_GRAPH_VSCROLL      1009
#define IDC_SEQUENCE_GRAPH_HSCROLL      1010
#define IDC_EDIT_RENAME                 1011
#define IDC_EDIT_TELEPORT_X             1012
#define IDC_EDIT_TELEPORT_Z             1013
#define IDC_EDIT_AVATAR_SPEED           1014
#define IDC_EDIT_WORLD_NAME             1015
#define IDC_EDIT_WORLD_MIN_Z            1016
#define IDC_EDIT_WORLD_MIN_X            1017
#define IDC_EDIT_WORLD_MAX_X            1018
#define IDC_EDIT_WORLD_MAX_Z            1019
#define IDC_COMBO_AVATAR_RACE           1020
#define IDC_COMBO_AVATAR_CLASS          1021
#define IDC_COMBO_AVATAR_GENDER         1022
#define IDC_POINTEDIT_RIGHT             1023
#define IDC_POINTEDIT_SCALE_INFO        1026
#define IDC_STATIC_SCALE_INFO           1029
#define IDC_STATIC_WORLD_CENTER         1030
#define IDC_ROTATE_VIEW                 1031
#define IDC_POINTROTATEEDIT_GRID_NUM    1032
#define IDC_POINTROTATEEDIT_DIR_X       1033
#define IDC_POINTROTATEEDIT_DIR_Y       1034
#define IDC_POINTROTATEEDIT_DIR_Z       1035
#define IDC_POINTROTATEEDIT_SNAP        1036
#define IDC_POINTROTATEEDIT_BACK        1037
#define IDC_POINTATTR_POINT_POS         1039
#define IDC_POINTATTR_POINT_OFFSETY     1040
#define IDC_POINTATTR_ADD_POINT_POS     1041
#define IDC_POINTROTATEEDIT_POINT_DIRECTION 1042
#define IDC_POINTROTATEEDIT_INTERPOLATION 1043
#define IDC_POINTATTR_POINT_SELECTED_INTERPOLATION 1044
#define IDC_POINTATTR_CAMERA_SPEED      1045
#define IDC_POINTEDIT_SEARCH_MOVE       1046
#define IDC_POINTATTR_POINT_BOX         1047
#define IDC_POINTATTR_CHECK_POS         1048
#define IDC_POINTATTR_CHECK_DIR         1049
#define IDC_POINTATTR_CHECK_CAMERA_MOVE 1050
#define IDC_CHECK1                      1052
#define IDC_POINTATTR_CHECK_AVATAR_COLLISION 1052
#define IDC_CUSVE_SOUND_LOOP            1052
#define IDC_CHECK_WEATHER_EFFECT        1052
#define IDC_CHECK_BGM                   1053
#define IDC_CHECK_WEATHER_MUSIC         1054
#define IDC_POINT_CUSTOM_DIALOG         1055
#define IDC_CUSTOM_CURVE_POINT          1056
#define IDC_CUSVE_SOUND_FILENAME        1057
#define IDC_CUSVE_SOUND_CLEAR           1058
#define IDC_POINTATTR_CHECK_CAMERA_COLLISION 1059
#define IDC_BUTTON2                     1060
#define IDOK_DIRECTION_ADD              1061
#define IDC_LIST2                       1064
#define IDC_REFREE                      1065
#define IDC_BUTTON3                     1067
#define IDC_LIST5                       1078
#define IDC_BUTTON7                     1079
#define IDC_BUTTON8                     1080
#define IDC_BUTTON9                     1081
#define IDC_COMBO2                      1082
#define IDC_STATIC_NARRATION            1083
#define IDC_SLIDER_WEATHER_EFFECT       1084
#define IDC_SLIDER_BGM                  1085
#define IDC_SLIDER_WEATHER_MUSIC        1086
#define IDC_EXCEL_TABCTRL               2001
#define IDC_CONTROL_POINT_SHEET         2002
#define IDC_RULER_BAR                   2003
#define IDR_PANE_OPTIONS                4000
#define IDR_PANE_PROPERTIES             4001
#define IDR_PANE_SCRIPT                 4002
#define IDR_PANE_CONTROL                4003
#define IDR_PANE_OUTPUT                 4004
#define IDR_PANE_CONTROL_POINT          4005
#define IDR_PANE_ACTOR                  4006
#define IDR_PANE_SKILL                  4007
#define IDR_PANE_BOT                    4008
#define IDR_PANE_WAYPOINT               4009
#define IDR_PANE_CINEMATIC              4010
#define IDR_DIRECTION_PANE              4011
#define IDC_OBJ_PANE_PROP_TREECTRL      5000
#define IDC_SKILL_PANE_PROP_TREECTRL    5001
#define IDC_BOT_PANE_PROP_TREECTRL      5002
#define IDC_POINTEDIT_EDITVIEW0         5003
#define IDC_POINTEDIT_EDITVIEW1         5004
#define IDC_POINTEDIT_EDITVIEW2         5005
#define IDC_POINTEDIT_EDITVIEW3         5006
#define IDC_SEQUENCEEDIT_VIEW           5007
#define IDC_DIRECTION_PANE_PROP_TREECTRL 5008
#define ID_PANE_OBJ_ADD                 32775
#define ID_PANE_OBJ_DELETE              32776
#define ID_OBJ_PANE_ADD                 32777
#define ID_OBJ_PANE_DELETE              32778
#define ID_SCRIPT_PANE_COMPILE          32779
#define ID_SCRIPT_PANE_COMPILE_STOP     32780
#define ID_BUTTON32781                  32781
#define ID_BUTTON32782                  32782
#define ID_SCRIPT_PANE_COPY             32783
#define ID_SCRIPT_PANE_PASTE            32784
#define ID_OBJ_PANE_REBUILD             32785
#define ID_CONTROL_PANE_TIME_CHANGE     32786
#define ID_CONTROL_PANE_TIME_GRAPH      32787
#define ID_CONTROL_PANE_POINT           32788
#define ID_BUTTON32794                  32794
#define ID_CONTROL_PANE_SHAPE           32797
#define ID_CONTROL_PANE_RESET_CAMERA    32798
#define ID_CONTROL_PANE_RESET_TRANS     32799
#define ID_PROP_TRANS_POSITION          32800
#define ID_PROP_TRANS_ROTATE            32801
#define ID_PROP_TRANS_SCALE             32802
#define ID_POINT_TRANS_POSITION         32803
#define ID_CURVE_TRANS_ROTATE           32804
#define ID_VIEW_SPLINEMARK              32806
#define ID_SPLINEMARK_CONTROLLINE       32807
#define ID_SPLINEMARK_CURVELINE         32808
#define ID_SPLINEMARK_CURVEROTATELINE   32809
#define ID_CONTROL_PANE_ADD_POINT       32811
#define ID_CONTROL_PANE_REMOVE_POINT    32812
#define ID_OBJ_PANE_FORDER_ADD          32813
#define ID_OBJ_PANE_FOLDER_ADD          32814
#define ID_OBJECTTREE_RENAME            32815
#define ID_OBJECTTREE_ATTACHFILE        32816
#define ID_POPUP_OBJECTTREE_RENAME      32817
#define ID_POPUP_OBJECTTREE_ATTACHFILE  32818
#define ID_OBJ_PANE_RENAME              32819
#define ID_OBJ_PANE_IMPORT_FILE         32820
#define ID_RENDERVIEW_WORLDRENDERINGON  32824
#define ID_RENDERVIEW_D                 32825
#define ID_RENDERVIEW_CONTROLPOINTLINE  32826
#define ID_RENDERVIEW_CURVEPOINTLINE    32827
#define ID_RENDERVIEW_CURVEROTATELINE   32828
#define ID_RENDERVIEW_WORLDRENDER_ONOFF 32829
#define ID_EDIT_A                       32836
#define ID_EDIT_MODE_COMBO              32837
#define ID_EDIT_TELEPORT                32838
#define ID_AVATAR_TELEPORT              32839
#define ID_VIEWERCONTROL_TELEPORT       32840
#define ID_VIEWERCONTROL_AVATARSPEED    32841
#define ID_WORLD_CHANGE                 32842
#define ID_AVATAR_SPEED                 32843
#define ID_SKILL_PANE_USE               32844
#define ID_VIEWERCONTROL_AVATARRACE     32845
#define ID_AVATAR_RACE                  32846
#define ID_SCRIPT_PANE_COMPILE_ALL      32848
#define ID_POINTEDIT_QUATER_VIEW        32849
#define ID_POINTEDIT_ZOOMIN             32850
#define ID_POINTEDIT_ZOOMOUT            32851
#define ID_CONTROL_PANE_POINTEDIT       32852
#define ID_CONTROL_PANE_POINTROTATEEDIT 32853
#define ID_CONTROL_PANE_POINTATTREDIT   32854
#define ID_RENDERVIEW_DF                32855
#define ID_RENDERVIEW_VALIDCUSTOMDATA   32856
#define ID_SPLINEMARK_CURVE_CUSTOMDATA_VISIBLE 32857
#define ID_BUTTON_DIRECTION_SAVE        32858
#define ID_BUTTON_DIRECTION_LOAD        32859
#define ID_BUTTON_DIRECTION_ADD_SET     32860
#define ID_BUTTON_DIRECTION_ADD_NODE    32861
#define ID_BUTTON_DIRECTION_REMOVE      32862
#define ID_BUTTON_DIRECTION_RUN         32863
#define ID_BUTTON_STOP                  32864
#define ID_BUTTON_DIRECTION_STOP        32864
#define ID_VIEW_OPTION                  32865
#define ID_OPTION_SOUND                 32866

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32867
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
