/*****************************************************************************
*
* File			: DboTLDefine.h
* Author		: JeongHo, Rho
* Copyright		: (аж)NTL
* Date			: 2008. 4. 22	
* Abstract		: 
*****************************************************************************
* Desc         : 
*
*****************************************************************************/

#ifndef __DBO_TL_DEFINE_H__
#define __DBO_TL_DEFINE_H__


#define TL_SAFE_GUIDE_TIME					(0.1f)


enum ETL_CONDITION_TYPE
{
	ETL_CONDITION_TYPE_MOUSE_DRAG,

	ETL_CONDITION_TYPE_IN_CHECK_POINT,

	ETL_CONDITION_TYPE_MAINMENU_OPEN,

	ETL_CONDITION_TYPE_SKILL_OPEN,
	ETL_CONDITION_TYPE_SKILL_CLOSE,

	ETL_CONDITION_TYPE_QUICK_SLOT_1_REG_SKILL,
	ETL_CONDITION_TYPE_QUICK_SLOT_1_UNREG_SKILL,

	ETL_CONDITION_TYPE_STATUS_OPEN,
	ETL_CONDITION_TYPE_STATUS_SCOUTER_SLOT_REG,
	ETL_CONDITION_TYPE_STATUS_SCOUTER_SLOT_UNREG,
	ETL_CONDITION_TYPE_STATUS_CLOSE,

	ETL_CONDITION_TYPE_MOB_TARGET,
	ETL_CONDITION_TYPE_MOB_NORMAL_ATTACK,
	ETL_CONDITION_TYPE_MOB_SKILL_ATTACK,

	ETL_CONDITION_TYPE_LOOT_ITEM,

	ETL_CONDITION_TYPE_SCOUTER_USE,
	ETL_CONDITION_TYPE_SCOUTER_POWERLEVEL,
	ETL_CONDITION_TYPE_SCOUTER_CLOSE,

	ETL_CONDITION_TYPE_CAPSULEKIT_OPEN,
	ETL_CONDITION_TYPE_CAPSULEKIT_CLOSE,

	ETL_CONDITION_TYPE_CINEMATIC_PLAY_FINISH,

	ETL_CONDITION_TYPE_QUEST_FINISH,

	ETL_CONDITION_TYPE_INVALID,
};

enum ETL_UI_INDICATOR_TYPE
{
	ETL_UI_INDICATOR_TYPE_LP_WND,
	ETL_UI_INDICATOR_TYPE_MINIMAP,
	ETL_UI_INDICATOR_TYPE_CHAT,
	ETL_UI_INDICATOR_TYPE_QUICK_SLOT,
	ETL_UI_INDICATOR_TYPE_QUICK_SLOT_1,
	ETL_UI_INDICATOR_TYPE_CAPSULE_SLOT,
	ETL_UI_INDICATOR_TYPE_SCOUTER_SLOT,
	ETL_UI_INDICATOR_TYPE_MAIN_MENU,
	ETL_UI_INDICATOR_TYPE_MAIN_MENU_SKILL,
	ETL_UI_INDICATOR_TYPE_MAIN_MENU_STATUS,
	ETL_UI_INDICATOR_TYPE_STATUS_SCOUTER_SLOT,
	ETL_UI_INDICATOR_TYPE_CAPSULE_KIT_SCOUTER_ITEM,
	ETL_UI_INDICATOR_TYPE_SKILL_ICON,
	ETL_UI_INDICATOR_TYPE_SKILL_CLOSE_BTN,
	ETL_UI_INDICATOR_TYPE_SCOUTER_POWERLEVEL,
	ETL_UI_INDICATOR_TYPE_SCOUTER_CLOSE_BTN,
	ETL_UI_INDICATOR_TYPE_INVALID,
};


enum ETL_MOUSE_INPUT_TYPE
{
	ETL_MOUSE_INPUT_TYPE_TARGETING,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_CLOSE,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_SKILL_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_SKILL_CLOSE,
	ETL_MOUSE_INPUT_TYPE_SKILL_WND_CLOSE_BTN,
	ETL_MOUSE_INPUT_TYPE_SKILL_WND_TAB,

	ETL_MOUSE_INPUT_TYPE_QUICK_SLOT_CHANGE,

	ETL_MOUSE_INPUT_TYPE_QUICK_SLOT_1_REG,
	ETL_MOUSE_INPUT_TYPE_QUICK_SLOT_1_UNREG,
	ETL_MOUSE_INPUT_TYPE_QUICK_SLOT_1_EXCUTE,
	ETL_MOUSE_INPUT_TYPE_QUICK_SLOT_2_LAST_REG,
	ETL_MOUSE_INPUT_TYPE_QUICK_SLOT_2_LAST_UNREG,
	ETL_MOUSE_INPUT_TYPE_QUICK_SLOT_2_LAST_EXCUTE,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_STATUS_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_STATUS_CLOSE,
	ETL_MOUSE_INPUT_TYPE_STATUS_WND_SCOUTER_SLOT,
	ETL_MOUSE_INPUT_TYPE_STATUS_WND_CLOSE_BTN,
	ETL_MOUSE_INPUT_TYPE_STATUS_WND_TAB,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_CAPSULE_KIT_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_CAPSULE_KIT_CLOSE,
	ETL_MOUSE_INPUT_TYPE_CPASULE_SLOT_OPEN,
	ETL_MOUSE_INPUT_TYPE_CPASULE_SLOT_CLOSE,
	ETL_MOUSE_INPUT_TYPE_CPASULE_KIT_WND_SLOTS_PICK_UP,
	ETL_MOUSE_INPUT_TYPE_CPASULE_KIT_WND_SLOTS_DROP_DOWN,
	ETL_MOUSE_INPUT_TYPE_CPASULE_KIT_WND_CLOSE_BTN,
	ETL_MOUSE_INPUT_TYPE_CPASULE_KIT_WND_TRASH,

	ETL_MOUSE_INPUT_TYPE_SCOUTER_ON_MODE,
	ETL_MOUSE_INPUT_TYPE_SCOUTER_OFF_MODE,

	ETL_MOUSE_INPUT_TYPE_SCOUTER_MODE_POWERLEVEL,
	ETL_MOUSE_INPUT_TYPE_SCOUTER_MODE_CLOSE_BTN,
	ETL_MOUSE_INPUT_TYPE_SCOUTER_SLOT,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_HELP_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_HELP_CLOSE,
	ETL_MOUSE_INPUT_TYPE_HELP_WND_CLOSE_BTN,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_QUEST_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_QUEST_CLOSE,
	ETL_MOUSE_INPUT_TYPE_QUEST_WND_CLOSE_BTN,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_COMMUNITY_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_COMMUNITY_CLOSE,
	ETL_MOUSE_INPUT_TYPE_COMMUNITY_WND_CLOSE_BTN,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_RANKBOARD_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_RANKBOARD_CLOSE,
	ETL_MOUSE_INPUT_TYPE_RANKBOARD_WND_CLOSE_BTN,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_OPTION_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_OPTION_CLOSE,
	ETL_MOUSE_INPUT_TYPE_OPTION_WND_CLOSE_BTN,

	ETL_MOUSE_INPUT_TYPE_MAINMENU_FRIEND_OPEN,
	ETL_MOUSE_INPUT_TYPE_MAINMENU_FRIEND_CLOSE,
	ETL_MOUSE_INPUT_TYPE_FRIEND_WND_CLOSE_BTN,

	ETL_MOUSE_INPUT_TYPE_MINIMAP,

	ETL_MOUSE_INPUT_TYPE_MOVE,

	ETL_MOUSE_INPUT_TYPE_HELP_BUTTON_IN_DIALOG,

	ETL_MOUSE_INPUT_TYPE_ALL,
};


enum ETL_KEYBOARD_INPUT_TYPE
{
	ETL_KEYBOARD_INPUT_TYPE_MOVE,

	ETL_KEYBOARD_INPUT_TYPE_LOOTING,

	ETL_KEYBOARD_INPUT_TYPE_TARGETING,
	ETL_KEYBOARD_INPUT_TYPE_ESC_TARGETING,

	ETL_KEYBOARD_INPUT_TYPE_QUICK_SLOT_CHANGE,

	ETL_KEYBOARD_INPUT_TYPE_QUICK_SLOT_1,
	ETL_KEYBOARD_INPUT_TYPE_QUICK_SLOT_2_LAST,

	ETL_KEYBOARD_INPUT_TYPE_SCOUTER,
	ETL_KEYBOARD_INPUT_TYPE_ESC_SCOUTER_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_SCOUTER_MODE,
	ETL_KEYBOARD_INPUT_TYPE_ESC_SCOUTER_MODE_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_SKILL_OPEN,
	ETL_KEYBOARD_INPUT_TYPE_SKILL_CLOSE,
	ETL_KEYBOARD_INPUT_TYPE_ESC_SKILL_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_STATUS_OPEN,
	ETL_KEYBOARD_INPUT_TYPE_STATUS_CLOSE,
	ETL_KEYBOARD_INPUT_TYPE_ESC_STATUS_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_CAPSULE_KIT_OPEN,
	ETL_KEYBOARD_INPUT_TYPE_CAPSULE_KIT_CLOSE,
	ETL_KEYBOARD_INPUT_TYPE_ESC_CAPSULE_KIT_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_QUEST,
	ETL_KEYBOARD_INPUT_TYPE_ESC_QUEST_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_GUILD,
	ETL_KEYBOARD_INPUT_TYPE_ESC_COMMUNITY_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_RANKBOARD,
	ETL_KEYBOARD_INPUT_TYPE_ESC_RANKBOARD_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_OPTION,
	ETL_KEYBOARD_INPUT_TYPE_ESC_OPTION_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_FRIEND,
	ETL_KEYBOARD_INPUT_TYPE_ESC_FRIEND_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_WORLDMAP,
	ETL_KEYBOARD_INPUT_TYPE_ESC_WORLDMAP_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_MINIMAP,

	ETL_KEYBOARD_INPUT_TYPE_HELP,
	ETL_KEYBOARD_INPUT_TYPE_ESC_HELP_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_MAINMENU,
	ETL_KEYBOARD_INPUT_TYPE_ESC_MAINMENU_CLOSE,

	ETL_KEYBOARD_INPUT_TYPE_AUTORUN,

	ETL_KEYBOARD_INPUT_TYPE_ALL,
};


enum ETL_ATTACK_TYPE
{
	ETL_ATTACK_TYPE_NORMAL_ATTACK,
	ETL_ATTACK_TYPE_SKILL_ATTACK,
	ETL_ATTACK_TYPE_ALL,
};


enum ETL_CAMERA_TYPE
{
	ETL_CAMERA_TYPE_MOB,
	ETL_CAMERA_TYPE_NPC,
	ETL_CAMERA_TYPE_POSITION,
};


#endif