//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CNtlStorageSerializer.h
//  @ Date : 2009-01-22
//  @ Author : 
//
//


#if !defined(_CNTLSTORAGESERIALIZER_H)
#define _CNTLSTORAGESERIALIZER_H

#include "NtlSerializer.h"

enum eNTL_STORAGE_SERIALIZER_TYPE
{
	eNTL_STORAGE_SERIALIZER_TEXT = 0,		// 텍스트 시리얼라이저
	eNTL_STORAGE_SERIALIZER_BINARY,			// 바이너리 시리얼라이저

	eNTL_STORAGE_SERIALIZER_NUMS,
	eNTL_STORAGE_SERIALIZER_INVALID
};


class CNtlStorageSerializer : public CNtlSerializer
{
public:
	CNtlStorageSerializer();
	CNtlStorageSerializer(int nBufferSize, int nGlowSize);
	virtual ~CNtlStorageSerializer();

	void								SetStorageSerializerType(eNTL_STORAGE_SERIALIZER_TYPE eType);
	eNTL_STORAGE_SERIALIZER_TYPE		GetStorageSerializerType();

protected:
	eNTL_STORAGE_SERIALIZER_TYPE		m_eType;

};

#endif  //_CNTLSTORAGESERIALIZER_H
