//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CNtlStorageBinarySerializer.h
//  @ Date : 2009-01-22
//  @ Author : 
//
//


#if !defined(_CNTLSTORAGEBINARYSERIALIZER_H)
#define _CNTLSTORAGEBINARYSERIALIZER_H

#include "NtlStorageSerializer.h"

class CNtlStorageBinarySerializer : public CNtlStorageSerializer
{
public:
	CNtlStorageBinarySerializer();
	CNtlStorageBinarySerializer(int nBufferSize, int nGlowSize);
	~CNtlStorageBinarySerializer();
};

#endif  //_CNTLSTORAGEBINARYSERIALIZER_H