//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CNtlStorageTextSerializer.h
//  @ Date : 2009-01-22
//  @ Author : 
//
//


#if !defined(_CNTLSTORAGETEXTSERIALIZER_H)
#define _CNTLSTORAGETEXTSERIALIZER_H

#include "NtlStorageSerializer.h"

class CNtlStorageTextSerializer : public CNtlStorageSerializer
{
public:
	CNtlStorageTextSerializer();
	CNtlStorageTextSerializer(int nBufferSize, int nGlowSize);
	~CNtlStorageTextSerializer();

	CNtlSerializer& operator << (char chData);
	CNtlSerializer& operator << (unsigned char byData);
	CNtlSerializer& operator << (short shData);
	CNtlSerializer& operator << (unsigned short wData);
	CNtlSerializer& operator << (int iData);
	CNtlSerializer& operator << (unsigned int uiData);
	CNtlSerializer& operator << (long lData);
	CNtlSerializer& operator << (unsigned long ulData);
	CNtlSerializer& operator << (__int64 i64Data);
	CNtlSerializer& operator << (unsigned __int64 ui64Data);
	CNtlSerializer& operator << (float fData);
	CNtlSerializer& operator << (double dData);
	CNtlSerializer& operator << (char *pData);
	CNtlSerializer& operator << (const char *pData);
	CNtlSerializer& operator << (std::string& str);

	CNtlSerializer& operator >> (char& chData);
	CNtlSerializer& operator >> (unsigned char& byData);
	CNtlSerializer& operator >> (short& shData);
	CNtlSerializer& operator >> (unsigned short& wData);
	CNtlSerializer& operator >> (int& iData);
	CNtlSerializer& operator >> (unsigned int& uiData);
	CNtlSerializer& operator >> (long& lData);
	CNtlSerializer& operator >> (unsigned long& ulData);
	CNtlSerializer& operator >> (__int64& i64Data);
	CNtlSerializer& operator >> (unsigned __int64& ui64Data);
	CNtlSerializer& operator >> (float& fData);
	CNtlSerializer& operator >> (double& dData);
	CNtlSerializer& operator >> (std::string& str);	
};

#endif  //_CNTLSTORAGETEXTSERIALIZER_H
