#ifndef _AISCRIPTGLOBALDEFINE_H_
#define _AISCRIPTGLOBALDEFINE_H_


enum eAIS_NODE
{
	AIS_NODE_STATE_SCENE = 0x29,
	AIS_NODE_STATE,
	AIS_NODE_STATE_SPAWN,
	AIS_NODE_STATE_IDLE,
	AIS_NODE_STATE_FIGHT,
	AIS_NODE_STATE_NONBATTLEACTIONPATTERNSET,
	AIS_NODE_STATE_TELEPORTING,
	AIS_NODE_STATE_COMEBACK,
	AIS_NODE_STATE_WANDER,
	AIS_NODE_ACTION_ADD_MOB,
	AIS_NODE_ACTION_SENDEVENTTOWPS,
	AIS_NODE_ACTION_SENDEVENTTOTQS,
	AIS_NODE_CONDITION_HIMSELF_CHECK,
	AIS_NODE_CONDITION_SCAN,
	AIS_NODE_CONDITION_RECV_EVENT_FROM_WPS,
	AIS_NODE_CONDITION_RECV_EVENT_FROM_TQS,

	MAX_AIS_NODE,
	INVALID_AIS_NODE = 0xFFFFFFFF,
};


#endif