#ifndef _TQSCRIPTGLOBALDEFINE_H_
#define _TQSCRIPTGLOBALDEFINE_H_


enum eTQS_NODE
{
	TQS_NODE_STATE_GAME_BEGIN,
	TQS_NODE_STATE_GAME_END,
	TQS_NODE_STATE_GAME_STAGE,
	TQS_NODE_ACTION_ADD_NPC,
	TQS_NODE_ACTION_REMOVE_NPC,
	TQS_NODE_ACTION_ADD_MOB,
	TQS_NODE_ACTION_ADD_MOB_GROUP,
	TQS_NODE_ACTION_REMOVE_MOB_GROUP,
	TQS_NODE_ACTION_ADD_DIRECT_PLAY,
	TQS_NODE_ACTION_WAIT,
	TQS_NODE_ACTION_SYSTEM_MESSAGE,
	TQS_NODE_ACTION_CHANGE_STAGE,
	TQS_NODE_ACTION_CHANGE_OBJECT_STATE,
	TQS_NODE_ACTION_TIME_COUNTDOWN,
	TQS_NODE_ACTION_SEND_TS_EVENT,
	TQS_NODE_ACTION_SEND_EVENT_TO_TS,
	TQS_NODE_ACTION_SEND_TQS_EVENT,
	TQS_NODE_ACTION_SEND_EVENT_TO_SPS,
	TQS_NODE_ACTION_SEND_EVENT_TO_WPS,
	TQS_NODE_ACTION_SEND_EVENT_TO_AIS,
	TQS_NODE_ACTION_REWARD,
	TQS_NODE_ACTION_INFORMATION,
	TQS_NODE_ACTION_TELECAST_MESSAGE,
	TQS_NODE_ACTION_BROAD_MESSAGE,
	TQS_NODE_ACTION_MINI_NARRATION,
	TQS_NODE_ACTION_PROGRESS_MESSAGE,
	TQS_NODE_ACTION_DIRECTION_INDICATE,
	TQS_NODE_ACTION_CHANGE_TMQ_POINT,
	TQS_NODE_ACTION_CHANGE_BONUS_TIME,
	TQS_NODE_ACTION_REGISTER_CONDITION,
	TQS_NODE_ACTION_TELEPORT,
	TQS_NODE_ACTION_PLAY_BGM,
	TQS_NODE_ACTION_PLAY_JINGLE,
	TQS_NODE_ACTION_CLEAR_EVENT,
	TQS_NODE_ACTION_TMQ_FAIL,
	TQS_NODE_ACTION_FUNCTION,
	TQS_NODE_ACTION_IF,
	TQS_NODE_ACTION_THEN,
	TQS_NODE_ACTION_ELSE,
	TQS_NODE_CONDITION_RECV_TS_EVENT,
	TQS_NODE_CONDITION_RECV_EVENT_FROM_TS,
	TQS_NODE_CONDITION_RECV_SPS_EVENT,
	TQS_NODE_CONDITION_RECV_EVENT_FROM_SPS,
	TQS_NODE_CONDITION_RECV_EVENT_FROM_AIS,
	TQS_NODE_CONDITION_RECV_EVENT_FROM_WPS,
	TQS_NODE_CONDITION_CHECK_TIME,
	TQS_NODE_CONDITION_CHECK_COUNTDOWN,
	TQS_NODE_CONDITION_CHECK_MOB_GROUP,
	TQS_NODE_CONDITION_NPC_FAINT,
	TQS_NODE_CONDITION_ALL_PLAYER_FAINT,
	TQS_NODE_CONDITION_AREA_ENTER,
	TQS_NODE_CONDITION_CHILD,
	MAX_TQS_NODE,

	INVALID_TQS_NODE = 0xFFFFFFFF,
};

enum eTQS_SEND_EVENT_TYPE
{
	TQS_SEND_EVENT_SPS,
	TQS_SEND_EVENT_AIS,
	MAX_TQS_SEND_EVENT_TYPE,

	INVALID_TQS_SEND_EVENT_TYPE,
};

enum eTQS_SEND_TYPE
{
	TQS_SEND_TYPE_ALL,
	TQS_SEND_TYPE_ONE,
	TQS_SEND_TYPE_INVALID = 0xFFFFFFFF,
};


#endif