#include "stdafx.h"
#include "ug_opcodes.h"
#include "ClientSession.h"



CUG_Opcodes::CUG_Opcodes()
{
	BuildOpcodeList();
}


CUG_Opcodes::~CUG_Opcodes()
{
	delete[] aOpcodeHandler;
}


void CUG_Opcodes::BuildOpcodeList()
{
	for (int i = 0; i < UG_OPCODE_END - UG_OPCODE_BEGIN; i++)
		aOpcodeHandler[i] = new OpcodeHandler<CClientSession>;

	StoreOpcode(UG_TUTORIAL_HINT_UPDATE_REQ, "UG_TUTORIAL_HINT_UPDATE_REQ", PROCESS_INPLACE, &CClientSession::RecvTutorialHintReq);
	StoreOpcode(UG_TUTORIAL_WAIT_CANCEL_REQ, "UG_TUTORIAL_WAIT_CANCEL_REQ", PROCESS_INPLACE, &CClientSession::RecvTutorialWaitCancelReq);
	StoreOpcode(UG_TUTORIAL_PLAY_QUIT_REQ, "UG_TUTORIAL_PLAY_QUIT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTutorialQuitReq);
	StoreOpcode(UG_CHAR_DASH_KEYBOARD, "UG_CHAR_DASH_KEYBOARD", PROCESS_THREADUNSAFE, &CClientSession::RecvCharDashKeyBoard);
	StoreOpcode(UG_CHAR_DASH_MOUSE, "UG_CHAR_DASH_MOUSE", PROCESS_THREADUNSAFE, &CClientSession::RecvCharDashMouse);
	StoreOpcode(UG_CHAR_JUMP, "UG_CHAR_JUMP", PROCESS_THREADUNSAFE, &CClientSession::RecvCharJump);
	StoreOpcode(UG_CHAR_JUMP_END, "UG_CHAR_JUMP_END", PROCESS_THREADUNSAFE, &CClientSession::RecvCharJumpEnd);
	StoreOpcode(UG_CHAR_FALLING, "UG_CHAR_FALLING", PROCESS_THREADUNSAFE, &CClientSession::RecvCharFalling);
	StoreOpcode(UG_CHAR_TOGG_SITDOWN, "UG_CHAR_TOGG_SITDOWN", PROCESS_THREADUNSAFE, &CClientSession::RecvCharSitDown);
	StoreOpcode(UG_CHAR_TOGG_FIGHTING, "UG_CHAR_TOGG_FIGHTING", PROCESS_THREADUNSAFE, &CClientSession::RecvCharToggFight);
	StoreOpcode(UG_CHAR_ATTACK_BEGIN, "UG_CHAR_ATTACK_BEGIN", PROCESS_THREADUNSAFE, &CClientSession::RecvAttackBegin);
	StoreOpcode(UG_CHAR_ATTACK_END, "UG_CHAR_ATTACK_END", PROCESS_THREADUNSAFE, &CClientSession::RecvAttackEnd);
	StoreOpcode(UG_CHAR_CHARGE, "UG_CHAR_CHARGE", PROCESS_THREADUNSAFE, &CClientSession::RecvRpCharge);
	StoreOpcode(UG_CHAR_BLOCK_MODE, "UG_CHAR_BLOCK_MODE", PROCESS_THREADUNSAFE, &CClientSession::RecvBlockMode); //UNSAFE BECAUSE GUARD MIGHT BREAK WHILE TRYING PROCESSING THIS PACKET
	StoreOpcode(UG_CHAR_TELEPORT_REQ, "UG_CHAR_TELEPORT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharTeleportReq);		//UNSAFE BECAUSE WE LEAVE WORLD
	StoreOpcode(UG_CHAR_BIND_REQ, "UG_CHAR_BIND_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharBindReq);
	StoreOpcode(UG_CHAR_REVIVAL_REQ, "UG_CHAR_REVIVAL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharRevivalReq);
	StoreOpcode(UG_CHAR_SERVER_CHANGE_REQ, "UG_CHAR_SERVER_CHANGE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharServerChangeReq);
	StoreOpcode(UG_CHAR_CHANNEL_CHANGE_REQ, "UG_CHAR_CHANNEL_CHANGE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvChangeChannelReq);
	StoreOpcode(UG_CHAR_TARGET_SELECT, "UG_CHAR_TARGET_SELECT", PROCESS_THREADUNSAFE, &CClientSession::RecvCharTargetSelect);
	StoreOpcode(UG_CHAR_TARGET_INFO, "UG_CHAR_TARGET_INFO", PROCESS_THREADUNSAFE, &CClientSession::RecvCharTargetInfo);
	StoreOpcode(UG_CHAR_TARGET_FACING, "UG_CHAR_TARGET_FACING", PROCESS_THREADUNSAFE, &CClientSession::RecvCharTargetFacing);
	StoreOpcode(UG_CHAR_READY_FOR_COMMUNITY_SERVER_NFY, "UG_CHAR_READY_FOR_COMMUNITY_SERVER_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecCharReadyForCommunityServerNfy);
	StoreOpcode(UG_CHAR_READY_TO_SPAWN, "UG_CHAR_READY_TO_SPAWN", PROCESS_THREADUNSAFE, &CClientSession::RecvCharReadyToSpawn);
	StoreOpcode(UG_CHAR_READY, "UG_CHAR_READY", PROCESS_THREADUNSAFE, &CClientSession::RecvCharReady); //UNSAFE BECAUSE WE COULD ENTER RANKED BATTLE
	StoreOpcode(UG_CHAR_MOVE, "UG_CHAR_MOVE", PROCESS_THREADUNSAFE, &CClientSession::RecvCharMove);
	StoreOpcode(UG_CHAR_DEST_MOVE, "UG_CHAR_DEST_MOVE", PROCESS_THREADUNSAFE, &CClientSession::RecvCharDestMove);
	StoreOpcode(UG_CHAR_CHANGE_HEADING, "UG_CHAR_CHANGE_HEADING", PROCESS_THREADUNSAFE, &CClientSession::RecvCharChangeHeading);
	StoreOpcode(UG_CHAR_MOVE_COLLISION, "UG_CHAR_MOVE_COLLISION", PROCESS_THREADUNSAFE, &CClientSession::RecvCharMoveCollision);
	StoreOpcode(UG_CHAR_MOVE_COLLISION_END, "UG_CHAR_MOVE_COLLISION_END", PROCESS_THREADUNSAFE, &CClientSession::RecvCharMoveCollisionEnd);
	StoreOpcode(UG_CHAR_STANDING_SLIP, "UG_CHAR_STANDING_SLIP", PROCESS_THREADUNSAFE, &CClientSession::RecvCharStandingSlip);
	StoreOpcode(UG_CHAR_STANDING_SLIP_END, "UG_CHAR_STANDING_SLIP_END", PROCESS_THREADUNSAFE, &CClientSession::RecvCharStandingSlipEnd);
	StoreOpcode(UG_CHAR_LOCATION_SYNC, "UG_CHAR_LOCATION_SYNC", PROCESS_THREADUNSAFE, &CClientSession::RecvCharLocationSync);
	StoreOpcode(UG_CHAR_AIR_MOVE_SYNC, "UG_CHAR_AIR_MOVE_SYNC", PROCESS_THREADUNSAFE, &CClientSession::RecvCharAirMoveSync);
	StoreOpcode(UG_CHAR_CHANGE_DIRECTION_ON_FLOATING, "UG_CHAR_CHANGE_DIRECTION_ON_FLOATING", PROCESS_THREADUNSAFE, &CClientSession::RecvCharChangeDirOnFloating);
	StoreOpcode(UG_CHAR_FOLLOW_MOVE, "UG_CHAR_FOLLOW_MOVE", PROCESS_THREADUNSAFE, &CClientSession::RecvCharFollowMove);
	StoreOpcode(UG_CHAR_FOLLOW_MOVE_SYNC, "UG_CHAR_FOLLOW_MOVE_SYNC", PROCESS_THREADUNSAFE, &CClientSession::RecvCharFollowMoveSync);
	StoreOpcode(UG_GAME_ENTER_REQ, "UG_GAME_ENTER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGameEnterReq);		//Should always be PROCESS_THREADUNSAFE
	StoreOpcode(UG_GAME_LEAVE_REQ, "UG_GAME_LEAVE_REQ", PROCESS_INPLACE, &CClientSession::RecvGameLeaveReq);
	StoreOpcode(UG_AUTH_KEY_FOR_COMMUNITY_SERVER_REQ, "UG_AUTH_KEY_FOR_COMMUNITY_SERVER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvAuthKeyForCumminityServerReq);
	StoreOpcode(UG_ENTER_WORLD, "UG_ENTER_WORLD", PROCESS_THREADUNSAFE, &CClientSession::RecvEnterWorld); //UNSAFE BECAUSE WE ENTER WORLD
	StoreOpcode(UG_LOADING_COMPLETE_NFY, "UG_LOADING_COMPLETE_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvLoadingCompleteNfy);
	StoreOpcode(UG_SERVER_COMMAND, "UG_SERVER_COMMAND", PROCESS_THREADUNSAFE, &CClientSession::RecvServerCommand);
	StoreOpcode(UG_SKILL_TARGET_LIST, "UG_SKILL_TARGET_LIST", PROCESS_THREADUNSAFE, &CClientSession::RecvSkillTargetList); // Player finish casting -> receive list of targets and skill process go on UNSAFE
	StoreOpcode(UG_SKILL_LEARN_REQ, "UG_SKILL_LEARN_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvLearnSkillReq);
	StoreOpcode(UG_SKILL_LEARN_BY_ITEM_REQ, "UG_SKILL_LEARN_BY_ITEM_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvLearnSkillByItemReq);
	StoreOpcode(UG_SKILL_UPGRADE_REQ, "UG_SKILL_UPGRADE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharSkillUpgradeReq);
	StoreOpcode(UG_SKILL_RP_BONUS_SETTING_REQ, "UG_SKILL_RP_BONUS_SETTING_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvRpBonusSettingReq);
	StoreOpcode(UG_HTB_START_REQ, "UG_HTB_START_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvHTBStartReq);
	StoreOpcode(UG_HTB_LEARN_REQ, "UG_HTB_LEARN_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvHTBLearnReq);
	StoreOpcode(UG_HTB_FORWARD_REQ, "UG_HTB_FORWARD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvHTBForwardReq);
	StoreOpcode(UG_HTB_RP_BALL_USE_REQ, "UG_HTB_RP_BALL_USE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvHTBRpBallUseReq);
	StoreOpcode(UG_BUFF_DROP_REQ, "UG_BUFF_DROP_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBuffDropReq);				//UNSAFE BECAUSE BUFF COULD BE REMOVED WHILE UPDATING BUFF
	StoreOpcode(UG_ITEM_MOVE_REQ, "UG_ITEM_MOVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemMoveReq);
	StoreOpcode(UG_ITEM_MOVE_STACK_REQ, "UG_ITEM_MOVE_STACK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemStackReq);
	StoreOpcode(UG_ITEM_DELETE_REQ, "UG_ITEM_DELETE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemDeleteReq);
	StoreOpcode(UG_ITEM_EQUIP_REPAIR_REQ, "UG_ITEM_EQUIP_REPAIR_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvEquipRepairReq);
	StoreOpcode(UG_ITEM_PICK_REQ, "UG_ITEM_PICK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPickUpItemReq);				//UNSAFE BECAUSE SYSTEM CAN REMOVE DROP WHILE PICK UP
	StoreOpcode(UG_ITEM_REPAIR_REQ, "UG_ITEM_REPAIR_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvRepairItemReq);				
	StoreOpcode(UG_ITEM_USE_REQ, "UG_ITEM_USE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemUseReq);
	StoreOpcode(UG_ITEM_UPGRADE_REQ, "UG_ITEM_UPGRADE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemUpgradeReq);
	StoreOpcode(UG_ITEM_IDENTIFY_REQ, "UG_ITEM_IDENTIFY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvIdentifyItemReq);
	StoreOpcode(UG_ZENNY_PICK_REQ, "UG_ZENNY_PICK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvZennyPickUpReq);			//UNSAFE BECAUSE SYSTEM CAN REMOVE DROP WHILE PICK UP
	StoreOpcode(UG_SHOP_START_REQ, "UG_SHOP_START_REQ", PROCESS_INPLACE, &CClientSession::RecvShopStartReq);
	StoreOpcode(UG_SHOP_BUY_REQ, "UG_SHOP_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvShopBuyReq);
	StoreOpcode(UG_SHOP_SELL_REQ, "UG_SHOP_SELL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvShopSellReq);
	StoreOpcode(UG_SHOP_END_REQ, "UG_SHOP_END_REQ", PROCESS_INPLACE, &CClientSession::RecvShopEndReq);
	StoreOpcode(UG_PARTY_CREATE_REQ, "UG_PARTY_CREATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCreatePartyReq);
	StoreOpcode(UG_PARTY_DISBAND_REQ, "UG_PARTY_DISBAND_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDisbandPartyReq); //UNSAFE
	StoreOpcode(UG_PARTY_INVITE_REQ, "UG_PARTY_INVITE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyInviteReq);
	StoreOpcode(UG_PARTY_INVITE_CHARID_REQ, "UG_PARTY_INVITE_CHARID_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyInviteCharIdReq);
	StoreOpcode(UG_PARTY_INVITE_CHAR_NAME_REQ, "UG_PARTY_INVITE_CHAR_NAME_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyInviteCharNameReq);
	StoreOpcode(UG_PARTY_RESPONSE_INVITATION, "UG_PARTY_RESPONSE_INVITATION", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyResponse);		//UNSAFE BECAUSE PLAYER COULD BE REMOVED FROM PARTY BY ANOTHER THREAD
	StoreOpcode(UG_PARTY_LEAVE_REQ, "UG_PARTY_LEAVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyLeaveReq);	//UNSAFE BECAUSE PLAYER COULD BE REMOVED FROM PARTY BY ANOTHER THREAD
	StoreOpcode(UG_PARTY_KICK_OUT_REQ, "UG_PARTY_KICK_OUT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvKickPartyMemberReq);	//UNSAFE BECAUSE PLAYER COULD BE REMOVED FROM PARTY BY ANOTHER THREAD
	StoreOpcode(UG_PARTY_CHANGE_LEADER_REQ, "UG_PARTY_CHANGE_LEADER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvChangePartyLeaderReq);
	StoreOpcode(UG_PARTY_CHANGE_ZENNY_LOOTING_METHOD_REQ, "UG_PARTY_CHANGE_ZENNY_LOOTING_METHOD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyChangeZeniLootMethodReq);
	StoreOpcode(UG_PARTY_CHANGE_ITEM_LOOTING_METHOD_REQ, "UG_PARTY_CHANGE_ITEM_LOOTING_METHOD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyChangeItemLootMethodReq);
	StoreOpcode(UG_BANK_START_REQ, "UG_BANK_START_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankStartReq);
	StoreOpcode(UG_BANK_MOVE_REQ, "UG_BANK_MOVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankMoveReq);
	StoreOpcode(UG_BANK_MOVE_STACK_REQ, "UG_BANK_MOVE_STACK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankStackReq);
	StoreOpcode(UG_BANK_END_REQ, "UG_BANK_END_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankEndReq);
	StoreOpcode(UG_BANK_ZENNY_REQ, "UG_BANK_ZENNY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankZeniReq);
	StoreOpcode(UG_BANK_BUY_REQ, "UG_BANK_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankBuyReq);
	StoreOpcode(UG_BANK_ITEM_DELETE_REQ, "UG_BANK_ITEM_DELETE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankDeleteReq);
	StoreOpcode(UG_SCOUTER_INDICATOR_REQ, "UG_SCOUTER_INDICATOR_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvScouterIndicatorReq);
	StoreOpcode(UG_SCOUTER_EQUIP_CHECK_REQ, "UG_SCOUTER_EQUIP_CHECK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvScouterEquipCheckReq);
	StoreOpcode(UG_SOCIAL_ACTION, "UG_SOCIAL_ACTION", PROCESS_INPLACE, &CClientSession::RecvSocialSkill);
	StoreOpcode(UG_TS_CONFIRM_STEP_REQ, "UG_TS_CONFIRM_STEP_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTsConfirmReq);			//UNSAFE BECAUSE QUEST COULD END IN MAIN THREAD WHILE PROCESS PACKET
	StoreOpcode(UG_TS_CONFIRM_STEP_FOR_USE_ITEM_REQ, "UG_TS_CONFIRM_STEP_FOR_USE_ITEM_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTsConfirmForUseItemReq); //UNSAFE BECAUSE QUEST COULD END IN MAIN THREAD WHILE PROCESS PACKET
	StoreOpcode(UG_TS_UPDATE_STATE, "UG_TS_UPDATE_STATE", PROCESS_THREADUNSAFE, &CClientSession::RecvTSUpdateState); //UNSAFE BECAUSE QUEST COULD END IN MAIN THREAD WHILE PROCESS PACKET
	StoreOpcode(UG_TS_EXCUTE_TRIGGER_OBJECT, "UG_TS_EXCUTE_TRIGGER_OBJECT", PROCESS_THREADUNSAFE, &CClientSession::RecvTSExcuteTriggerObject);  //UNSAFE BECAUSE QUEST COULD END IN MAIN THREAD WHILE PROCESS PACKET
	StoreOpcode(UG_QUEST_ITEM_MOVE_REQ, "UG_QUEST_ITEM_MOVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvQuestItemMoveReq);
	StoreOpcode(UG_QUEST_ITEM_DELETE_REQ, "UG_QUEST_ITEM_DELETE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvQuestItemDeleteReq);
	StoreOpcode(UG_QUEST_GIVEUP_REQ, "UG_QUEST_GIVEUP_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvQuestGiveUpReq);			//UNSAFE BECAUSE QUEST COULD END IN MAIN THREAD WHILE PROCESS PACKET
	StoreOpcode(UG_QUEST_SHARE, "UG_QUEST_SHARE", PROCESS_THREADUNSAFE, &CClientSession::RecvQuestShare);
	StoreOpcode(UG_QUEST_OBJECT_VISIT_REQ, "UG_QUEST_OBJECT_VISIT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvQuestObjectVisitReq);
	StoreOpcode(UG_FREEBATTLE_CHALLENGE_REQ, "UG_FREEBATTLE_CHALLENGE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvFreeBattleChallengeReq);//UNSAFE BECAUSE FREE BATTLE COULD END WHILE CREATING ONE
	StoreOpcode(UG_FREEBATTLE_ACCEPT_RES, "UG_FREEBATTLE_ACCEPT_RES", PROCESS_THREADUNSAFE, &CClientSession::RecvFreeBattleAccpetReq); //UNSAFE COZ FREEBATTLE COULD BE DELETED BEFORE WE ACCEPT
	StoreOpcode(UG_QUICK_SLOT_UPDATE_REQ, "UG_QUICK_SLOT_UPDATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvQuickSlotUpdateReq);
	StoreOpcode(UG_QUICK_SLOT_DEL_REQ, "UG_QUICK_SLOT_DEL_REQ", PROCESS_INPLACE, &CClientSession::RecvQuickSlotDelReq);
	StoreOpcode(UG_PET_DISMISS_PET_REQ, "UG_PET_DISMISS_PET_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPetDismissPetReq);
	StoreOpcode(UG_TRADE_START_REQ, "UG_TRADE_START_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeStartReq);
	StoreOpcode(UG_TRADE_OK_RES, "UG_TRADE_OK_RES", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeOkRes);		//unsafe because trade request could end while process this packet
	StoreOpcode(UG_TRADE_ADD_REQ, "UG_TRADE_ADD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeAddReq);
	StoreOpcode(UG_TRADE_DEL_REQ, "UG_TRADE_DEL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeDelReq);
	StoreOpcode(UG_TRADE_MODIFY_REQ, "UG_TRADE_MODIFY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeModifyReq);
	StoreOpcode(UG_TRADE_ZENNY_UPDATE_REQ, "UG_TRADE_ZENNY_UPDATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeZeniUpdateReq);
	StoreOpcode(UG_TRADE_END_REQ, "UG_TRADE_END_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeEndReq);
	StoreOpcode(UG_TRADE_CANCEL_REQ, "UG_TRADE_CANCEL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeCancelReq);
	StoreOpcode(UG_TRADE_DENY_REQ, "UG_TRADE_DENY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTradeDenyReq);
	StoreOpcode(UG_GUILD_CREATE_REQ, "UG_GUILD_CREATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildCreateReq);
	StoreOpcode(UG_GUILD_INVITE_REQ, "UG_GUILD_INVITE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildInviteReq);
	StoreOpcode(UG_DRAGONBALL_CHECK_REQ, "UG_DRAGONBALL_CHECK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDragonBallCheckReq); //unsafe because we may spawn shenron(npc) which enter world
	StoreOpcode(UG_DRAGONBALL_REWARD_REQ, "UG_DRAGONBALL_REWARD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDragonBallRewardReq); //unsafe because shenron could have already despawned due to time out 
	StoreOpcode(UG_TIMEQUEST_ENTER_REQ, "UG_TIMEQUEST_ENTER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTimeQuestEnterReq); //unsafe
	StoreOpcode(UG_RANKBATTLE_INFO_REQ, "UG_RANKBATTLE_INFO_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvRankBattleInfoReq);
	StoreOpcode(UG_RANKBATTLE_JOIN_REQ, "UG_RANKBATTLE_JOIN_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvJoinRankBattleReq); //unsafe entering rankbattle
	StoreOpcode(UG_RANKBATTLE_LEAVE_REQ, "UG_RANKBATTLE_LEAVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvLeaveRankBattleReq); //unsafe leaving rank battle
	StoreOpcode(UG_PORTAL_ADD_REQ, "UG_PORTAL_ADD_REQ", PROCESS_INPLACE, &CClientSession::RecvPortalAddReq);
	StoreOpcode(UG_PORTAL_REQ, "UG_PORTAL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPortalReq);
	StoreOpcode(UG_PRIVATESHOP_CREATE_REQ, "UG_PRIVATESHOP_CREATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCreatePrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_EXIT_REQ, "UG_PRIVATESHOP_EXIT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvExitPrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_OPEN_REQ, "UG_PRIVATESHOP_OPEN_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvOpenPrivateShopReq); //should this really be thread-unsafe?
	StoreOpcode(UG_PRIVATESHOP_CLOSE_REQ, "UG_PRIVATESHOP_CLOSE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvClosePrivateShopReq); //should this really be thread-unsafe?
	StoreOpcode(UG_PRIVATESHOP_ITEM_UPDATE_REQ, "UG_PRIVATESHOP_ITEM_UPDATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemUpdatePrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_ITEM_INSERT_REQ, "UG_PRIVATESHOP_ITEM_INSERT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemInsertPrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_ITEM_DELETE_REQ, "UG_PRIVATESHOP_ITEM_DELETE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemDeletePrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_ITEM_BUYING_REQ, "UG_PRIVATESHOP_ITEM_BUYING_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBuyItemPrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_ENTER_REQ, "UG_PRIVATESHOP_ENTER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvEnterPrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_LEAVE_REQ, "UG_PRIVATESHOP_LEAVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvLeavePrivateShopReq);
	StoreOpcode(UG_PRIVATESHOP_ITEM_SELECT_REQ, "UG_PRIVATESHOP_ITEM_SELECT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvSelectItemPrivateShopReq);
	StoreOpcode(UG_MAIL_START_REQ, "UG_MAIL_START_REQ", PROCESS_INPLACE, &CClientSession::RecvMailStartReq);
	StoreOpcode(UG_MAIL_SEND_REQ, "UG_MAIL_SEND_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMailSendReq);
	StoreOpcode(UG_MAIL_READ_REQ, "UG_MAIL_READ_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMailReadReq);
	StoreOpcode(UG_MAIL_DEL_REQ, "UG_MAIL_DEL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMailDelReq);
	StoreOpcode(UG_MAIL_RETURN_REQ, "UG_MAIL_RETURN_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharMailReturnReq);
	StoreOpcode(UG_MAIL_RELOAD_REQ, "UG_MAIL_RELOAD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMailReloadReq);
	StoreOpcode(UG_MAIL_LOAD_REQ, "UG_MAIL_LOAD_REQ", PROCESS_INPLACE, &CClientSession::RecvMailLoadReq);
	StoreOpcode(UG_MAIL_ITEM_RECEIVE_REQ, "UG_MAIL_ITEM_RECEIVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMailItemReceiveReq);
	StoreOpcode(UG_MAIL_LOCK_REQ, "UG_MAIL_LOCK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMailLockReq);
	StoreOpcode(UG_MAIL_MULTI_DEL_REQ, "UG_MAIL_MULTI_DEL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharMailMultiDelReq);
	StoreOpcode(UG_WAR_FOG_UPDATE_REQ, "UG_WAR_FOG_UPDATE_REQ", PROCESS_INPLACE, &CClientSession::RecvWarFogUpdateReq);
	StoreOpcode(UG_GUILD_FUNCTION_ADD_REQ, "UG_GUILD_FUNCTION_ADD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvAddGuildFunctionReq);
	StoreOpcode(UG_GUILD_GIVE_ZENNY, "UG_GUILD_GIVE_ZENNY", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildGiveZeniReq);
	StoreOpcode(UG_GUILD_BANK_START_REQ, "UG_GUILD_BANK_START_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildBankStartReq);
	StoreOpcode(UG_GUILD_BANK_MOVE_REQ, "UG_GUILD_BANK_MOVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildBankMoveReq);
	StoreOpcode(UG_GUILD_BANK_MOVE_STACK_REQ, "UG_GUILD_BANK_MOVE_STACK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildBankMoveStackReq);
	StoreOpcode(UG_GUILD_BANK_END_REQ, "UG_GUILD_BANK_END_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildBankEndReq);
	StoreOpcode(UG_GUILD_BANK_ZENNY_REQ, "UG_GUILD_BANK_ZENNY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildBankZeniReq);
	StoreOpcode(UG_GUILD_CREATE_MARK_REQ, "UG_GUILD_CREATE_MARK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildCreateMarkReq);
	StoreOpcode(UG_GUILD_CHANGE_MARK_REQ, "UG_GUILD_CHANGE_MARK_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildChangeMarkReq);
	StoreOpcode(UG_CROSSFIRE_REQ, "UG_CROSSFIRE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCrossfireReq);
	StoreOpcode(UG_BANK_LOAD_REQ, "UG_BANK_LOAD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBankLoadReq);
	StoreOpcode(UG_GUILD_CHANGE_NAME_REQ, "UG_GUILD_CHANGE_NAME_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGuildChangeNameReq);
	StoreOpcode(UG_PARTY_SHARETARGET_REQ, "UG_PARTY_SHARETARGET_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyShareTargetReq);
	StoreOpcode(UG_RIDE_ON_BUS_REQ, "UG_RIDE_ON_BUS_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvRideOnBusReq);
	StoreOpcode(UG_RIDE_OFF_BUS_REQ, "UG_RIDE_OFF_BUS_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvRideOffBusReq);
	StoreOpcode(UG_TRANSFORM_CANCEL_REQ, "UG_TRANSFORM_CANCEL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCancelTransformationReq);	//UNSAFE BECAUSE TRANSFORM CAN END IN SYSTEM WHILE RECEIVE PACKET
	StoreOpcode(UG_SHOP_ITEM_IDENTIFY_REQ, "UG_SHOP_ITEM_IDENTIFY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvShopIdentifyItemReq);
	StoreOpcode(UG_DICE_ROLL_REQ, "UG_DICE_ROLL_REQ", PROCESS_INPLACE, &CClientSession::RecvRollDiceReq);
	StoreOpcode(UG_BUDOKAI_JOIN_INFO_REQ, "UG_BUDOKAI_JOIN_INFO_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiJoinInfoReq);
	StoreOpcode(UG_BUDOKAI_JOIN_STATE_REQ, "UG_BUDOKAI_JOIN_STATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiJoinStateReq);
	StoreOpcode(UG_BUDOKAI_MUDOSA_INFO_REQ, "UG_BUDOKAI_MUDOSA_INFO_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiMudosaInfoReq);
	StoreOpcode(UG_BUDOKAI_MUDOSA_TELEPORT_REQ, "UG_BUDOKAI_MUDOSA_TELEPORT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiMudosaTeleportReq);
	StoreOpcode(UG_BUDOKAI_PARTY_MAKER_REQ, "UG_BUDOKAI_PARTY_MAKER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiPartyMakerReq);
	StoreOpcode(UG_BUDOKAI_SOCIAL_ACTION, "UG_BUDOKAI_SOCIAL_ACTION", PROCESS_INPLACE, &CClientSession::RecvBudokaiSocialAction);
	StoreOpcode(UG_BUDOKAI_PRIZEWINNER_NAME_REQ, "UG_BUDOKAI_PRIZEWINNER_NAME_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiPrizeWinnerNameReq);
	StoreOpcode(UG_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_REQ, "UG_BUDOKAI_GM_BUDOKAI_SERVER_ENTER_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);	//NOT EXIST YET
	StoreOpcode(UG_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_REQ, "UG_BUDOKAI_GM_BUDOKAI_SERVER_LEAVE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);	//NOT EXIST YET
	StoreOpcode(UG_BUDOKAI_GM_MATCH_PROGRESS_INFO_REQ, "UG_BUDOKAI_GM_MATCH_PROGRESS_INFO_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);	//NOT EXIST YET
	StoreOpcode(UG_BUDOKAI_GM_MATCH_ARENA_ENTER_REQ, "UG_BUDOKAI_GM_MATCH_ARENA_ENTER_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);	//NOT EXIST YET
	StoreOpcode(UG_BUDOKAI_GM_MATCH_ARENA_LEAVE_REQ, "UG_BUDOKAI_GM_MATCH_ARENA_LEAVE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);	//NOT EXIST YET
	StoreOpcode(UG_BUDOKAI_JOIN_TEAM_INFO_REQ, "UG_BUDOKAI_JOIN_TEAM_INFO_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiJoinTeamInfoReq);
	StoreOpcode(UG_BUDOKAI_JOIN_TEAM_REQ, "UG_BUDOKAI_JOIN_TEAM_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiJoinTeamReq);
	StoreOpcode(UG_BUDOKAI_LEAVE_TEAM_REQ, "UG_BUDOKAI_LEAVE_TEAM_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiLeaveTeamReq);
	StoreOpcode(UG_BUDOKAI_LEAVE_TEAM_MEMBER_REQ, "UG_BUDOKAI_LEAVE_TEAM_MEMBER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiLeaveTeamMemberReq);
	StoreOpcode(UG_BUDOKAI_JOIN_INDIVIDUAL_REQ, "UG_BUDOKAI_JOIN_INDIVIDUAL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiJoinIndividualReq);
	StoreOpcode(UG_BUDOKAI_LEAVE_INDIVIDUAL_REQ, "UG_BUDOKAI_LEAVE_INDIVIDUAL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBudokaiLeaveIndividualReq);
	StoreOpcode(UG_SHOP_EVENTITEM_START_REQ, "UG_SHOP_EVENTITEM_START_REQ", PROCESS_INPLACE, &CClientSession::RecvEventItemShopReq);
	StoreOpcode(UG_SHOP_EVENTITEM_BUY_REQ, "UG_SHOP_EVENTITEM_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBuyEventItemShopReq);
	StoreOpcode(UG_SHOP_EVENTITEM_END_REQ, "UG_SHOP_EVENTITEM_END_REQ", PROCESS_INPLACE, &CClientSession::RecvEndEventItemShopReq);
	StoreOpcode(UG_SHOP_GAMBLE_BUY_REQ, "UG_SHOP_GAMBLE_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvSendGambleBuyReq);
	StoreOpcode(UG_PARTY_DIFF_CHANGE_REQ, "UG_PARTY_DIFF_CHANGE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyChangeDiffReq);
	StoreOpcode(UG_PARTY_DUNGEON_INIT_REQ, "UG_PARTY_DUNGEON_INIT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvInitPartyDungeonReq);
	StoreOpcode(UG_VEHICLE_DIRECT_PLAY_CANCEL_NFY, "UG_VEHICLE_DIRECT_PLAY_CANCEL_NFY", PROCESS_INPLACE, &CClientSession::RecvCancelVehicleDirectPlayNfy);
	StoreOpcode(UG_VEHICLE_END_REQ, "UG_VEHICLE_END_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvEndVehicleReq);
	StoreOpcode(UG_VEHICLE_STUNT_NFY, "UG_VEHICLE_STUNT_NFY", PROCESS_INPLACE, &CClientSession::RecvVehicleStuntNfy);
	StoreOpcode(UG_VEHICLE_FUEL_REMOVE_NFY, "UG_VEHICLE_FUEL_REMOVE_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvVehicleFuelRemoveNfy);
	StoreOpcode(UG_SKILL_INIT_REQ, "UG_SKILL_INIT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvSkillInitReq);
	StoreOpcode(UG_SKILL_RESET_PLUS_REQ, "UG_SKILL_RESET_PLUS_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvSkillResetPlusReq);
	StoreOpcode(UG_TELEPORT_CONFIRM_REQ, "UG_TELEPORT_CONFIRM_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvTeleportConfirmationReq);
	StoreOpcode(UG_HOIPOIMIX_ITEM_CREATE_REQ, "UG_HOIPOIMIX_ITEM_CREATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvHoiPoiItemCreateReq);
	StoreOpcode(UG_ITEM_DISASSEMBLE_REQ, "UG_ITEM_DISASSEMBLE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemDisassembleReq);
	StoreOpcode(UG_CASHITEM_MOVE_REQ, "UG_CASHITEM_MOVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCashItemMoveReq);
	StoreOpcode(UG_CASHITEM_USE_REQ, "UG_CASHITEM_USE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCashItemUseReq);
	StoreOpcode(UG_CASHITEM_HLSHOP_START_REQ, "UG_CASHITEM_HLSHOP_START_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCashItemHlsStartReq);
	StoreOpcode(UG_CASHITEM_HLSHOP_END_REQ, "UG_CASHITEM_HLSHOP_END_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCashItemHlsEndReq);
	StoreOpcode(UG_CASHITEM_HLSHOP_REFRESH_REQ, "UG_CASHITEM_HLSHOP_REFRESH_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCashItemHlsRefreshReq);
	StoreOpcode(UG_CASHITEM_BUY_REQ, "UG_CASHITEM_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCashItemBuyReq);
	StoreOpcode(UG_CASHITEM_SEND_GIFT_REQ, "UG_CASHITEM_SEND_GIFT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCashItemSendGiftReq);
	StoreOpcode(UG_DOJO_CREATE_REQ, "UG_DOJO_CREATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDojoCreateReq);
	StoreOpcode(UG_DOJO_DELETE_REQ, "UG_DOJO_DELETE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDojoDeleteReq);
	StoreOpcode(UG_DOJO_FUNCTION_ADD_REQ, "UG_DOJO_FUNCTION_ADD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDojoFunctionAddReq);
	StoreOpcode(UG_DOGI_CREATE_REQ, "UG_DOGI_CREATE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_DOGI_CHANGE_REQ, "UG_DOGI_CHANGE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_GUILD_DOGI_CREATE_REQ, "UG_GUILD_DOGI_CREATE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_GUILD_DOGI_CHANGE_REQ, "UG_GUILD_DOGI_CHANGE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_DOJO_SCRAMBLE_REQ, "UG_DOJO_SCRAMBLE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDojoScrambleReq);
	StoreOpcode(UG_DOJO_SCRAMBLE_RESPONSE_REQ, "UG_DOJO_SCRAMBLE_RESPONSE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDojoScrambleResponseReq);
	StoreOpcode(UG_SHOP_NETPYITEM_START_REQ, "UG_SHOP_NETPYITEM_START_REQ", PROCESS_INPLACE, &CClientSession::RecvNetPyStartReq);
	StoreOpcode(UG_SHOP_NETPYITEM_BUY_REQ, "UG_SHOP_NETPYITEM_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvNetPyBuyReq);
	StoreOpcode(UG_SHOP_NETPYITEM_END_REQ, "UG_SHOP_NETPYITEM_END_REQ", PROCESS_INPLACE, &CClientSession::RecvNetPyEndReq);
	StoreOpcode(UG_WORLD_MAP_STATUS, "UG_WORLD_MAP_STATUS", PROCESS_THREADUNSAFE, &CClientSession::RecvWorldMapStatus);
	StoreOpcode(UG_DOJO_NPC_INFO_REQ, "UG_DOJO_NPC_INFO_REQ", PROCESS_INPLACE, &CClientSession::RecvDojoNpcInfoReq);
	StoreOpcode(UG_SKILL_CASTING_CANCELED_NFY, "UG_SKILL_CASTING_CANCELED_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvCancelSkillCastingNfy); //UNSAFE BECAUSE CASTING COULD FINISH WHILE PROCESS THIS PACKET
	StoreOpcode(UG_PET_ATTACK_TARGET_NFY, "UG_PET_ATTACK_TARGET_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvAttackTargetNfy);
	StoreOpcode(UG_DURATION_ITEM_BUY_REQ, "UG_DURATION_ITEM_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDurationItemBuyReq);
	StoreOpcode(UG_DURATION_RENEW_REQ, "UG_DURATION_RENEW_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemDurationRenewReq);
	StoreOpcode(UG_BUDOKAI_PRIZEWINNER_TEAM_NAME_REQ, "UG_BUDOKAI_PRIZEWINNER_TEAM_NAME_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid); // TO DO
	StoreOpcode(UG_GMT_UPDATE_REQ, "UG_GMT_UPDATE_REQ", PROCESS_INPLACE, &CClientSession::RecvGmtUpdateReq);
	StoreOpcode(UG_CHAR_LOC_AFTER_KNOCKDOWN_NFY, "UG_CHAR_LOC_AFTER_KNOCKDOWN_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvCharLocAfterKnockdown);
	StoreOpcode(UG_CHAR_LOC_AFTER_SLIDING_NFY, "UG_CHAR_LOC_AFTER_SLIDING_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvCharLocAfterSliding);
	StoreOpcode(UG_CHAR_LOC_AFTER_PUSH_NFY, "UG_CHAR_LOC_AFTER_PUSH_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvCharLocAfterPush);
	StoreOpcode(UG_SCS_CHECK_START_RES, "UG_SCS_CHECK_START_RES", PROCESS_THREADUNSAFE, &CClientSession::RecvScsCheckStartRes);
	StoreOpcode(UG_SCS_CHECK_RES, "UG_SCS_CHECK_RES", PROCESS_THREADUNSAFE, &CClientSession::RecvScsCheckRes);
	StoreOpcode(UG_SCS_REPLY_REQ, "UG_SCS_REPLY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvScsReplyReq);
	StoreOpcode(UG_SCS_REMAKE_REQ, "UG_SCS_REMAKE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvScsRemakeReq);
	StoreOpcode(UG_QUICK_TELEPORT_LOAD_REQ, "UG_QUICK_TELEPORT_LOAD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvLoadQuickTeleportReq);
	StoreOpcode(UG_QUICK_TELEPORT_UPDATE_REQ, "UG_QUICK_TELEPORT_UPDATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvUpdateQuickTeleportReq);
	StoreOpcode(UG_QUICK_TELEPORT_DEL_REQ, "UG_QUICK_TELEPORT_DEL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDelQuickTeleportReq);
	StoreOpcode(UG_QUICK_TELEPORT_USE_REQ, "UG_QUICK_TELEPORT_USE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvUseQuickTeleportReq);
	StoreOpcode(UG_CHAR_CRESCENT_POPO_REVIVAL_REQ, "UG_CHAR_CRESCENT_POPO_REVIVAL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCrescentPopoRevivalReq);
	StoreOpcode(UG_CHARACTER_RENAME_REQ, "UG_CHARACTER_RENAME_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharRenameReq);
	StoreOpcode(UG_CHAR_EXIT_REQ, "UG_CHAR_EXIT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharExitReq);
	StoreOpcode(UG_GAME_EXIT_REQ, "UG_GAME_EXIT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGameExitReq);
	StoreOpcode(UG_CHAR_AWAY_REQ, "UG_CHAR_AWAY_REQ", PROCESS_INPLACE, &CClientSession::RecvCharAwayReq);
	StoreOpcode(UG_CHAR_KEY_UPDATE_REQ, "UG_CHAR_KEY_UPDATE_REQ", PROCESS_INPLACE, &CClientSession::RecvShortcutKeyUpdateReq);
	StoreOpcode(UG_CHAR_DIRECT_PLAY_CANCEL, "UG_CHAR_DIRECT_PLAY_CANCEL", PROCESS_THREADUNSAFE, &CClientSession::RecvCharDirectPlayCancel);
	StoreOpcode(UG_CHAR_DIRECT_PLAY_ACK, "UG_CHAR_DIRECT_PLAY_ACK", PROCESS_THREADUNSAFE, &CClientSession::RecvCharDirectPlayAck);
	StoreOpcode(UG_CHAR_KNOCKDOWN_RELEASE_NFY, "UG_CHAR_KNOCKDOWN_RELEASE_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvCharKnockdownReleaseNfy);
	StoreOpcode(UG_CHAR_SKILL_REQ, "UG_CHAR_SKILL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvCharSkillReq);	//UNSAFE BECAUSE IT CAN ADD/REMOVE BUFFS
	StoreOpcode(UG_DRAGONBALL_SCRAMBLE_JOIN_REQ, "UG_DRAGONBALL_SCRAMBLE_JOIN_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDragonballScrambleJoinReq);
	StoreOpcode(UG_DRAGONBALL_SCRAMBLE_BALL_LOC_REQ, "UG_DRAGONBALL_SCRAMBLE_BALL_LOC_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDragonballScrambleBallLocReq);
	StoreOpcode(UG_CHAR_SKILL_INIT_REQ, "UG_CHAR_SKILL_INIT_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_GUILD_DOGI_DYE_REQ, "UG_GUILD_DOGI_DYE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_TENKAICHIDAISIJYOU_SELL_REQ, "UG_TENKAICHIDAISIJYOU_SELL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvSellAuctionHouseReq);
	StoreOpcode(UG_TENKAICHIDAISIJYOU_SELL_CANCEL_REQ, "UG_TENKAICHIDAISIJYOU_SELL_CANCEL_REQ", PROCESS_INPLACE, &CClientSession::RecvSellCancelAuctionHouseReq);
	StoreOpcode(UG_TENKAICHIDAISIJYOU_BUY_REQ, "UG_TENKAICHIDAISIJYOU_BUY_REQ", PROCESS_INPLACE, &CClientSession::RecvBuyAuctionHouseReq);
	StoreOpcode(UG_TENKAICHIDAISIJYOU_LIST_REQ, "UG_TENKAICHIDAISIJYOU_LIST_REQ", PROCESS_INPLACE, &CClientSession::RecvLoadAuctionHouseReq);
	StoreOpcode(UG_MASCOT_RING_ACTION_REQ, "UG_MASCOT_RING_ACTION_REQ", PROCESS_INPLACE, &CClientSession::RecvMascotRingActionReq);
	StoreOpcode(UG_MASCOT_RING_REMOVE_ALL_REQ, "UG_MASCOT_RING_REMOVE_ALL_REQ", PROCESS_INPLACE, &CClientSession::RecvMascotRingRemoveAllReq);
	StoreOpcode(UG_MASCOT_SUMMON_REQ_EX, "UG_MASCOT_SUMMON_REQ_EX", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotSummonReq);
	StoreOpcode(UG_MASCOT_UNSUMMON_REQ_EX, "UG_MASCOT_UNSUMMON_REQ_EX", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotUnsummonReq);
	StoreOpcode(UG_MASCOT_DELETE_REQ_EX, "UG_MASCOT_DELETE_REQ_EX", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotDelReq);
	StoreOpcode(UG_MASCOT_RING_MATERIAL_DISASSEMBLE_REQ, "UG_MASCOT_RING_MATERIAL_DISASSEMBLE_REQ", PROCESS_INPLACE, &CClientSession::RecvMascotRingMaterialDisassembleReq);
	StoreOpcode(UG_MASCOT_RING_ACTION_END_REQ, "UG_MASCOT_RING_ACTION_END_REQ", PROCESS_INPLACE, &CClientSession::RecvMascotRingActionEndReq);
	StoreOpcode(UG_REMOTE_SHOP_BUY_REQ, "UG_REMOTE_SHOP_BUY_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_REMOTE_SHOP_SELL_REQ, "UG_REMOTE_SHOP_SELL_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_REMOTE_ITEM_EQUIP_REPAIR_REQ, "UG_REMOTE_ITEM_EQUIP_REPAIR_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_REMOTE_ITEM_REPAIR_REQ, "UG_REMOTE_ITEM_REPAIR_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_REMOTE_SHOP_ITEM_IDENTIFY_REQ, "UG_REMOTE_SHOP_ITEM_IDENTIFY_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_WORLD_LAVA_ENTERED_NFY, "UG_WORLD_LAVA_ENTERED_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvLavaEnteredNfy);
	StoreOpcode(UG_WORLD_LAVA_LEFT_NFY, "UG_WORLD_LAVA_LEFT_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvLavaLeftNfy);
	StoreOpcode(UG_SKILL_ONE_RESET_REQ, "UG_SKILL_ONE_RESET_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvResetOneSkillReq);
	StoreOpcode(UG_ULTIMATE_DUNGEON_ENTER_REQ, "UG_ULTIMATE_DUNGEON_ENTER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvUltimateDungeonEnterReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_REGISTER_REQ, "UG_PARTY_MATCHING_REGISTER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingRegisterReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_JOIN_REQ, "UG_PARTY_MATCHING_JOIN_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingJoinReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_ROLEPLAY_REQ, "UG_PARTY_MATCHING_ROLEPLAY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingRoleplayReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_UNREGISTER_REQ, "UG_PARTY_MATCHING_UNREGISTER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingUnregisterReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_LIST_REQ, "UG_PARTY_MATCHING_LIST_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingListReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_INFO_REQ, "UG_PARTY_MATCHING_INFO_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingInfoReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_ENTER_DUNGEON_REQ, "UG_PARTY_MATCHING_ENTER_DUNGEON_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingEnterDungeonReq);	//UNSAFE
	StoreOpcode(UG_PARTY_MATCHING_ENTER_DUNGEON_AGREE_NFY, "UG_PARTY_MATCHING_ENTER_DUNGEON_AGREE_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecPartyMatchingEnterDungeonAgreeNfy);	//UNSAFE
	StoreOpcode(UG_DWC_WORLDCOUNT_INFO_REQ, "UG_DWC_WORLDCOUNT_INFO_REQ", PROCESS_INPLACE, &CClientSession::RecvDwcWorldCountInfoReq);
	StoreOpcode(UG_DWC_ENTER_REQ, "UG_DWC_ENTER_REQ", PROCESS_INPLACE, &CClientSession::RecvDwcWorldEnterReq);
	StoreOpcode(UG_DWC_ENTER_CONFIRM_REQ, "UG_DWC_ENTER_CONFIRM_REQ", PROCESS_INPLACE, &CClientSession::RecvDwcWorldEnterConfirmReq);
	StoreOpcode(UG_DWC_SCENARIO_INFO_REQ, "UG_DWC_SCENARIO_INFO_REQ", PROCESS_INPLACE, &CClientSession::RecvDwcScenarioInfoReq);
	StoreOpcode(UG_DWC_GET_REWARD_REQ, "UG_DWC_GET_REWARD_REQ", PROCESS_INPLACE, &CClientSession::RecvDwcGetRewardReq);
	StoreOpcode(UG_CHARTITLE_SELECT_REQ, "UG_CHARTITLE_SELECT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvSelectCharTitleReq);
	StoreOpcode(UG_TMQ_LIMIT_COUNT_PLUS_REQ, "UG_TMQ_LIMIT_COUNT_PLUS_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_PARTY_SELECT_STATE_REQ, "UG_PARTY_SELECT_STATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartySelectStateReq); //UNSAFE
	StoreOpcode(UG_BATTLE_DUNGEON_ENTER_REQ, "UG_BATTLE_DUNGEON_ENTER_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBattleDungeonEnterReq);	//UNSAFE
	StoreOpcode(UG_BATTLE_DUNGEON_LEAVE_REQ, "UG_BATTLE_DUNGEON_LEAVE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvBattleDungeonLeaveReq);	//UNSAFE
	StoreOpcode(UG_EVENT_REWARD_LOAD_REQ, "UG_EVENT_REWARD_LOAD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvEventRewardLoadReq);
	StoreOpcode(UG_EVENT_REWARD_SELECT_REQ, "UG_EVENT_REWARD_SELECT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvEventRewardSelectReq);
	StoreOpcode(UG_ITEM_UPGRADE_BY_COUPON_REQ, "UG_ITEM_UPGRADE_BY_COUPON_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemUpgradeByCouponReq);
	StoreOpcode(UG_VEHICLE_FUEL_INSERT_REQ, "UG_VEHICLE_FUEL_INSERT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvVehicleFuelInsertReq);
	StoreOpcode(UG_ITEM_EXCHANGE_REQ, "UG_ITEM_EXCHANGE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemExchangeReq);
	StoreOpcode(UG_ITEM_UPGRADED_EXCHANGE_REQ, "UG_ITEM_UPGRADED_EXCHANGE_REQ", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_ITEM_SEAL_REQ, "UG_ITEM_SEAL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemSealReq);
	StoreOpcode(UG_ITEM_SEAL_EXTRACT_REQ, "UG_ITEM_SEAL_EXTRACT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemSealExtractReq);
	StoreOpcode(UG_PARTY_CHANGE_ITEM_LOOTING_RANK_METHOD_REQ, "UG_PARTY_CHANGE_ITEM_LOOTING_RANK_METHOD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvPartyChangeItemLottingankMethodReq);
	StoreOpcode(UG_ITEM_DICE_REQ, "UG_ITEM_DICE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemDiceReq);
	StoreOpcode(UG_GIFT_SHOP_START_REQ, "UG_GIFT_SHOP_START_REQ", PROCESS_INPLACE, &CClientSession::RecvGiftShopStartReq);
	StoreOpcode(UG_GIFT_SHOP_BUY_REQ, "UG_GIFT_SHOP_BUY_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvGiftShopBuyReq);
	StoreOpcode(UG_ITEM_SOCKET_INSERT_BEAD_REQ, "UG_ITEM_SOCKET_INSERT_BEAD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemSocketInsertBeadReq);
	StoreOpcode(UG_ITEM_SOCKET_DESTROY_BEAD_REQ, "UG_ITEM_SOCKET_DESTROY_BEAD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemSocketDestroyBeadReq);
	StoreOpcode(UG_ITEM_CHAGE_BATTLE_ATTRIBUTE_REQ, "UG_ITEM_CHAGE_BATTLE_ATTRIBUTE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemChangeBattleAttributeReq);
	StoreOpcode(UG_INVISIBLE_COSTUME_UPDATE_REQ, "UG_INVISIBLE_COSTUME_UPDATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvInvisibleCostumeUpdateReq);
	StoreOpcode(UG_INVENTORY_SORT_REQ, "UG_INVENTORY_SORT_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvInventorySortReq);
	StoreOpcode(UG_ITEM_CHANGE_OPTION_REQ, "UG_ITEM_CHANGE_OPTION_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvItemChangeOptionReq);
	StoreOpcode(UG_DYNAMIC_FIELD_SYSTEM_BOSS_POSITION_REQ, "UG_DYNAMIC_FIELD_SYSTEM_BOSS_POSITION_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvDynamicFieldSystemBossPositionReq); //ASYNC BECAUSE SCRIPT MIGHT GET DELETED WHILE PROCESSING PACKET
	StoreOpcode(UG_CHAR_AIR_MOVE, "UG_CHAR_AIR_MOVE", PROCESS_THREADUNSAFE, &CClientSession::RecvCharAirMove);
	StoreOpcode(UG_CHAR_AIR_JUMP, "UG_CHAR_AIR_JUMP", PROCESS_THREADUNSAFE, &CClientSession::RecvCharAirJump);
	StoreOpcode(UG_CHAR_AIR_DASH, "UG_CHAR_AIR_DASH", PROCESS_THREADUNSAFE, &CClientSession::RecvCharDashAir);
	StoreOpcode(UG_CHAR_AIR_ACCEL, "UG_CHAR_AIR_ACCEL", PROCESS_THREADUNSAFE, &CClientSession::RecvCharAirAccel);
	StoreOpcode(UG_CHAR_AIR_FALLING, "UG_CHAR_AIR_FALLING", PROCESS_THREADUNSAFE, &CClientSession::RecvCharAirFalling);
	StoreOpcode(UG_CHAR_AIR_END, "UG_CHAR_AIR_END", PROCESS_THREADUNSAFE, &CClientSession::RecvCharAirEnd);
	StoreOpcode(UG_CHAR_AIR_FOLLOW_MOVE, "UG_CHAR_AIR_FOLLOW_MOVE", PROCESS_THREADUNSAFE, &CClientSession::RecvCharAirFollowMove);
	StoreOpcode(UG_PET_ATTACK_TOGGLE_NFY, "UG_PET_ATTACK_TOGGLE_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvPetAttackToggleNfy);
	StoreOpcode(UG_PET_SKILL_TOGGLE_NFY, "UG_PET_SKILL_TOGGLE_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvPetSkillToggleNfy);
	StoreOpcode(UG_PET_RECALL_NFY, "UG_PET_RECALL_NFY", PROCESS_INPLACE, &CClientSession::OnInvalid);
	StoreOpcode(UG_MASCOT_FUSION_REQ, "UG_MASCOT_FUSION_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotFusionReq);
	StoreOpcode(UG_MASCOT_SKILL_ADD_REQ, "UG_MASCOT_SKILL_ADD_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotSkillAddReq);
	StoreOpcode(UG_MASCOT_SKILL_UPDATE_REQ, "UG_MASCOT_SKILL_UPDATE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotSkillUpdateReq);
	StoreOpcode(UG_MASCOT_SKILL_UPGRADE_REQ, "UG_MASCOT_SKILL_UPGRADE_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotSkillUpgradeReq);
	StoreOpcode(UG_MASCOT_SKILL_REQ, "UG_MASCOT_SKILL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotSkillReq);
	StoreOpcode(UG_MASCOT_AUTO_LOOTING_REQ, "UG_MASCOT_AUTO_LOOTING_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotAutoLootingReq);					//ASYNC BECAUSE ITEM CAN BE REMOVED BY SYSTEM WHILE TRY PICK IT UP
	StoreOpcode(UG_MASCOT_REMOTE_SHOP_SELL_REQ, "UG_MASCOT_REMOTE_SHOP_SELL_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotRemoteShopSellReq);
	StoreOpcode(UG_MASCOT_SEAL_SET_REQ, "UG_MASCOT_SEAL_SET_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotSealSetReq);
	StoreOpcode(UG_MASCOT_SEAL_CLEAR_REQ, "UG_MASCOT_SEAL_CLEAR_REQ", PROCESS_THREADUNSAFE, &CClientSession::RecvMascotSealClearReq);
	StoreOpcode(UG_CLIENT_INFO_NFY, "UG_CLIENT_INFO_NFY", PROCESS_THREADUNSAFE, &CClientSession::RecvClientInfoNfy);

}


