//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ModelTool2.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_TOON_MORE                    101
#define ID_TOON_SELECTOR                102
#define IDD_CLUMPPANE                   103
#define IDR_PANE_TREEITEM               103
#define IDD_MATERIALPANE                104
#define IDR_PANE_ENVMAP                 104
#define IDD_ANIMSETPANE                 105
#define IDR_PANE_LINKEFFECT             105
#define IDD_ATTACKTYPEPANE              106
#define IDR_PANE_ITEMVIEW               106
#define IDD_BONEEDITPANE                107
#define IDR_PANE_NPC                    107
#define IDD_ANIMPLAYPANE                108
#define IDR_PANE_TREENPC                108
#define IDD_EVENTPROPERY                109
#define ID_HEAD_SKIN_SELECT             109
#define IDD_PROPERTYPANE                110
#define ID_BODY_SKIN_SELECT             110
#define IDR_PANE_TREEVEHICLE            111
#define IDD_BBOXPANE                    112
#define IDR_PANE_NAVI                   112
#define IDD_TREEOBJECTPANE              113
#define IDR_PANE_VEHICLEVIEW            113
#define IDD_DUMMYMODELPANE              114
#define IDD_ITEMPANE                    115
#define IDD_TREEITEMPANE                116
#define IDD_ENVMAPPANE                  117
#define IDD_LINKEFFECTPANE              118
#define IDD_ITEMVIEWPANE                119
#define IDD_NAVIMESHPANE                122
#define IDD_VEHICLEVIEWPANE             123
#define IDR_MAINFRAME                   128
#define IDR_ModelTool2TYPE              129
#define IDB_BITMAP_ICONS                130
#define IDI_ICON_SCRIPT                 132
#define IDI_ICON_CLOSE                  133
#define IDI_ICON_OPEN                   134
#define IDR_MENU_POPUP                  135
#define IDI_ICON_OBJECT                 143
#define IDI_ICON_OBJECT_SCRIPT          144
#define IDC_CURSOR1                     145
#define IDR_TOOLBAR1                    146
#define IDR_MENU_HIDDEN                 148
#define IDI_ICON_ITEM                   149
#define IDR_TOOLBAR2                    152
#define ID_HEADSKIN_MORE                154
#define ID_BODYSKIN_MORE                155
#define IDD_CONVERTDLG                  155
#define IDC_FRAME_ATOMIC                1001
#define IDC_EDIT_NAME                   1002
#define IDC_LT_ANIM_ITEM                1003
#define IDC_EDIT_SIZE                   1003
#define IDC_FRAME_MATERIAL              1004
#define IDC_LT_ANIM_ITEM2               1004
#define IDC_BT_ANIM_PLAY                1004
#define IDC_STATIC2                     1005
#define IDC_BT_ANIM_STOP                1005
#define IDC_ED_TIME                     1006
#define IDC_ED_SPEED                    1007
#define IDC_STATIC_X                    1008
#define IDC_CB_EVENT                    1010
#define IDC_STATIC_MULTI_TEXTURE        1011
#define IDC_ST_SIZE                     1012
#define IDC_ST_NAME                     1013
#define IDC_TREE_SCRIPT                 1015
#define IDC_EDIT13                      1016
#define IDC_TREE_RESOURCE               1016
#define IDC_BT_BONE_PREV                1017
#define IDC_STATIC_SCRIPT               1017
#define IDC_BT_BONE_NEXT                1018
#define IDC_STATIC_RESOURCE             1018
#define IDC_STATIC_TOON                 1019
#define IDC_STATIC_RENDER               1020
#define IDC_CB_BONE                     1021
#define IDC_BONE_MOVE                   1022
#define IDC_EDIT_FILENAME               1022
#define IDC_CHECK_VISIBLE               1023
#define IDC_EDIT_POSX                   1024
#define IDC_EDIT_POSY                   1025
#define IDC_CK_NORM_MAP                 1025
#define IDC_CK_ENV_MAP                  1026
#define IDC_ED_ENV_MAP                  1027
#define IDC_SL_SHINE                    1028
#define IDC_ED_DAMAGE00                 1029
#define IDC_CB_EFFECT                   1029
#define IDC_ED_DAMAGE01                 1030
#define IDC_LIST_EFFECT                 1030
#define IDC_ED_DAMAGE02                 1031
#define IDC_TREE_ITEM                   1031
#define IDC_ED_DAMAGE03                 1032
#define IDC_CHECK_ITEM                  1032
#define IDC_ED_DAMAGE04                 1033
#define IDC_STATIC_COLLISION            1033
#define IDC_ED_DAMAGE05                 1034
#define IDC_CHECK_COLLISION             1034
#define IDC_ED_DAMAGE06                 1035
#define IDC_CHECK_NOT_VISIBLE           1035
#define IDC_ED_DAMAGE07                 1036
#define IDC_PROG                        1036
#define IDC_CHECK_DECAL_VISIBLE         1036
#define IDC_RA_PHYSICAL                 1037
#define IDC_MSG                         1037
#define IDC_CHECK_CAMERA_COLLISION      1037
#define IDC_ED_DAMAGE08                 1039
#define IDC_EDIT1                       1039
#define IDC_ED_FRUSTUM                  1039
#define IDC_ED_DAMAGE09                 1040
#define IDC_COMBO1                      1040
#define IDC_STT_FRUSTUM                 1041
#define IDC_CB_ENV                      1042
#define IDC_ST_ENV_ATOMIC               1043
#define IDC_ST_ENV_TEXTURE              1044
#define IDC_CK_2SIDE                    1045
#define IDC_LIST_NAVI                   1045
#define IDC_CK_2SIDE_EDGE               1046
#define IDC_ST_NAVI                     1046
#define IDC_CHECK_ALPHA                 1047
#define IDC_ST_OBS                      1047
#define IDC_CHECK_ALPHA2                1048
#define IDC_RE_LOG                      1048
#define IDC_CHECK_ALPHA3                1049
#define IDC_TREE_VEHICLE                1049
#define IDC_CHECK_SHADOWMAP             1050
#define IDC_ED_DAMAGE10                 1051
#define IDC_CHECK_ALPHA4                1051
#define IDC_CHECK_EMBLEM_MARK           1051
#define IDC_ED_DAMAGE11                 1052
#define IDC_STATIC_GROUP                1052
#define IDC_ED_DAMAGE12                 1053
#define IDC_ED_DAMAGE13                 1054
#define IDC_ED_DAMAGE14                 1055
#define IDC_ED_DAMAGE15                 1056
#define IDC_SLIDER                      1064
#define IDC_LIST_MATERIAL               1069
#define IDC_EDIT_CLUMP_NAME             1076
#define IDC_LIST_ATOMIC                 1077
#define IDC_BT_DELETE                   1078
#define IDC_LIST_OBS                    1078
#define IDC_BT_CLUMP_SAVE               1079
#define IDC_BT_CLUMP_SAVE_ALL           1080
#define IDC_BT_SAVECLUMP                1081
#define IDC_EDIT_ENVMAP                 1082
#define IDC_BT_MATERIAL_ADD             1084
#define IDC_BT_MATERIAL_DEL             1085
#define IDC_ET_SENSE                    1086
#define IDC_CB_ANIM_SET                 1093
#define IDC_CK_BONE_EDIT                1097
#define IDC_ST_SCALE_X                  1098
#define IDC_ST_SCALE_Y                  1099
#define IDC_ST_SCALE_Z                  1100
#define IDC_CK_BONE_EDIT2               1101
#define IDC_ED_BONE_LENGTH              1102
#define IDC_ED_BONE_WIDTH               1103
#define IDC_ED_BONE_LENGTH2             1104
#define IDC_RA_ENERGY                   1120
#define IDC_SPIN1                       1121
#define IDC_SPIN2                       1122
#define IDC_SPIN3                       1123
#define IDC_SPIN4                       1124
#define IDC_SPIN5                       1125
#define IDC_SPIN_ANIM_SPEED             1130
#define IDR_PANE_OPTIONS                4000
#define IDR_PANE_PROPERTIES             4001
#define IDR_PANE_CLUMP                  4002
#define IDR_PANE_MATERIAL               4003
#define IDR_PANE_ANIMSET                4004
#define IDR_PANE_ATTACKTYPE             4005
#define IDR_PANE_BONEEDIT               4006
#define IDR_PANE_ANIMPLAY               4007
#define IDR_PANE_PROPERTY               4008
#define IDR_PANE_TREEPC                 4009
#define IDR_PANE_BBOX                   4010
#define IDR_PANE_TREEMOB                4011
#define IDR_PANE_TREEOBJECT             4012
#define IDR_PANE_DUMMY                  4013
#define ID_FOLDER_NEWFOLDER             32771
#define ID_FOLDER_NEWSCRIPT             32772
#define ID_MENU_ADD_FOLDER              32773
#define ID_MENU_NEW_SCRIPT              32774
#define ID_MENU_LOAD_SCRIPT             32775
#define ID_MENU_RENAME_FOLDER           32776
#define ID_MENU_DELETE_FOLDER           32777
#define ID_MENU_SCRIPT_SAVE             32778
#define ID_MENU_SCRIPT_SAVEAS           32779
#define ID_MENU_SCRIPT_RENAME           32780
#define ID_MENU_DELETE_SCRIPT           32781
#define ID_MENU_ANIM_SET                32782
#define ID_MENU_ANIM_DELETE             32783
#define ID_SCRIPT_SETCLUMP              32784
#define ID_SCRIPT_SETCLUMP32785         32785
#define ID_VIEW_VIEWWORLD               32786
#define ID_VIEW_VIEWHEIRARCHY           32787
#define ID_VIEW_VIEWWIREFRAME           32788
#define ID_VIEW_VIEWBBOX                32789
#define ID_PANE                         32797
#define ID_PANE_PCTREE                  32798
#define ID_PANE_MOBTREE                 32799
#define ID_PANE_CLUMPEDIT               32800
#define ID_PANE_MATERIALEDIT            32801
#define ID_PANE_ANIMATIONSET            32802
#define ID_PANE_ATTACKTYPE              32803
#define ID_PANE_ANIMATIONPLAY           32804
#define ID_PANE_BONEEDIT                32805
#define ID_PANE_BBOXEDIT                32806
#define ID_PANE_EVENTPROPERTIES         32807
#define ID_SCRIPT_SAVEALL               32808
#define ID_CAMERA_LEFTVIEW              32809
#define ID_CAMERA_FRONTVIEW             32810
#define ID_CAMERA_TOPVIEW               32811
#define ID_OBJECTRESOURCE_EXPORTTOSCRIPT 32821
#define ID_OBJECTRESOURCE_EXPROTALLTOSCRIPT 32822
#define ID_OBJECTSCRIPT                 32823
#define ID_OBJECTFOLDER_NEWFOLDER       32824
#define ID_OBJECTFOLDER_RENAME          32825
#define ID_OBJECTFOLDER_IMPORTSCRIPT    32826
#define ID_OBJECTSCRIPT_RENAME          32827
#define ID_OBJECTSCRIPT_DELETE          32828
#define ID_OBJECTFOLDER_DELETE          32829
#define ID_PANE_OBJECTTREE              32830
#define ID_OBJECTSCRIPT_SAVE            32831
#define ID_OBJECTSCRIPT_SAVEAS          32832
#define ID_OBJECTSCRIPT_SAVEALL         32833
#define ID_PANE_DUMMYMODEL              32834
#define ID_OBJECTFOLDER_SAVETREE        32835
#define ID_TOOL_CAMERA_SENSE            32836
#define ID_CAMERA_REARVIEW              32841
#define ID_CAMERA_RIGHTVIEW             32842
#define ID_CAMERA_BOTTOMVIEW            32843
#define ID_VIEW_VIEWTOONEDGE            32844
#define ID_TOOL_THICKNESS_ICON          32846
#define ID_TOOL_THICKNESS               32847
#define ID_TOOLBAR_CAMRAICON            32848
#define ID_TOOLBAR_THICKNESSICON        32849
#define ID_TOOL_TOONCOLOR               32850
#define ID_ITEMRESOURCE_EXPORTTOSCRIPT  32851
#define ID_ITEMFOLDER_NEWFOLDER         32852
#define ID_ITEMFOLDER_RENAME            32853
#define ID_ITEMFOLDER_IMPORTSCRIPT      32854
#define ID_ITEMFOLDER_SAVETREE          32855
#define ID_ITEMFOLDER_DELETE            32856
#define ID_ITEMSCRIPT_SAVE              32857
#define ID_ITEMSCRIPT_SAVEAS            32858
#define ID_ITEMSCRIPT_SAVEALL           32859
#define ID_ITEMSCRIPT_RENAME            32860
#define ID_ITEMSCRIPT_DELETE            32861
#define ID_PANE_ITEMTREEE               32862
#define ID_PANE_ENVIROMENTMAP           32863
#define ID_OPTION_HITEFFECT             32864
#define ID_PANE_ITEMVIEW                32865
#define ID_PANE_NPCTREE                 32868
#define ID_FILE_EDIT                    32869
#define ID_FILE_PASTE                   32870
#define ID_OPTION_OBJECTCOLLISIONBOX    32871
#define ID_OPTION_COLLISIONMESH         32872
#define ID_TOOLBAR_HEADSKINCOLOR        32873
#define ID_TOOLBAR_BODYSKINCOLOR        32874
#define ID_OPTION_ITEMGRADEEFFECT       32875
#define ID_ITEMGRADEEFFECT_NONE         32876
#define ID_ITEMGRADEEFFECT_1            32877
#define ID_ITEMGRADEEFFECT_2            32878
#define ID_ITEMGRADEEFFECT_3            32879
#define ID_ITEMGRADEEFFECT_4            32880
#define ID_OPTION_GLOWFILTER            32881
#define ID_OPTION_BLURFILTER            32882
#define ID_OPTION_FRAMEFIX              32883
#define ID_FILE_CONVERTBINARY           32884
#define ID_FILE_CONVERTENCRYPTBINARY    32885
#define ID_OBJECTSCRIPT_OVERWRITEALL    32886
#define ID_ITEMSCRIPT_OVERWRITEALL      32887
#define ID_CAMERA_FREECAMERA            32888
#define ID_OPTION_CAMERADISTANCEALPHA   32889
#define ID_FILE_UPDATEENTITYDATA        32890
#define ID_FILE_UPDATEPROPERTYDATA      32891
#define ID_PANE_VEHICLEVIEW             32892
#define ID_OPTION_CAMERASHAKEDISABLE    32893

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32894
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           124
#endif
#endif
