#ifndef __NTLWORLDPALETTEDEFINE_H__
#define __NTLWORLDPALETTEDEFINE_H__


enum eMAP_EDIT_MODE
{
	eMEM_RAISE = 0,
	eMEM_DROP,
	eMEM_PLATEAU,
	eMEM_JUST,
	eMEM_STANDARDIZE,
	eMEM_SMOOTH,
	eMEM_CUSTOMIZE,
	eMEM_CUSTOMIZE_E,
	eMEM_SLOPE,
	eMEM_SMOOTH_RANGE,
	eMEM_ROAD,
	eMEM_NUM
};

enum eWATER_EDIT_MODE
{
	eWEM_IDLE = 0,
	eWEM_EDIT,
	eWEM_MOVE,
	eWEM_NUM
};

enum eOBJ_EDIT_MODE
{
	eOEM_IDLE = 0,
	eOEM_PLACE,
	eOEM_EDIT,
	eOEM_MOVE,
	eOEM_NUM
};

enum eSPAWN_EDIT_MODE
{
	eSEM_IDLE = 0,
	eSEM_PLACE,
	eSEM_EDIT,
	eSEM_NUM
};

enum ePALETTE_MODE
{
	ePM_DEFAULT = 0,
	ePM_TERRAIN,
	ePM_TEXTURE,
	ePM_DIFFUSE,
	ePM_ORNAMENT,
	ePM_FIELDUI,
	ePM_WATER,
	ePM_SHADOW,
	ePM_EFFECT,
	ePM_NM_PROP,
	ePM_SE,
	ePM_UNIT,
	ePM_REGION,
	ePM_TRIGGER,
	ePM_SPAWN,
	// CZ-SS
	//ePM_SOFTSPOT,
	ePM_PERFORMANCE_SECTORCULL,
	ePM_PERFORMANCE_OCCLUSION,
	ePM_PERFORMANCE_PVS,
	ePM_PERFORMANCE_IMPOSTER,
	ePM_SHORE_LINE,
	ePM_DECAL,
	ePM_PLANT,
	ePM_WORLDLIGHT,
	ePM_HEATHAZE,
	ePM_LIGHTOBJECT,
	ePM_LIGHTMODE,
	ePM_GAMEPROPERTY,
	ePM_SKYFLOATING, // 인도어에서는 FIELDUI를 사용하지 않기 때문에 SKYFLOATING PALETTE_MODE가 필요하다.
	ePM_DECAL_VOLUME,
	ePM_DOJO,
};

extern ePALETTE_MODE g_PaletteMode;
#define dGET_CUR_PALETTE() (g_PaletteMode)

extern eMAP_EDIT_MODE g_MapEditMode;
#define dGET_TERRAIN_MODE() (g_MapEditMode)

extern eOBJ_EDIT_MODE g_ObjEditMode;
#define dGET_MAPOBJ_MODE() (g_ObjEditMode)

extern eSPAWN_EDIT_MODE g_SpawnEditMode;
#define dGET_SPAWN_MODE() (g_SpawnEditMode)

extern eWATER_EDIT_MODE g_WaterEditMode;
#define dGET_WATER_MODE() (g_WaterEditMode)


#endif __NTLWORLDPALETTEDEFINE_H__