//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NtlWE.rc
//
#define ID_LOAD_RAW                     3
#define IDCLEAR                         3
#define ID_GETPROP                      3
#define ID_SETPROP                      4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MENU_OUTDOOR                128
#define IDR_NtlWETYPE                   129
#define IDD_FILE_NEW                    130
#define IDI_ICON1                       132
#define IDD_CAMERA_ATTR_DLG             133
#define IDD_CAMERA_ATTR                 133
#define IDC_DIFFUSE_PICKER_B            134
#define IDD_ORNAMENT                    135
#define IDD_UNIT                        136
#define IDD_REGION                      137
#define IDD_TRIGGER                     138
#define IDB_JUSTD                       152
#define IDB_JUSTU                       153
#define IDB_LOWERD                      154
#define IDB_LOWERU                      155
#define IDB_STANDARDIZED                156
#define IDB_STANDARDIZEU                157
#define IDB_PLATEAUD                    158
#define IDB_PLATEAUU                    159
#define IDB_RAISED                      160
#define IDB_RAISEU                      161
#define IDB_SMOOTHD                     162
#define IDB_SMOOTHU                     163
#define IDB_CUSTOMIZED                  164
#define IDB_CUSTOMIZEU                  165
#define IDR_FIELD_POP                   168
#define IDR_MERGE_POP                   169
#define IDR_PROP                        170
#define IDB_BMP_AQUA                    172
#define IDB_BMP_LUNA                    173
#define IDB_BMP_PHOTON                  174
#define IDB_CUSTOMIZEU_E                177
#define IDB_CUSTOMIZED_E                178
#define IDB_SLOPE_D                     180
#define IDB_SLOPE_U                     181
#define IDB_ROADD                       182
#define IDB_ROADU                       183
#define IDB_SMOOTHRANGED                184
#define IDB_SMOOTHRANGEU                185
#define IDD_MATERIAL_PROP               191
#define IDD_ORNAMENT_PLANT              192
#define IDD_WORLDLIGHT                  193
#define IDD_ATTR_FIELDCOLOR             195
#define IDD_PE_HEIGHT                   197
#define IDD_SEARCH                      198
#define IDD_ATTR_WEATHER                199
#define IDD_SABER_TEST_DLG              200
#define IDD_ATTR_FIELD_HEATHAZE         201
#define IDD_ORNAMENT_HEATHAZE           202
#define IDR_MENU_IDLE                   204
#define IDR_MENU_INDOOR                 205
#define IDR_MENU_SAVE_AUTO              205
#define IDR_MENU1                       206
#define IDD_PATH_ENGINE_EXPORT          207
#define IDD_WORLD_VIEW                  208
#define IDR_POPUP_WORLD_VIEW            209
#define IDD_PATH_MESH_FIND              211
#define IDD_LIGHT_INDOOR                212
#define IDD_LIGHT_OBJECT                212
#define IDD_ATTR_LIGHT_NEW              213
#define IDD_LIGHT_MODE                  214
#define IDD_GAME_PROPERTY               215
#define IDD_ATTR_GAMEPROP               216
#define IDD_ORNAMENT_DECAL_VOLUME       217
#define IDD_SPAWN_POPUP                 219
#define IDD_VISIBLE_PROP                221
#define IDD_EFFECT_PROP                 222
#define IDD_ORNAMENT_DOJO               223
#define IDD_ORNAMENT_DOJO_POPUP         224
#define IDR_MENU_OBJECT_POPUP           227
#define IDD_ATTR_FIELD_SOUND            228
#define IDD_SPAWN_MERGE                 229
#define IDC_EDIT1                       1000
#define IDC_TRIGGER_NAME                1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_WorldSectorVertNum          1004
#define IDC_DEPTHMAP_HEIGHT_MAX         1004
#define IDC_SL_BRIGHTNESS_MAX           1004
#define IDC_ENTITY02_TEXTURE_NAME       1004
#define IDC_EDIT6                       1004
#define IDC_WorldSectorNum              1005
#define IDC_VERT_ALPHA                  1005
#define IDC_ENTITY00_POS_Y              1005
#define IDC_WorldSectorSize             1006
#define IDC_ENTITY00_POS_Z              1006
#define IDC_WorldSectorHalfNum          1007
#define IDC_EDIT9                       1007
#define IDC_ENTITY00_SCALE              1007
#define IDC_WorldSectorPolyNum          1008
#define IDC_EDIT23                      1008
#define IDC_MR                          1008
#define IDC_ENTITY01_POS_Y              1008
#define IDC_WorldSize                   1009
#define IDC_DT                          1009
#define IDC_ENTITY01_POS_Z              1009
#define IDC_WorldSizeHalf               1010
#define IDC_ENTITY01_SCALE              1010
#define IDC_WorldValueMax               1011
#define IDC_DIR                         1011
#define IDC_ENTITY02_POS_X              1011
#define IDC_WorldValueMin               1012
#define IDC_NMP_TNAME_01                1012
#define IDC_POS                         1012
#define IDC_ENTITY02_POS_Y              1012
#define IDC_SIZE_X                      1012
#define IDC_WorldFieldSize              1013
#define IDC_NMP_TNAME_02                1013
#define IDC_ENTITY02_POS_Z              1013
#define IDC_SIZE_Y                      1013
#define IDC_WorldFieldNum               1014
#define IDC_NMP_TNAME_03                1014
#define IDC_ENTITY02_SCALE              1014
#define IDC_SIZE_Z                      1014
#define IDC_WorldFieldHalfNum           1015
#define IDD_TERRAIN                     1015
#define IDC_NMP_TNAME_04                1015
#define IDC_MACRO                       1015
#define IDC_SPECULAR_SCALE_X            1015
#define IDC_EDIT5                       1016
#define IDC_CAM_TRANSLATION_GO          1016
#define IDD_FIELDUI                     1016
#define IDC_NMP_TNAME_05                1016
#define IDC_EDIT17                      1016
#define IDC_SPECULAR_SCALE_Y            1016
#define IDC_GROUP                       1016
#define IDC_INFO                        1016
#define IDC_RAISE                       1017
#define IDC_CAM_VELOCITY_OK             1017
#define IDD_ATTR_FOG                    1017
#define IDC_RAW_FILE_NAME               1017
#define IDC_NMP_TNAME_06                1017
#define IDC_EDIT18                      1017
#define IDC_SPECULAR_POWER              1017
#define IDC_TAP_S                       1017
#define IDC_SECTOR_TRANSLATION_GO       1017
#define IDC_EDIT_AGENCY                 1017
#define IDC_LOWER                       1018
#define IDD_ATTR_SKY                    1018
#define IDC_NMP_TNAME_07                1018
#define IDC_EDIT19                      1018
#define IDC_SPECULAR_POS_Y              1018
#define IDC_TAP_R                       1018
#define IDC_FIELD_TRANSLATION_GO        1018
#define IDC_WorldBlockNum               1018
#define IDC_PLATEAU                     1019
#define IDD_WATER                       1019
#define IDC_NMP_TNAME_08                1019
#define IDC_EDIT20                      1019
#define IDC_TAP_T                       1019
#define IDC_WorldBlockSize              1019
#define IDC_JUST                        1020
#define IDD_ATTR_LIGHT                  1020
#define IDC_NMP_TNAME_09                1020
#define IDC_EDIT21                      1020
#define IDC_ROT_X                       1020
#define IDC_STANDARDIZE                 1021
#define IDD_ATTR_SL                     1021
#define IDC_NMP_TNAME_10                1021
#define IDC_ROT_Y                       1021
#define IDC_SMOOTH                      1022
#define IDD_SHADOW                      1022
#define IDC_NMP_TNAME_11                1022
#define IDC_EDIT22                      1022
#define IDC_ROT_Z                       1022
#define IDC_CUSTOMIZE                   1023
#define IDD_EFFECT                      1023
#define IDC_NMP_TNAME_12                1023
#define IDC_CUSTOMIZE_E                 1024
#define IDD_NORMAL_MAP_PROP             1024
#define IDC_NMP_TNAME_13                1024
#define IDC_CUSTOMIZE_EDIT              1025
#define IDC_NMP_TNAME_14                1025
#define IDD_ATTR_BGM                    1025
#define IDC_BLT0_ANG                    1026
#define IDD_ATTR_SE                     1026
#define IDC_BLT0_CREATE_BTN             1027
#define IDD_OBJ_PROP                    1027
#define IDC_BLT0_DELETE_BTN             1028
#define IDD_VISIBILITY_DIST             1028
#define IDC_BLT0_MODIFY_BTN2            1029
#define IDC_NMP_TNAME_15                1029
#define IDD_SPAWN_PALETTE               1029
#define IDC_DLT0_ANG                    1030
#define IDC_SKY_BLENDED_TEXTURE0_LOAD   1030
#define IDD_SPAWN_MACRO                 1030
#define IDC_DLT1_ANG                    1031
#define IDC_SKY_BLENDED_TEXTURE1_LOAD   1031
#define IDC_DLT2_ANG                    1032
#define IDD_SPAWN_PARTY                 1032
#define IDC_BLT0_EDIT                   1033
#define IDC_DOODAD_RX                   1033
#define IDC_SKY_BLENDED_TEXTURE1_DEL    1033
#define IDD_SPAWN_BASE                  1033
#define IDC_DLT0_EDIT                   1034
#define IDC_DOODAD_TX                   1034
#define IDC_SKY_BLENDED_TEXTURE0_NAME   1034
#define IDD_SPAWN_SEARCH                1034
#define IDC_DLT1_EDIT                   1035
#define IDC_SKY_BLENDED_TEXTURE1_NAME   1035
#define IDD_MINIMAP                     1035
#define IDC_DLT2_EDIT                   1036
#define IDC_SKY_BLENDED_TEXTURE0_DEL    1036
#define IDD_SPAWN_NEST_CNT              1036
#define IDC_BLT0_ACT_BTN                1037
#define IDD_ATTR_FIELDNAME              1037
#define IDC_BRUSH_SIZE                  1038
#define IDC_DOODAD_SY                   1038
#define IDD_FIELD_INFO                  1038
#define IDC_BRUSH_SENSITIVITY           1039
#define IDC_DOODAD_RY                   1039
#define IDD_SOFTSPOT                    1039
#define IDC_CLIP_DISTANCE               1039
#define IDC_DIFFUSE_PICKER              1040
#define IDC_DOODAD_TY                   1040
#define IDD_LIGHT_SHADOW                1040
#define IDC_DIFFUSE_PICKER_R            1041
#define IDC_TAP_MOVEMENT_EDIT           1041
#define IDD_ATTR_BLOOM                  1041
#define IDC_DLT0_CREATE_BTN             1042
#define IDC_ANGLE                       1042
#define IDD_PERFORMANCE                 1042
#define IDC_DLT0_DELETE_BTN             1043
#define IDC_ATTR_FOG_NEAR               1043
#define IDC_RADIUS                      1043
#define IDD_PERFORMANCE_SECTORCULL      1043
#define IDC_DIFFUSE_PICKER_G            1044
#define IDC_DOODAD_SZ                   1044
#define IDD_PERFORMANCE_OCCLUSION       1044
#define IDC_RADIUS2                     1044
#define IDC_ANGLE2                      1044
#define IDC_SAMPLE                      1044
#define IDC_DLT1_CREATE_BTN             1045
#define IDC_DOODAD_RZ                   1045
#define IDC_ATTR_FOG_FAR                1045
#define IDC_S_TAP_VALUE                 1045
#define IDD_PERFORMANCE_PVS             1045
#define IDC_DLT1_DELETE_BTN             1046
#define IDC_DOODAD_TZ                   1046
#define IDC_R_TAP_VALUE                 1046
#define IDD_PERFORMANCE_IMPOSTER        1046
#define IDC_BLT0_ADDR                   1047
#define IDC_DOODAD_SRAND_PB             1047
#define IDC_DOODAD_SCALE_X              1047
#define IDD_WATER_TAB                   1047
#define IDC_DLT2_CREATE_BTN             1048
#define IDC_DOODAD_SX                   1048
#define IDD_SHORELINE                   1048
#define IDC_DLT2_DELETE_BTN             1049
#define IDC_TREE                        1049
#define IDD_ORNAMENT_DECAL              1049
#define IDC_DLT0_ADDR                   1050
#define IDC_DOODAD_SRAND_RANGE_EB       1050
#define IDD_ORNAMENT_TAB                1050
#define IDC_DLT0_ACT_BTN                1051
#define IDC_DOODAD_RRAND_PB             1051
#define IDD_SPAWN_PATH                  1051
#define IDC_DLT1_ACT_BTN                1052
#define IDC_DOODAD_RRAND_RANGE_EB       1052
#define IDC_DOODAD_SCALE_Y              1052
#define IDD_SPAWN_MACRO_MODIFY          1052
#define IDC_DLT2_ACT_BTN                1053
#define IDC_DOODAD_TRAND_PB             1053
#define IDC_DOODAD_SCALE_Z              1053
#define IDD_SKY_FLOATING_ENTITY         1053
#define IDC_DLT1_ADDR                   1054
#define IDC_DOODAD_TRAND_RANGE_EB       1054
#define IDD_SPAWN_GROUP_PROP_DLG        1054
#define IDC_DLT2_ADDR                   1055
#define IDD_SABER_VIEW1                 1055
#define IDC_DLT3_CREATE_BTN             1056
#define IDD_SABER_VIEW2                 1056
#define IDC_DLT3_DELETE_BTN             1057
#define IDD_SABER_VIEW3                 1057
#define IDC_DLT3_EDIT                   1058
#define IDD_BOOKMARK                    1058
#define IDC_DLT3_ANG                    1059
#define IDC_DLT3_ACT_BTN                1060
#define IDC_DLT3_ADDR                   1061
#define IDC_DLT4_CREATE_BTN             1062
#define IDC_DLT4_DELETE_BTN             1063
#define IDC_DLT4_EDIT                   1064
#define IDC_DLT4_ANG                    1065
#define IDC_DLT4_ACT_BTN                1066
#define IDC_DLT4_ADDR                   1067
#define IDC_BRUSH_SIZE_SLIDER           1068
#define IDC_PORTALX                     1069
#define IDC_DLT0_MODIFY_BTN2            1069
#define IDC_CLIP_DISTANCE_SLIDER        1069
#define IDC_BRUSH_SENSITIVITY_SLIDER    1070
#define IDC_PORTALY                     1070
#define IDC_PORTALZ                     1071
#define IDC_DLT1_MODIFY_BTN2            1071
#define IDC_DLT2_MODIFY_BTN2            1072
#define IDC_FIELD_VISIBLE               1072
#define IDC_CAM_VELOCITY                1072
#define IDC_DLT3_MODIFY_BTN2            1073
#define IDC_MERGE_VISIBLE               1073
#define IDC_CAM_FOV                     1073
#define IDC_DLT4_MODIFY_BTN2            1074
#define IDC_LOAD_FIELDMAP               1074
#define IDC_CAM_DIST                    1074
#define IDC_OPACITY_EDIT                1075
#define IDC_LOAD_MERGEMAP               1075
#define IDC_CAMERATYPE_COMBO            1075
#define IDC_OPACITY_SLIDER              1076
#define IDC_MERGE_HEIGHTFIELD           1076
#define IDC_PORTAL_SECTOR               1076
#define IDC_HEIGHTFIELD_EDIT            1077
#define IDC_ATTRIBUTE                   1077
#define IDC_MERGE_HEIGHTFIELD2          1077
#define IDC_PORTAL_FIELD                1077
#define IDC_HEIGHTFIELD_SLIDER          1078
#define IDC_LINK_WORLD                  1078
#define IDC_MERGE_WORLD_NAME_EDIT       1079
#define IDC_SLOPE                       1079
#define IDC_SMOOTHRANGE                 1080
#define IDC_MERGE_HEIGHTFIELD3          1080
#define IDC_FOG_COLOR_PICKER            1081
#define IDC_ROAD                        1081
#define IDC_MERGE_HEIGHTFIELD4          1081
#define IDC_ATTR_FOG_R                  1082
#define IDC_MERGE_HEIGHTFIELD5          1082
#define IDC_ATTR_FOG_G                  1083
#define IDC_MERGE_MAPNAME               1083
#define IDC_ATTR_FOG_B                  1084
#define IDC_MERGE_HEIGHTFIELD6          1084
#define IDC_MERGE_TEXTURE               1085
#define IDC_BASESKY_COLOR               1085
#define IDC_DIRECTIONAL_COLOR_PICKER    1085
#define IDC_MERGE_BLOOM                 1085
#define IDC_MERGE_DIFFUSE               1086
#define IDC_BASESKY_TEXTURE             1086
#define IDC_ATTR_DIRECTIONAL_R          1086
#define IDC_SKY_PALETTE                 1086
#define IDC_ATTR_DIRECTIONAL_G          1087
#define IDC_BASESKY_NOTHING             1087
#define IDC_MERGE_SPAWN_FILENAME_DST    1087
#define IDC_ATTR_DIRECTIONAL_B          1088
#define IDC_BTN_MERGE_SPAWN_DST         1088
#define IDC_MERGE_TRIGGER               1089
#define IDC_SKY_RGB0_PICKER             1089
#define IDC_MERGE_DOODAD                1090
#define IDC_SKY_RGB0_R                  1090
#define IDC_MERGE_EFFECT                1091
#define IDC_SKY_RGB1_PICKER             1091
#define IDC_MERGE_SPAWN                 1091
#define IDC_SKY_RGB1_R                  1092
#define IDC_MERGE_SPAWN_FILENAME_SRC    1092
#define IDC_SKY_RGB1_G                  1093
#define IDC_BTN_MERGE_SPAWN_SRC         1093
#define IDC_SKY_RGB1_B                  1094
#define IDC_SKY_RGB2_PICKER             1095
#define IDC_SKY_RGB2_R                  1096
#define IDC_SKY_RGB2_G                  1097
#define IDC_SKY_RGB2_B                  1098
#define IDC_SKY_RGB0_G                  1099
#define IDC_SKY_RGB0_B                  1100
#define IDC_SKY_BASE_TEXTURE_NAME       1101
#define IDC_SKY_BASE_TEXTURE_LOAD       1102
#define IDC_SKY_BASE_SPEED              1103
#define IDC_SKY_BLENDED_TEXTURE0_SPEED  1104
#define IDC_SKY_BLENDED_TEXTURE1_SPEED  1105
#define IDC_SEQUENCE_TYPE               1110
#define IDC_CREATE_WATER                1111
#define IDC_MODIFY_HEIGHT               1112
#define IDC_RENDERSTATE_SRC             1113
#define IDC_RENDERSTATE_DST             1114
#define IDC_DEPTHMAP_SIZE               1116
#define IDC_CREATE_DEPTHMAP             1117
#define IDC_DELETE_DEPTHMAP             1118
#define IDC_VERT_DIFFUSE                1119
#define IDC_HEIGHT                      1120
#define IDC_ROT_TEX                     1121
#define IDC_ROT_SCL                     1122
#define IDC_DEPTHMAP_HEIGHT_MIN         1123
#define IDC_WATER_DIFFUSE_R             1124
#define IDC_WATER_DIFFUSE_G             1125
#define IDC_WATER_DIFFUSE_B             1126
#define IDC_MODIFY_WATER                1127
#define IDC_DELETE_WATER                1128
#define IDC_EXIST                       1129
#define IDC_OPA_DENSITY                 1130
#define IDC_ATTR_AMBIENT_R              1131
#define IDC_DEPTHMAP_EDIT               1131
#define IDC_ATTR_AMBIENT_G              1132
#define IDC_UV_ANI_CHECK                1132
#define IDC_EDIT_COLOR_G_AMBIENT        1132
#define IDC_ATTR_AMBIENT_B              1133
#define IDC_EDIT_COLOR_B_AMBIENT        1133
#define IDC_AMBIENT_COLOR_PICKER        1134
#define IDC_EDIT_COLOR_G_DIRECTIONAL1   1134
#define IDC_LIGHT_ANG_X                 1135
#define IDC_EDIT_COLOR_B_DIRECTIONAL1   1135
#define IDC_LIGHT_ANG_Y                 1136
#define IDC_EDIT_COLOR_G_DIRECTIONAL2   1136
#define IDC_LIGHT_ANG_Z                 1137
#define IDC_EDIT_COLOR_B_DIRECTIONAL2   1137
#define IDC_EDIT_COLOR_G_DIRECTIONAL3   1138
#define IDC_EDIT_COLOR_B_DIRECTIONAL3   1139
#define IDC_SL_SOFTNESS                 1140
#define IDC_EDIT_ANGLE_Y_DIRECTIONAL1   1140
#define IDC_SL_COLOR_PICKER             1141
#define IDC_EDIT_ANGLE_Z_DIRECTIONAL1   1141
#define IDC_SL_COLOR_R                  1142
#define IDC_EDIT_ANGLE_Y_DIRECTIONAL2   1142
#define IDC_SL_COLOR_G                  1143
#define IDC_EDIT_ANGLE_Z_DIRECTIONAL2   1143
#define IDC_SL_COLOR_B                  1144
#define IDC_EDIT_ANGLE_Y_DIRECTIONAL3   1144
#define IDC_SL_BRIGHTNESS_MIN           1145
#define IDC_EDIT_ANGLE_Z_DIRECTIONAL3   1145
#define IDC_SL_DIRECTION                1146
#define IDC_BLUR_PASS                   1147
#define IDC_MAPSIZE                     1148
#define IDC_SL_INTERPOLATION            1149
#define IDC_HEIGHTFIELD_LABEL           1150
#define IDC_TEXTURE_BRUSH_LABEL         1151
#define IDC_DIFFUSE_BRUSH_LABEL         1152
#define IDC_CREATE_SHADOW               1153
#define IDC_DIFFUSE_BRUSH_LABEL2        1153
#define IDC_DELETE_SHADOW               1154
#define IDC_DIFFUSE_BRUSH_LABEL3        1154
#define IDC_ANTIALIAS                   1155
#define IDC_LIGHT_POS                   1155
#define IDC_LIGHT_ROT                   1156
#define IDC_CREATE_OBJ_SHADOW           1156
#define IDC_FADE                        1157
#define IDC_SOFT_CREATE                 1157
#define IDC_DIRECTION                   1158
#define IDC_PS_PICKER                   1159
#define IDC_SHADOW_PICKER_R             1160
#define IDC_SHADOW_PICKER_G             1161
#define IDC_SHADOW_PICKER_B             1162
#define IDC_DELETE_OBJ_SHADOW           1163
#define IDC_PS_OPACITY_EDIT             1164
#define IDC_PS_OPACITY_SLIDER           1165
#define IDC_CREATE_SHADOW_PROP          1166
#define IDC_EFFECT_TREE                 1167
#define IDC_DELETE_SHADOW_PROP          1167
#define IDC_S_TAP_VALUE_EFFECT          1168
#define IDC_R_TAP_VALUE_EFFECT          1169
#define IDC_TAP_MOVEMENT_EDIT_EFFECT    1170
#define IDC_NMAPPROP00                  1171
#define IDC_NMAPPROP01                  1172
#define IDC_NMAPPROP02                  1173
#define IDC_NMAPPROP03                  1174
#define IDC_NMAPPROP04                  1175
#define IDC_NMAPPROP05                  1176
#define IDC_NMAPPROP06                  1177
#define IDC_NMAPPROP07                  1178
#define IDC_NMAPPROP08                  1179
#define IDC_NMAPPROP09                  1180
#define IDC_NMAPPROP10                  1181
#define IDC_NMAPPROP11                  1182
#define IDC_NMAPPROP12                  1183
#define IDC_NMAPPROP13                  1184
#define IDC_NMAPPROP14                  1185
#define IDC_NMAPPROP15                  1186
#define IDC_NMP_LOAD00                  1187
#define IDC_NMP_LOAD01                  1188
#define IDC_NMP_LOAD02                  1189
#define IDC_NMP_LOAD03                  1190
#define IDC_NMP_LOAD04                  1191
#define IDC_NMP_LOAD05                  1192
#define IDC_NMP_LOAD06                  1193
#define IDC_NMP_LOAD07                  1194
#define IDC_NMP_LOAD08                  1195
#define IDC_NMP_LOAD09                  1196
#define IDC_NMP_LOAD10                  1197
#define IDC_NMP_LOAD11                  1198
#define IDC_NMP_LOAD12                  1199
#define IDC_NMP_LOAD13                  1200
#define IDC_NMP_LOAD14                  1201
#define IDC_NMP_LOAD15                  1202
#define IDC_NMP_TNAME_00                1205
#define IDC_EXPORT_NMP                  1206
#define IDC_BGM_LISTBOX                 1209
#define IDC_ENV_LISTBOX                 1210
#define IDC_CURPROP                     1211
#define IDC_BGM_CURPROP                 1211
#define IDC_SE_TREE                     1212
#define IDC_ENV_CURPROP                 1212
#define IDC_TRIGGER                     1213
#define IDC_SID                         1214
#define IDC_SABER_VER                   1217
#define IDC_AABB                        1217
#define IDC_VISIBILITY_DIST             1218
#define IDC_AABB_MAX                    1219
#define IDC_BITPROP                     1220
#define IDC_APPLY_ALL                   1221
#define IDC_OBJ_NAME                    1221
#define IDC_RANGE_MIN                   1222
#define IDC_OBJ_NAME2                   1222
#define IDC_OBJ_ID                      1222
#define IDC_RANGE_MAX                   1223
#define IDC_LTMAP_FLAGS_OBJECT          1223
#define IDC_DIST                        1224
#define IDC_LTMAP_FLAGS_MATERIAL        1224
#define IDC_TEX_ANG                     1225
#define IDC_TEX_SCALE                   1226
#define IDC_DECAL_SIZE_X                1227
#define IDC_UV_SPEED                    1228
#define IDC_DECAL_SIZE_Z                1229
#define IDC_MACROTYPE                   1230
#define IDC_VISIBLE_DISTANCE            1230
#define IDC_NPC                         1231
#define IDC_CREATE                      1231
#define IDC_DECAL_COLOR_R               1231
#define IDC_MILEPOST_GUID               1231
#define IDC_SPAWN_SAVE                  1232
#define IDC_UV_OFFSET                   1232
#define IDC_CHECK1                      1233
#define IDC_SPAWN_LOAD                  1233
#define IDC_MOVETYPE                    1233
#define IDC_CHECK2                      1234
#define IDC_SPAWN_MACRO_MODIFY          1234
#define IDC_DELETE                      1235
#define IDC_DECAL_COLOR_G               1235
#define IDC_CHECK_PROP2                 1235
#define IDC_MACRO_SETUP                 1236
#define IDC_DECAL_COLOR_B               1236
#define IDC_CHECK_PROP3                 1236
#define IDC_SPAWN_PALETTE_SEARCH        1237
#define IDC_CHECK_PROP4                 1237
#define IDC_MOB                         1238
#define IDC_CHECK_PROP5                 1238
#define IDC_CHECK_PROP6                 1239
#define IDC_CREATE_ALL                  1240
#define IDC_TEXSIZE                     1241
#define IDC_CHECK_PROP7                 1241
#define IDC_SPAWN_EXPORT                1242
#define IDC_CHECK_PROP8                 1242
#define IDC_CREATE_MOB                  1242
#define IDC_MINIMAP_INFO                1242
#define IDC_NEST_MEMBER_CNT             1243
#define IDC_CHECK_PROP9                 1243
#define IDC_CREATE_NPC                  1243
#define IDC_COOLTIME                    1244
#define IDC_CHECK_PROP10                1244
#define IDC_CREATE_ALL4                 1244
#define IDC_CREATE_TIRGGER              1244
#define IDC_WANDER_RANGE                1245
#define IDC_CHECK_PROP11                1245
#define IDC_MOVE_RANGE                  1246
#define IDC_CHECK_PROP12                1246
#define IDC_DELAY_TIME                  1247
#define IDC_CHECK_PROP13                1247
#define IDC_SPAWN_MACRO                 1248
#define IDC_CHECK_PROP14                1248
#define IDC_MI                          1249
#define IDC_CHECK_PROP15                1249
#define IDC_CT                          1250
#define IDC_CHECK_PROP16                1250
#define IDC_MT                          1251
#define IDC_WR                          1252
#define IDC_MAPNAMECODE                 1254
#define IDC_CUR_MAPNAMECODE             1255
#define IDC_FI_FIELDS                   1255
#define IDC_FI_INFORMATION              1256
#define IDC_SAL_TAB                     1258
#define IDC_SOFT_PICKER                 1259
#define IDC_SOFT_R                      1260
#define IDC_SOFT_G                      1261
#define IDC_SOFT_B                      1262
#define IDC_SOFT_POS_X                  1263
#define IDC_SOFT_CREATE_BTN             1264
#define IDC_NAME_INDEX_CUR              1267
#define IDC_NAME_INDEX_INPUT            1268
#define IDC_SOFT_POS_Y                  1269
#define IDC_PERFORMACE_TAB              1269
#define IDC_SOFT_POS_Z                  1270
#define IDC_BUTTON1                     1270
#define IDC_SOFT_ROT_X                  1271
#define IDC_BUTTON2                     1271
#define IDC_SECTORCULL                  1271
#define IDC_SOFT_ROT_Y                  1272
#define IDC_BUTTON3                     1272
#define IDC_WATER_TAB                   1272
#define IDC_FIELD_CHECK                 1272
#define IDC_SOFT_ROT_Z                  1273
#define IDC_BUTTON4                     1273
#define IDC_SCRIPT_TREE                 1273
#define IDC_DEPTHMAP_SLIDER             1275
#define IDC_DEPTHMAP_RADIUS_SLIDER      1276
#define IDC_UV_PATTERN                  1276
#define IDC_SAVE                        1276
#define IDC_DECAL_LISTBOX               1277
#define IDC_ALPHA_VALUE                 1278
#define IDC_EXPORT                      1278
#define IDC_DECAL_MODE                  1279
#define IDC_PORTAL                      1279
#define IDC_APPLY                       1280
#define IDC_LOAD                        1280
#define IDC_DECAL_COLOR_PICKER          1281
#define IDC_COMBO_DECAL_VOLUME          1282
#define IDC_PATHPOINTLIST               1283
#define IDC_PATHLIST                    1284
#define IDC_PATHLISTVIEW                1286
#define IDC_PATH_OPEN                   1287
#define IDC_PATH_INDEX                  1289
#define IDC_PATH_MEMO                   1290
#define IDC_SPAWN_PLAYSCRIPT_SCENE_INDEX 1290
#define IDC_SPAWN_LIST                  1291
#define IDC_PATH_RADIUS                 1291
#define IDC_SPAWN_AISCRIPT_INDEX        1291
#define IDC_LIST_OPTION                 1292
#define IDC_SPAWN_AISCRIPT_SCENE_INDEX  1292
#define IDC_LEVEL_MIN                   1293
#define IDC_LEVEL_MAX                   1294
#define IDC_SKY_TYPE                    1294
#define IDC_SPAWN_INDEX                 1295
#define IDC_ENTITY00_CREATE             1295
#define IDC_SPAWN_COUNT_INFO            1296
#define IDC_ENTITY01_CREATE             1296
#define IDC_ENTITY02_CREATE             1297
#define IDC_ENTITY00_LENSFLARE          1298
#define IDC_ENTITY01_LENSFLARE          1299
#define IDC_ENTITY02_LENSFLARE          1300
#define IDC_ENTITY00_TEXTURE_NAME       1301
#define IDC_ENTITY01_TEXTURE_NAME       1302
#define IDC_ENTITY00_TEXTURE_LOAD       1303
#define IDC_ENTITY01_TEXTURE_LOAD       1304
#define IDC_ENTITY02_TEXTURE_LOAD       1305
#define IDC_ENTITY00_POS_X              1306
#define IDC_ENTITY01_POS_X              1307
#define IDC_SPAWN_GROUP_INDEX           1308
#define IDC_SPAWN_PLAYSCRIPT_INDEX      1309
#define IDC_SPECULAR_CREATE             1309
#define IDC_ANALYZE                     1310
#define IDC_DOODAD_PROP_LABEL           1311
#define IDC_SSM                         1312
#define IDC_MILEPOST_TEXT               1313
#define IDC_MILEPOST_MEMO               1314
#define IDC_LOS_FULL_BUILD              1315
#define IDC_REPORT                      1316
#define IDC_LOS_FULL_DESTROY            1317
#define IDC_PVS_BMP_FILE_NAME           1318
#define ID_LOAD_PVS_BMP                 1319
#define IDC_SPECULAR_REFLASH            1320
#define IDC_ALL_DELETE                  1322
#define IDC_ALL_UPDATE                  1323
#define IDC_PLANT_SET_LISTBOX           1324
#define IDC_REFRESH                     1325
#define IDC_NUM_MIN                     1326
#define IDC_PLANT_SET_RES_LISTBOX       1327
#define IDC_NUM_MAX                     1328
#define IDC_SCALE_MIN                   1329
#define IDC_SCALE_MAX                   1330
#define IDC_ROTATION_TERRAIN            1331
#define IDC_LIST_WORLDLIGHT             1334
#define IDC_COLOR_R                     1335
#define IDC_COLOR_G                     1336
#define IDC_COLOR_B                     1337
#define IDC_POS_X                       1338
#define IDC_COLOR_A                     1338
#define IDC_POS_Y                       1339
#define IDC_POS_Z                       1340
#define IDC_RADIUS_SLIDER               1341
#define IDC_WORLDLIGHT_PICKER           1342
#define IDC_ANGLE_SLIDER                1342
#define IDC_POSITION_X                  1343
#define IDC_SAMPLE_SLIDER               1343
#define IDC_FIELDCOLOR_PICKER           1347
#define IDC_ATTR_FIELDCOLOR_R           1348
#define IDC_ATTR_FIELDCOLOR_G           1349
#define IDC_ATTR_FIELDCOLOR_B           1350
#define IDC_OCCLUDER_NEW                1351
#define IDC_SCALE_X                     1352
#define IDC_SCALE_Y                     1353
#define IDC_SCALE_Z                     1354
#define IDC_PLANE_TYPE                  1355
#define IDC_PVS                         1356
#define IDC_FIELD_NUMBER                1361
#define IDC_FIELD_NUMBER_OK             1362
#define IDC_INDEX                       1363
#define IDC_INDEX_OK                    1364
#define IDC_NEST_COUNT                  1365
#define IDC_NEST_COUNT_OK               1366
#define IDC_COOL_TIME_OK                1368
#define IDC_COOL_TIME                   1369
#define IDC_MOVE_TYPE_OK                1370
#define IDC_COMBO1                      1371
#define IDC_WANDER_RANGE_OK             1372
#define IDC_ALL_OK                      1373
#define IDC_MOVE_RANGE_OK               1374
#define IDC_PE_HEIGHT                   1374
#define IDC_SEARCH_TEXT                 1375
#define IDC_DELAY_TIME_OK               1376
#define IDC_SEARCH_LIST                 1376
#define IDC_PATH_INDEX_OK               1378
#define IDC_SEARCH_FIELD_IDX            1378
#define IDC_CHECK_OBJECT                1379
#define IDC_CHECK_SE                    1380
#define IDC_SPAWN_GROUP_IDX             1381
#define IDC_CHECK_EFFECT                1381
#define IDC_SPAWN_GROUP_IDX_OK          1382
#define IDC_SEARCH_PORTAL               1382
#define IDC_PLAYSCRIPT_IDX              1383
#define IDC_SEARCH_SELECT_ERROR         1383
#define IDC_PLAYSCRIPT_IDX_OK           1384
#define IDC_COMBO_WEATHER1              1384
#define IDC_PLAYSCRIPT_SCENE_IDX        1385
#define IDC_COMBO_WEATHER2              1385
#define IDC_PLAYSCRIPT_SCENE_IDX_OK     1386
#define IDC_COMBO_WEATHER3              1386
#define IDC_CHECK_FIELD_ALL             1386
#define IDC_COMBO_WEATHER4              1387
#define IDC_CHARACTER                   1387
#define IDC_AISCRIPT_IDX                1387
#define IDC_COMBO_WEATHER5              1388
#define IDC_AISCRIPT_IDX_OK             1388
#define IDC_CHECK_OBJECT_SNAP           1388
#define IDC_AISCRIPT_SCENE_IDX2         1389
#define IDC_AISCRIPT_SCENE_IDX_OK       1390
#define IDC_SLIDER1                     1391
#define IDC_SLIDER2                     1392
#define IDC_SLIDER3                     1393
#define IDC_SLIDER4                     1394
#define IDC_SLIDER5                     1395
#define IDC_SLIDER_MPS                  1397
#define IDC_EDIT_MPS                    1398
#define IDC_SLIDER_EXTENT               1401
#define IDC_EDIT_EXTENT                 1402
#define IDC_SLIDER_SCALE                1403
#define IDC_EDIT_SCALE                  1404
#define IDC_SLIDER_EXTENT_RAND          1405
#define IDC_EDIT_EXTENT_RAND            1406
#define IDC_EDIT_DIST                   1407
#define IDC_WORLD                       1408
#define IDC_WORLD_TYPE                  1408
#define IDC_WorldHeightFieldNum         1409
#define IDC_WorldSectorTileSize         1410
#define IDC_WorldSectorTileNum          1411
#define IDC_WorldFieldSectorNum         1412
#define IDC_WorldTexAddr                1413
#define IDC_BTN_WORLD_PATH              1414
#define IDC_BTN_EXPORT_PATH             1415
#define IDC_EDIT_WORLD_PATH             1416
#define IDC_EDIT_EXPORT_PATH            1417
#define IDC_VIEW                        1418
#define IDC_BTN_LOAD_WORLD_MAP          1419
#define IDC_EDIT_WORLD_NAME             1421
#define IDC_EDIT_FIELD_CNT              1422
#define IDC_EDIT_OVERLAP_SIZE           1423
#define IDC_SABER_VIEW1_HIDE            1424
#define IDC_EDIT_WORLD_ID               1425
#define IDC_CHECK_BLOCK                 1427
#define IDC_CHECK_FIELD                 1428
#define IDC_CHECK_SECTOR                1429
#define IDC_BTN_SABER_CAMERA            1430
#define IDC_COMBO_SELECT                1431
#define IDC_BTN_SEARCH_AREA             1432
#define IDC_BTN_PORTAL                  1433
#define IDC_EDIT_SIZE                   1434
#define IDC_CHECK_NAVI_MESH             1435
#define IDC_CHECK_OBS_MESH              1436
#define IDC_BTN_SEARCH_ROT              1437
#define IDC_BTN_OBS_EXCEPTION           1438
#define IDC_BTN_IMPORT                  1439
#define IDC_LIGHTINDOOR_PICKER          1440
#define IDC_LIGHTOBJECT_PICKER          1440
#define IDC_LIST_LIGHT                  1441
#define IDC_PICKER_DECAL_VOLUME         1442
#define IDC_INSERT                      1443
#define IDC_CHECK_CIRCLE                1444
#define IDC_CHECK_CIRCLE_SCAN           1445
#define IDC_RADIO_REAL                  1446
#define IDC_RADIO_DUMMY                 1447
#define IDC_CHECK_VISIBLE_LINE          1448
#define IDC_CHECK_VISIBLE_PLANE         1449
#define IDC_COLOR_PICKER_AMBIENT        1452
#define IDC_EDIT_COLOR_R_AMBIENT        1453
#define IDC_CHECK_AMBIENT               1454
#define IDC_COLOR_PICKER_DIRECTIONAL1   1455
#define IDC_EDIT_COLOR_R_DIRECTIONAL1   1456
#define IDC_CHECK_DIRECTIONAL1          1457
#define IDC_COLOR_PICKER_DIRECTIONAL2   1458
#define IDC_EDIT_COLOR_R_DIRECTIONAL2   1459
#define IDC_CHECK_DIRECTIONAL2          1460
#define IDC_COLOR_PICKER_DIRECTIONAL3   1461
#define IDC_EDIT_COLOR_R_DIRECTIONAL3   1462
#define IDC_CHECK_DIRECTIONAL3          1463
#define IDC_EDIT_ANGLE_X_DIRECTIONAL1   1464
#define IDC_EDIT_ANGLE_X_DIRECTIONAL2   1465
#define IDC_EDIT_ANGLE_X_DIRECTIONAL3   1466
#define IDC_LIGHTMODE_PICKER            1467
#define IDC_EDIT_COLOR_R                1468
#define IDC_LIST_SHAPE                  1468
#define IDC_EDIT_COLOR_G                1469
#define IDC_CHECK_PROP1                 1469
#define IDC_EDIT_COLOR_B                1470
#define IDC_EDIT_ANGLE_X                1471
#define IDC_EDIT_ANGLE_Y                1472
#define IDC_EDIT_ANGLE_Z                1473
#define IDC_BUTTON_GET                  1474
#define IDC_BUTTON_SET                  1475
#define IDC_LISTBOX_DECAL               1478
#define IDC_POSITION_Y                  1479
#define IDC_POSITION_Z                  1480
#define IDC_ROTATION_X                  1481
#define IDC_ROTATION_Y                  1482
#define IDC_ROTATION_Z                  1483
#define IDC_APPEND_POS                  1484
#define IDC_APPEND_OFFSET               1484
#define IDC_VISIBLE_DIST                1485
#define IDC_BTN_PATH_ENGINE_DATA_EXPORT 1485
#define IDC_BUTTON5                     1486
#define IDC_PREVIEW                     1488
#define IDC_AISCRIPT_SCENE_IDX          1489
#define IDC_CHECK_ACTIVE                1490
#define IDC_CHECK_PROP                  1491
#define IDC_SLIDER_VISIBLE_DIST         1492
#define IDC_EDIT_VISIBLE_DIST           1493
#define IDC_EDIT_NAME                   1494
#define IDC_LIST_CNT_TEXT               1494
#define IDC_LIST_LEVEL                  1495
#define IDC_EDIT_DOJO_ID                1496
#define IDC_EDIT_FADE_TIME              1497
#define IDC_EDIT_FADE_TIME2             1498
#define IDC_COMBO_LEVEL                 1505
#define IDC_BUTTON_LOAD_OBJECT          1506
#define IDC_EDIT_NAME_OBJECT            1509
#define IDC_EDIT_NAME_EFFECT_UP         1510
#define IDC_EDIT_NAME_EFFECT_DOWN       1511
#define IDC_CHECK_FADE_USE              1512
#define IDC_BUTTON_RESET                1513
#define IDC_CHECK_FADE_USE2             1516
#define IDC_EDIT7                       1516
#define IDC_EDIT8                       1517
#define IDC_BUTTON6                     1518
#define IDC_BUTTON7                     1519
#define IDC_BUTTON8                     1520
#define IDC_CHECK_DECAL                 1520
#define IDC_CHECK_WORLD_LIGHT           1521
#define IDC_CHECK_ATTACH_MODE           1522
#define IDC_COMBO_FUNC                  1523
#define IDC_OBJECT_TYPE                 1525
#define IDC_MINIMAP_LAYER               1526
#define IDC_COMBO_BGM                   1527
#define IDC_COMBO_ENV                   1528
#define IDC_COMBO_SHARE_0               1529
#define IDC_COMBO_SHARE_1               1530
#define IDC_COMBO_SHARE_2               1531
#define IDC_COMBO_SHARE_3               1532
#define IDC_COMBO_SHARE_4               1533
#define IDC_BUTTON_EXPORT_BGM           1534
#define IDC_BUTTON_EXPORT_ENV           1535
#define IDC_LIST_PATH_LIST_DST          1535
#define IDC_BUTTON_EXPORT_SHARE         1536
#define IDC_LIST_PATH_LIST_SRC          1536
#define IDC_MERGE_SPAWN_PATH            1536
#define IDC_UPDATE_PARAM                1538
#define IDC_EXPORT_SPAWN_LIST           1539
#define IDC_EXPORT_RULE_OUT             1540
#define ID_MENU_CAMERA_ATTR             32771
#define ID_CAMERA_ATTR                  32772
#define ID_PALETTE_TERRAIN              32773
#define ID_PALETTE_ORNAMENT             32774
#define ID_PALETTE_UNIT                 32775
#define ID_PALETTE_REGION               32776
#define ID_PALETTE_TRIGGER              32777
#define ID_COLLISIONTREE_GENERATION     32778
#define ID_32779                        32779
#define ID_VSHADOW_GENERATION_4_CURRENT_FIELDS 32780
#define ID_GENERATE_1                   32781
#define ID_OPTION_FOG                   32782
#define ID_VIEW_FREE                    32783
#define ID_VIEW_TOP                     32784
#define ID_VIEW_CAMERA                  32785
#define ID_VIEW_OBJECT                  32786
#define ID_VIEW_UI                      32787
#define ID_UI_FIELDGUIDELINE            32788
#define ID_UI_FIELDSELECTION            32789
#define ID_UI_SECTORGUIDELINE           32790
#define ID_CAMERA_PORTAL                32791
#define ID_VIEW_RENDER                  32792
#define ID_FILLMODE_WIREFRAME           32793
#define ID_FILLMODE_POINT               32794
#define ID_FILLMODE_SOLID               32795
#define ID_Menu                         32796
#define ID_FILE_ALL                     32797
#define ID_FILE_SAVEALL                 32798
#define ID_PALETTE_FIELDMERGE           32799
#define ID_PORTAL                       32800
#define ID_CREATEAMINIMAP               32801
#define ID_TEMP_CREATEASHADOWMAP        32802
#define ID_TEMP_MERGE                   32803
#define ID_MERGE                        32804
#define ID_FILE_VERIFICATION            32805
#define ID_TEMP_FOG                     32806
#define ID_ATTR_FOG                     32807
#define ID_TEMP_SKY                     32808
#define ID_TEMP_SKY32809                32809
#define ID_ATTR_SKY                     32810
#define ID_PALETTE_WATER                32811
#define ID_GENERATE_GENERATECYNISFIELD  32812
#define ID_OBJECT_WATER                 32813
#define ID_OBJECT_MAPOBJECTS            32814
#define ID_OPTION_WATER                 32815
#define ID_OPTION_MAPOBJ                32816
#define ID_TEMP_LIGHT                   32817
#define ID_ATTR_LIGHT                   32818
#define ID_TEMP_SLOPELIGHTING           32819
#define ID_MENU_SLOPELIGHTING           32820
#define ID_GENERATE_GENERATECYNISDOODADS 32821
#define ID_PALETTE_SHADOW               32822
#define ID_OBJECT_ANIMATIBLEDOODADPOSITION 32823
#define ID_OBJECT_ANIMATIBLE_DOODAD_DUMMY 32824
#define ID_OBJECT_VISION                32825
#define ID_OBJECT_WIRETERRAIN           32826
#define ID_OBJECT_DISPLAYWIREFRAME      32827
#define ID_DISPLAY_TERRAIN              32828
#define ID_DISPLAY_FILLMODE             32829
#define ID_PALETTE_EFFECT               32833
#define ID_VISION_EFFECTS               32837
#define ID_PALETTE_NORMALMAPPROPERTY    32838
#define ID_TEMP_CREATE                  32839
#define ID_TEMP_DELETE                  32840
#define ID_PROP_CREATE                  32841
#define ID_PROP_DELETE                  32842
#define ID_TEMP_BGM                     32843
#define ID_FIELD_BGM                    32844
#define ID_VISION_SOUNDMUTE             32845
#define ID_GENERATE_EXPORT              32846
#define ID_MENU_EXPORT_TRIGGER          32847
#define ID_INFO_VERSION                 32848
#define ID_TEMP_HEIGHTFIELDUPDATE       32849
#define ID_HEIGHTFIELDUPDATE            32850
#define ID_EXPORT_EXPORTMAPPROP         32853
#define ID_EXPORT_EXPORTP               32854
#define ID_EXPORT_PEC                   32855
#define ID_VISION_VISIBILITYDISTANCE    32856
#define ID_TEMP_VISIBILITYDISTANCE      32857
#define ID_VISIBILITY_DISTANCE          32858
#define ID_PALETTE_SPAWN                32859
#define ID_VISION_COLLISIONOBJECT       32860
#define ID_TEMP_FIELDNAME               32865
#define ID_FIELD_FIELDNAME              32866
#define ID_TEMP_INFORMATION             32867
#define ID_INFORMATION                  32868
#define ID_111_DELETE                   32869
#define ID_TEMP_BLOOM                   32870
#define ID_FIELD_MONOPOWER              32871
#define ID_VISION_BLOOMEFFECT           32872
#define ID_PALETTE_SOUNDEFFECT          32873
#define ID_PALETTE_PERFORMANCE          32874
#define ID_VISION_PERFORMANCESECTORCULL 32875
#define ID_111_CREATETRANSPARENTTILES   32876
#define ID_111_DELETETRANSPARENTTILES   32877
#define ID_CREATE_TRANSPARENT_TILES     32878
#define ID_DELETE_TRANSPARENT_TILES     32879
#define ID_EXPORT_EXPORTMAPNAME         32880
#define ID_TEMP_CREATEPVS               32881
#define ID_CREATE_PVS                   32882
#define ID_TEMP_DESTROYPVS              32883
#define ID_DESTROY_PVS                  32884
#define ID_VISION_PVSLOCKING            32885
#define ID_VISION_PVSACTIVATION         32886
#define ID_VISION_PROJECTIONSHADOW      32887
#define ID_VISION_FOGACTIVATION         32888
#define ID_TEMP_MATERIALUPDATE          32889
#define ID_MATERIAL_UPDATE              32890
#define ID_MATERIAL_PROP_UPDATE         32891
#define ID_VISION_PLANTSET              32892
#define ID_TEMP_FIELDCOLOR              32893
#define ID_EXPORT_EXPORTHEIGHTFIELDY    32894
#define ID_VISION_OCCLUDERACTIVATION    32895
#define ID_VISION_OBJECTWIREFRAME       32896
#define ID_UI_OBJECTWIREFRAME           32897
#define ID_EXPORT_EXPORTHEIGHTFIELDPE   32899
#define ID_EXPORT_EXPORTMAPPROP32900    32900
#define ID_EXPORT_EXPORTMAPPROPPE       32901
#define ID_UI_OBJECTVISIBLE             32902
#define ID_TEMP_FIELDSEARCH             32904
#define ID_FIELDSEARCH                  32905
#define ID_FIELDCOLOR                   32906
#define ID_VISION_MUTESOUNDALL          32907
#define ID_VISION_MUTEENV               32908
#define ID_VISION_MUTEBGM               32909
#define ID_VISION_SOUNDMUTE_BGM         32910
#define ID_VISION_SOUNDMUTE_ENV         32911
#define ID_TEMP_WEATHER                 32912
#define ID_WEATHER                      32913
#define ID_VISION_WEATHER               32914
#define ID_TEMP_FIELDHEATHAZE           32915
#define ID_Menu32916                    32916
#define ID_VISION_HEATHAZE              32917
#define ID_IDLE_CREATEWORLDOUTDOOR      32918
#define ID_IDLE_CREATEWORLDOUTDOOR32919 32919
#define ID_INDOOR_NEWWORLD              32920
#define ID_INDOOR_LOADWORLD             32921
#define ID_IDLE_OUTDOOR_NEWWORLD        32922
#define ID_IDLE_OUTDOOR_LOADWORLD       32923
#define ID_IDLE_INDOOR_NEWWORLD         32924
#define ID_OUTDOOR_NEWWORLD             32925
#define ID_OUTDOOR_LOADWORLD            32926
#define ID_NEWWORLD                     32927
#define ID_WORLD_LOAD                   32928
#define ID_WORLD_NEW                    32929
#define ID_FILE_EXIT                    32930
#define ID_VIEW_VIEW1                   32931
#define ID_VIEW_VIEW2                   32932
#define ID_VIEW_VIEW3                   32933
#define ID_FILE_SAVEALL32934            32934
#define ID_VIEW_VIEW0                   32935
#define ID_EXPORT_EXPORTPATHENGINEDATA  32936
#define ID_SABER_VIEW1                  32937
#define ID_SABER_VIEW2                  32938
#define ID_SABER_VIEW3                  32939
#define ID_FIELD_FIELDPORTAL            32940
#define ID_SECTOR_SECTORPORTAL          32941
#define ID_BLOCK_BLOCKPORTAL            32942
#define ID_BLOCK_PORTAL                 32943
#define ID_SECTOR_PORTAL                32944
#define ID_FIELD_PORTAL                 32945
#define ID_VISION_BSPWIREFRAME          32946
#define ID_GUIDELINE_BSPWIREFRAME       32947
#define ID_GUIDELINE_BSPWIREFRAME32948  32948
#define ID_UI_BSP_SECTOR                32949
#define ID_UI_BSP_WIREFRAME             32950
#define ID_UTIL_PATHENGINEUTIL          32951
#define ID_UTIL_BOOKMARK                32952
#define ID_BLOCK_GAMEPROPERTY           32955
#define ID_PALETTE_GAMEPROPERTY         32956
#define ID_PALETTE_WORLDVIEW            32957
#define ID_FILE_SAVEAUTO                32958
#define ID_FILE_SAVE_AUTO               32959
#define ID_BLOCK_SKYFLOATING            32960
#define ID_VISION_LIGHTMAP              32961
#define ID_UI_BSP_WIREFRAME_NV          32962
#define ID_GUIDELINE_BLOCK              32963
#define ID_UI_BLOCKGUIDELINE            32964
#define ID_VISION_PAUSEANIMATION        32965
#define AID_VISION_DOODADS_ANIMATION    32966
#define ID_VISION_DOODADS_ANIMATION     32967
#define ID_BLOCK_CREATEMINIMAP          32968
#define ID_TEMP_PROPERTYCLIPBOARDCOPY   32969
#define ID_TEMP_PROPERTYCLIPBOARDPASTE  32970
#define ID_PROPERTY_CLIPBOARD_COPY      32971
#define ID_PROPERTY_CLIPBOARD_PASTE     32972
#define ID_VISION_TERRAIN               32973
#define ID_VISION_TRIGGERUI             32974
#define ID_EXPORT_EXPORTINVALIDSECTORLINK 32975
#define ID_TEMP_PROOFSINVALIDSECTORLINK 32976
#define ID_VISION_MINIINDOORCULL        32977
#define ID_FILE_RESETOBJECTSERIALID     32978

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32979
#define _APS_NEXT_CONTROL_VALUE         1541
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
